In [4]:
#%%
from attack_utils import *
from matplotlib import pyplot as plt

In [ ]:
which_dataset = 1    # 'iris = 0', 'crop = 1', 'adult = 2', 'breast = 3', 'nursery = 4', 'mushroom = 5', 'bc-tcga = 6', 'digits = 7'
which_model = 0    # 'Decision_Tree = 0', 'Logistic_Regression = 1', 'Multinomial_Naive_Bayes = 2', 'K_Nearest_Neeighbor = 3', 'Random_Forest = 4', 'Multilayer_Perceptron = 5'
explanation_tool = 1 # 'Lime = 0', 'Shap = 1'
how_many_sets = 5 # This is the number of auxiliary datasets to experiment on. Lower the number for lowering the runtime.
sample_set_sizes = [5] # (list of n values from the paper) Size of auxiliary dataset (per class) in a list format
nfe = [3] # (list of k values from the paper) Number of features explored in a list format
query_limit = [500] # (list of Q values from the paper) Number of queries allowed for traversal

In [ ]:
## Shorten nfe for shorter runtime
results, other_args = run_attack_auto_v2(which_dataset, which_model, explanation_tool, how_many_sets, sample_set_sizes, nfe, query_limit, False, 5)

In [8]:
accuracies, rtest_sims, acc_baseline, rtest_sims_baseline, _, _ = run_attack_auto_compare(
                which_dataset, 
                which_model, 
                explanation_tool, 
                how_many_sets, 
                sample_set_sizes, 
                nfe, 
                query_limit, 
                False
            )

DATASET 1 0
Train results
[[75  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 75  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 75  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 75  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 75  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 75  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 75  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 75  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 75  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 75  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 75  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 75  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 75  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 75  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 75  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 75  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 75]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        75
           1       1.00      1.00      1.00        75
           2       1.00      1.00      1.00        75
           3       1.00      1.00      1.00        75
           4       1.00      1.00      1.00        75
           5       1.00      1.00      1.00        75
           6       1.00      1.00      1.00        75
           7       1.00      1.00      1.00        75
           8       1.00      1.00      1.00        75
           9       1.00      1.00      1.00        75
          10       1.00      1.00      1.00        75
          11       1.00      1.00      1.00        75
          12       1.00      1.00      1.00        75
          13       1.00      1.00      1.00        75
          14       1.00      1.00      1.00        75
          15       1.00      1.00      1.00        75
          16       1.00      1.00      1.00        75

    accuracy                           1.00      1275
   macro avg       1.00      1.00      1.00      1275
weighted avg       1.00      1.00      1.00      1275

Test results
[[15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 15  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 15  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 14  0  0  0  0  0  0  1  0  0  0  0]
 [ 0  0  0  0  0  0 15  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 15  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 15  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 15  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 15  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 15  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 15  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 15  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 15  0  0]
 [ 0  0  0  0  0  1  0  0  0  0  0  0  0  0  0 14  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 15]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00        15
           2       1.00      1.00      1.00        15
           3       1.00      1.00      1.00        15
           4       1.00      1.00      1.00        15
           5       0.93      0.93      0.93        15
           6       1.00      1.00      1.00        15
           7       1.00      1.00      1.00        15
           8       1.00      1.00      1.00        15
           9       1.00      1.00      1.00        15
          10       1.00      1.00      1.00        15
          11       1.00      1.00      1.00        15
          12       0.94      1.00      0.97        15
          13       1.00      1.00      1.00        15
          14       1.00      1.00      1.00        15
          15       1.00      0.93      0.97        15
          16       1.00      1.00      1.00        15

    accuracy                           0.99       255
   macro avg       0.99      0.99      0.99       255
weighted avg       0.99      0.99      0.99       255

Model test accuracy:  0.9922

Dataset:   Crop
ML Model:  Decision Tree
SHAP is the explanation tool currently in use

Lower bounds:  [15]  Upper bounds:  [508] (per class for both)

-----The attack starts here!-----

Number of top features allowed to be explored (k): 3

Number of samples per class (n): 5
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
[SHAP3]     Sample set 0, n_queries=575, Top similarity=0.9098
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0
Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 1.0

In [6]:
#print average similaties and accuracies for each explanation type and standard deviations
for etype in results:
    print(f"Explanation Type: {etype}")
    # print("Average Accuracy and Std Dev: ", np.mean(results[etype]['accuracies']), np.std(results[etype]['accuracies']))
    print("Average Similarity and Std Dev: ", np.mean(results[etype]['rtest_sims']), np.std(results[etype]['rtest_sims']))
    print()

Explanation Type: vanilla
Average Similarity and Std Dev:  0.79353 0.05446308933580614

In [ ]:
## Shorten nfe for shorter runtime
averages, similarities, _, _ = run_attack_auto(which_dataset, which_model, explanation_tool, how_many_sets, sample_set_sizes, nfe, query_limit, False)
print("Results Summary:")
print(np.average(similarities), np.std(similarities))

In [4]:
#%% Show results
print("Results Summary:")
print(np.average(similarities), np.std(similarities))
#write results to a file
with open("results_summary.txt", "a") as f:
    f.write(f"Dataset: {which_dataset}, Model: {which_model}, Explanation Tool: {explanation_tool}\n")
    f.write(f"Average Similarity: {np.average(similarities)}, Std Dev: {np.std(similarities)}\n")

Results Summary:
0.8470449999999999 0.09572119658153047


Run the attack notebook for all dataset/model combinations with a comparison to the Autolycus

In [2]:
# Run attack for all datasets and models, collect average similarities
import numpy as np

# Parameters for the attack
explanation_tool = 1  # Shap
how_many_sets = 20
sample_set_sizes = [5]
nfe = [3]
query_limit = [500]

# Results storage
all_results = []
baseline_results = []

In [ ]:
# Loop through all datasets and models
n_datasets = 6  # 0-5
n_models = 6    # 0-5

print("Running attacks for all dataset and model combinations...\n")

for which_dataset in range (n_datasets):
    for which_model in range(n_models):
        try:
            print(f"Dataset: {which_dataset}, Model: {which_model}...", end=" ")
            
            # Using run_attack_auto_compare 
            accuracies, rtest_sims, acc_baseline, rtest_sims_baseline, _, _ = run_attack_auto_compare(
                which_dataset, 
                which_model, 
                explanation_tool, 
                how_many_sets, 
                sample_set_sizes, 
                nfe, 
                query_limit, 
                False
            )
            
            # Flatten lists if they are nested because argmaxing may return nested chunks
            flat_sims = [s for batch in rtest_sims for s in batch] if len(rtest_sims) > 0 and isinstance(rtest_sims[0], list) else rtest_sims
            avg_similarity = float(np.mean(flat_sims)) if len(flat_sims) > 0 else np.nan
            
            if rtest_sims_baseline:
                flat_base = [s for batch in rtest_sims_baseline for s in batch] if len(rtest_sims_baseline) > 0 and isinstance(rtest_sims_baseline[0], list) else rtest_sims_baseline
                avg_base_similarity = float(np.mean(flat_base)) if len(flat_base) > 0 else np.nan
            else:
                avg_base_similarity = np.nan
                
            all_results.append({
                'dataset': which_dataset,
                'model': which_model,
                'avg_similarity': avg_similarity
            })
            baseline_results.append({
                'dataset': which_dataset,
                'model': which_model,
                'avg_similarity': avg_base_similarity
            })
            
            print(f"Avg Similarity: {avg_similarity:.4f} | Baseline: {avg_base_similarity:.4f}")
        except Exception as e:
            print(f"Error: {e}")
            all_results.append({'dataset': which_dataset, 'model': which_model, 'avg_similarity': np.nan})
            baseline_results.append({'dataset': which_dataset, 'model': which_model, 'avg_similarity': np.nan})

# Write results to file
print("\n\nWriting results to file...")
with open("results_all_combinations.txt", "w") as f:
    f.write("Dataset\tModel\tAvgSimilarity\tBaselineSimilarity\n")
    for main, base in zip(all_results, baseline_results):
        f.write(f"{main['dataset']}\t{main['model']}\t{main['avg_similarity']:.4f}\t{base['avg_similarity']:.4f}\n")

print("Results written to results_all_combinations.txt")

Running attacks for all dataset and model combinations...

Dataset: 0, Model: 0... DATASET 0 0
Train results
[[40  0  0]
 [ 0 38  0]
 [ 0  0 34]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       1.00      1.00      1.00        38
           2       1.00      1.00      1.00        34

    accuracy                           1.00       112
   macro avg       1.00      1.00      1.00       112
weighted avg       1.00      1.00      1.00       112

Test results
[[ 4  0  0]
 [ 0  5  1]
 [ 0  0 12]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       1.00      0.83      0.91         6
           2       0.92      1.00      0.96        12

    accuracy                           0.95        22
   macro avg       0.97      0.94      0.96        22
weighted avg       0.96      0.95      0.95        22

Model test accuracy:  0.9545

Dataset:   Iris
ML Model:  Decision Tree
SHAP is the explanation tool currently in use

Error: Sample larger than population or is negative
Dataset: 0, Model: 1... DATASET 0 1
Train results
[[40  0  0]
 [ 0 28  3]
 [ 0  0 41]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       1.00      0.90      0.95        31
           2       0.93      1.00      0.96        41

    accuracy                           0.97       112
   macro avg       0.98      0.97      0.97       112
weighted avg       0.98      0.97      0.97       112

Test results
[[ 8  0  0]
 [ 0 11  0]
 [ 0  0  3]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00         3

    accuracy                           1.00        22
   macro avg       1.00      1.00      1.00        22
weighted avg       1.00      1.00      1.00        22

Model test accuracy:  1.0

Dataset:   Iris
ML Model:  Logistic Regression
SHAP is the explanation tool currently in use

Error: Sample larger than population or is negative
Dataset: 0, Model: 2... DATASET 0 2
Train results
[[37  0  0]
 [ 0 37  1]
 [ 0  3 34]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        37
           1       0.93      0.97      0.95        38
           2       0.97      0.92      0.94        37

    accuracy                           0.96       112
   macro avg       0.97      0.96      0.96       112
weighted avg       0.97      0.96      0.96       112

Test results
[[9 0 0]
 [0 5 0]
 [0 0 8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00         5
           2       1.00      1.00      1.00         8

    accuracy                           1.00        22
   macro avg       1.00      1.00      1.00        22
weighted avg       1.00      1.00      1.00        22

Model test accuracy:  1.0

Dataset:   Iris
ML Model:  Multinomial Naive Bayes
SHAP is the explanation tool currently in use

Error: Sample larger than population or is negative
Dataset: 0, Model: 3... DATASET 0 3
Train results
[[42  0  0]
 [ 0 37  3]
 [ 0  2 28]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        42
           1       0.95      0.93      0.94        40
           2       0.90      0.93      0.92        30

    accuracy                           0.96       112
   macro avg       0.95      0.95      0.95       112
weighted avg       0.96      0.96      0.96       112

Test results
[[ 5  0  0]
 [ 0  4  0]
 [ 0  1 12]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       0.80      1.00      0.89         4
           2       1.00      0.92      0.96        13

    accuracy                           0.95        22
   macro avg       0.93      0.97      0.95        22
weighted avg       0.96      0.95      0.96        22

Model test accuracy:  0.9545

Dataset:   Iris
ML Model:  K Nearest Neighbor
SHAP is the explanation tool currently in use

Error: Sample larger than population or is negative
Dataset: 0, Model: 4... DATASET 0 4
Train results
[[37  0  0]
 [ 0 39  0]
 [ 0  0 36]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        37
           1       1.00      1.00      1.00        39
           2       1.00      1.00      1.00        36

    accuracy                           1.00       112
   macro avg       1.00      1.00      1.00       112
weighted avg       1.00      1.00      1.00       112

Test results
[[8 0 0]
 [0 6 0]
 [0 0 8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      1.00      1.00         6
           2       1.00      1.00      1.00         8

    accuracy                           1.00        22
   macro avg       1.00      1.00      1.00        22
weighted avg       1.00      1.00      1.00        22

Model test accuracy:  1.0

Dataset:   Iris
ML Model:  Random Forest
SHAP is the explanation tool currently in use

Lower bounds:  [84]  Upper bounds:  [582] (per class for both)

-----The attack starts here!-----

Number of top features allowed to be explored (k): 3

Number of samples per class (n): 5
Dataset name in traverse_explanations_SHAP3: iris
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0
Error: unhashable type: 'numpy.ndarray'
Dataset: 0, Model: 5... DATASET 0 5
Train results
[[34  0  0]
 [ 0 37  2]
 [ 0  1 38]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        34
           1       0.97      0.95      0.96        39
           2       0.95      0.97      0.96        39

    accuracy                           0.97       112
   macro avg       0.97      0.97      0.97       112
weighted avg       0.97      0.97      0.97       112

Test results
[[ 7  0  0]
 [ 0 11  0]
 [ 0  0  4]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00         4

    accuracy                           1.00        22
   macro avg       1.00      1.00      1.00        22
weighted avg       1.00      1.00      1.00        22

Model test accuracy:  1.0

Dataset:   Iris
ML Model:  Multilayer Perceptron
SHAP is the explanation tool currently in use

Error: Sample larger than population or is negative
Dataset: 1, Model: 0... DATASET 1 0
Train results
[[75  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 75  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 75  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 75  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 75  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 75  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 75  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 75  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 75  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 75  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 75  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 75  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 75  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 75  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 75  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 75  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 75]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        75
           1       1.00      1.00      1.00        75
           2       1.00      1.00      1.00        75
           3       1.00      1.00      1.00        75
           4       1.00      1.00      1.00        75
           5       1.00      1.00      1.00        75
           6       1.00      1.00      1.00        75
           7       1.00      1.00      1.00        75
           8       1.00      1.00      1.00        75
           9       1.00      1.00      1.00        75
          10       1.00      1.00      1.00        75
          11       1.00      1.00      1.00        75
          12       1.00      1.00      1.00        75
          13       1.00      1.00      1.00        75
          14       1.00      1.00      1.00        75
          15       1.00      1.00      1.00        75
          16       1.00      1.00      1.00        75

    accuracy                           1.00      1275
   macro avg       1.00      1.00      1.00      1275
weighted avg       1.00      1.00      1.00      1275

Test results
[[15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 15  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 15  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 14  0  0  0  0  0  0  1  0  0  0  0]
 [ 0  0  0  0  0  0 15  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 15  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 15  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 15  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 15  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 15  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 15  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 15  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 15  0  0]
 [ 0  0  0  0  0  1  0  0  0  0  0  0  0  0  0 14  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 15]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00        15
           2       1.00      1.00      1.00        15
           3       1.00      1.00      1.00        15
           4       1.00      1.00      1.00        15
           5       0.93      0.93      0.93        15
           6       1.00      1.00      1.00        15
           7       1.00      1.00      1.00        15
           8       1.00      1.00      1.00        15
           9       1.00      1.00      1.00        15
          10       1.00      1.00      1.00        15
          11       1.00      1.00      1.00        15
          12       0.94      1.00      0.97        15
          13       1.00      1.00      1.00        15
          14       1.00      1.00      1.00        15
          15       1.00      0.93      0.97        15
          16       1.00      1.00      1.00        15

    accuracy                           0.99       255
   macro avg       0.99      0.99      0.99       255
weighted avg       0.99      0.99      0.99       255

Model test accuracy:  0.9922

Dataset:   Crop
ML Model:  Decision Tree
SHAP is the explanation tool currently in use

Lower bounds:  [15]  Upper bounds:  [508] (per class for both)

-----The attack starts here!-----

Number of top features allowed to be explored (k): 3

Number of samples per class (n): 5
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0
Error: unhashable type: 'numpy.ndarray'
Dataset: 1, Model: 1... DATASET 1 1
Train results
[[75  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 74  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0 75  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 70  0  0  0  5  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 75  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 63  0  0  0  0  0  0  0  0  0 12  0]
 [ 0  0  0  0  0  0 73  0  0  0  0  0  0  2  0  0  0]
 [ 0  0  0  4  0  0  0 71  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 75  0  0  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0  0  0 69  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 75  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 75  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 75  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  0  0  0  0 74  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 75  0  0]
 [ 0  0  0  0  0 15  0  0  0  0  0  0  0  0  0 60  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 75]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        75
           1       0.93      0.99      0.95        75
           2       1.00      1.00      1.00        75
           3       0.95      0.93      0.94        75
           4       1.00      1.00      1.00        75
           5       0.81      0.84      0.82        75
           6       0.99      0.97      0.98        75
           7       0.93      0.95      0.94        75
           8       1.00      1.00      1.00        75
           9       0.99      0.92      0.95        75
          10       1.00      1.00      1.00        75
          11       1.00      1.00      1.00        75
          12       1.00      1.00      1.00        75
          13       0.97      0.99      0.98        75
          14       1.00      1.00      1.00        75
          15       0.83      0.80      0.82        75
          16       1.00      1.00      1.00        75

    accuracy                           0.96      1275
   macro avg       0.96      0.96      0.96      1275
weighted avg       0.96      0.96      0.96      1275

Test results
[[15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 15  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 15  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 12  0  0  0  0  0  0  1  0  0  2  0]
 [ 0  0  0  0  0  0 15  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0 14  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 15  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 15  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 15  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 15  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 15  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0  0  0 14  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 15  0  0]
 [ 0  0  0  0  0  1  0  0  0  0  0  0  0  0  0 14  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 15]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00        15
           2       1.00      1.00      1.00        15
           3       0.94      1.00      0.97        15
           4       1.00      1.00      1.00        15
           5       0.92      0.80      0.86        15
           6       1.00      1.00      1.00        15
           7       1.00      0.93      0.97        15
           8       1.00      1.00      1.00        15
           9       0.94      1.00      0.97        15
          10       1.00      1.00      1.00        15
          11       1.00      1.00      1.00        15
          12       0.94      1.00      0.97        15
          13       1.00      0.93      0.97        15
          14       1.00      1.00      1.00        15
          15       0.88      0.93      0.90        15
          16       1.00      1.00      1.00        15

    accuracy                           0.98       255
   macro avg       0.98      0.98      0.98       255
weighted avg       0.98      0.98      0.98       255

Model test accuracy:  0.9765

Dataset:   Crop
ML Model:  Logistic Regression
SHAP is the explanation tool currently in use

Lower bounds:  [15]  Upper bounds:  [508] (per class for both)

-----The attack starts here!-----

Number of top features allowed to be explored (k): 3

Number of samples per class (n): 5
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8900975029694654
Average confidence score for samples classified same by surrogate model: 0.9682081047135407
[SHAP3]     Sample set 0, n_queries=575, Top similarity=0.7804
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9284761972379336
Average confidence score for samples classified same by surrogate model: 0.958153736973045
[SHAP base] Sample set 0, n_queries=585, Top similarity=0.7608
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9068168734093437
Average confidence score for samples classified same by surrogate model: 0.9640786515052927
[SHAP3]     Sample set 1, n_queries=575, Top similarity=0.7725
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9259545601021318
Average confidence score for samples classified same by surrogate model: 0.9601816198788219
[SHAP base] Sample set 1, n_queries=585, Top similarity=0.7333
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.888467313990325
Average confidence score for samples classified same by surrogate model: 0.9674757691227595
[SHAP3]     Sample set 2, n_queries=575, Top similarity=0.7922
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9276415180457822
Average confidence score for samples classified same by surrogate model: 0.9593983579532831
[SHAP base] Sample set 2, n_queries=585, Top similarity=0.7373
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8757454075846823
Average confidence score for samples classified same by surrogate model: 0.9676295897387048
[SHAP3]     Sample set 3, n_queries=575, Top similarity=0.8196
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9161376212323277
Average confidence score for samples classified same by surrogate model: 0.9656030633992226
[SHAP base] Sample set 3, n_queries=585, Top similarity=0.7059
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9030781984611946
Average confidence score for samples classified same by surrogate model: 0.9645552456806923
[SHAP3]     Sample set 4, n_queries=575, Top similarity=0.7804
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9249448631255452
Average confidence score for samples classified same by surrogate model: 0.9625603032796164
[SHAP base] Sample set 4, n_queries=585, Top similarity=0.6941
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.887444523178698
Average confidence score for samples classified same by surrogate model: 0.9650546647754285
[SHAP3]     Sample set 5, n_queries=575, Top similarity=0.8196
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9070501281339558
Average confidence score for samples classified same by surrogate model: 0.9637223015184299
[SHAP base] Sample set 5, n_queries=585, Top similarity=0.7765
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9276876714838569
Average confidence score for samples classified same by surrogate model: 0.960607653671156
[SHAP3]     Sample set 6, n_queries=575, Top similarity=0.7098
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.91893280830983
Average confidence score for samples classified same by surrogate model: 0.9639383406465222
[SHAP base] Sample set 6, n_queries=585, Top similarity=0.7137
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8851009922529594
Average confidence score for samples classified same by surrogate model: 0.9709077268436738
[SHAP3]     Sample set 7, n_queries=575, Top similarity=0.7686
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9036211155438161
Average confidence score for samples classified same by surrogate model: 0.9623370793331928
[SHAP base] Sample set 7, n_queries=585, Top similarity=0.8078
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8653429661676199
Average confidence score for samples classified same by surrogate model: 0.9714420760294724
[SHAP3]     Sample set 8, n_queries=575, Top similarity=0.8078
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9072246477343789
Average confidence score for samples classified same by surrogate model: 0.9651344292474257
[SHAP base] Sample set 8, n_queries=585, Top similarity=0.7569
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9323213791088389
Average confidence score for samples classified same by surrogate model: 0.9566934267186895
[SHAP3]     Sample set 9, n_queries=575, Top similarity=0.7686
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9316514995021767
Average confidence score for samples classified same by surrogate model: 0.959924303109203
[SHAP base] Sample set 9, n_queries=585, Top similarity=0.6863
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8986739901891105
Average confidence score for samples classified same by surrogate model: 0.9661336139570976
[SHAP3]     Sample set 10, n_queries=575, Top similarity=0.7765
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9125403597570716
Average confidence score for samples classified same by surrogate model: 0.9634267911883224
[SHAP base] Sample set 10, n_queries=585, Top similarity=0.7569
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9003806527030322
Average confidence score for samples classified same by surrogate model: 0.9634138554591858
[SHAP3]     Sample set 11, n_queries=575, Top similarity=0.8039
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9008290977279527
Average confidence score for samples classified same by surrogate model: 0.9693181516512503
[SHAP base] Sample set 11, n_queries=585, Top similarity=0.7333
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8332255555364266
Average confidence score for samples classified same by surrogate model: 0.9710528782084263
[SHAP3]     Sample set 12, n_queries=575, Top similarity=0.8549
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8603702333655701
Average confidence score for samples classified same by surrogate model: 0.968428474001385
[SHAP base] Sample set 12, n_queries=585, Top similarity=0.8392
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.884350932596578
Average confidence score for samples classified same by surrogate model: 0.9689747395227336
[SHAP3]     Sample set 13, n_queries=575, Top similarity=0.7882
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9074979385023069
Average confidence score for samples classified same by surrogate model: 0.9672124475678784
[SHAP base] Sample set 13, n_queries=585, Top similarity=0.7294
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8998931351314652
Average confidence score for samples classified same by surrogate model: 0.9671411946456974
[SHAP3]     Sample set 14, n_queries=575, Top similarity=0.7608
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.909437011630301
Average confidence score for samples classified same by surrogate model: 0.9661880011413055
[SHAP base] Sample set 14, n_queries=585, Top similarity=0.7333
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8767843188020121
Average confidence score for samples classified same by surrogate model: 0.9674009298535509
[SHAP3]     Sample set 15, n_queries=575, Top similarity=0.8196
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9001550356964318
Average confidence score for samples classified same by surrogate model: 0.9650517302049048
[SHAP base] Sample set 15, n_queries=585, Top similarity=0.7843
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9159483869017596
Average confidence score for samples classified same by surrogate model: 0.9609334841094781
[SHAP3]     Sample set 16, n_queries=575, Top similarity=0.7804
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9040036839674104
Average confidence score for samples classified same by surrogate model: 0.9642948075482901
[SHAP base] Sample set 16, n_queries=585, Top similarity=0.7804
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9199035324295833
Average confidence score for samples classified same by surrogate model: 0.9617112810334827
[SHAP3]     Sample set 17, n_queries=575, Top similarity=0.7451
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9171652130194384
Average confidence score for samples classified same by surrogate model: 0.9608103831423064
[SHAP base] Sample set 17, n_queries=585, Top similarity=0.7765
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8762944424986574
Average confidence score for samples classified same by surrogate model: 0.9675087495184042
[SHAP3]     Sample set 18, n_queries=575, Top similarity=0.8196
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8955300805696434
Average confidence score for samples classified same by surrogate model: 0.9685130829357542
[SHAP base] Sample set 18, n_queries=585, Top similarity=0.7608
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8836426106496861
Average confidence score for samples classified same by surrogate model: 0.9687416566329272
[SHAP3]     Sample set 19, n_queries=575, Top similarity=0.7922
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9093198217726386
Average confidence score for samples classified same by surrogate model: 0.968774114802034
[SHAP base] Sample set 19, n_queries=585, Top similarity=0.702

=== Query limit 500 | k=3 | n=5 ===
  [SHAP3 main]    Avg similarity: 0.788  | All: [0.7804, 0.7725, 0.7922, 0.8196, 0.7804, 0.8196, 0.7098, 0.7686, 0.8078, 0.7686, 0.7765, 0.8039, 0.8549, 0.7882, 0.7608, 0.8196, 0.7804, 0.7451, 0.8196, 0.7922]
  [SHAP baseline] Avg similarity: 0.7484  | All: [0.7608, 0.7333, 0.7373, 0.7059, 0.6941, 0.7765, 0.7137, 0.8078, 0.7569, 0.6863, 0.7569, 0.7333, 0.8392, 0.7294, 0.7333, 0.7843, 0.7804, 0.7765, 0.7608, 0.702]
  Difference (main - baseline): +0.0396


========== FINAL COMPARISON SUMMARY ==========
  [SHAP3 main]    Overall avg similarity: 0.788
  [SHAP baseline] Overall avg similarity: 0.7484
  Overall difference (main - baseline): +0.0396
===============================================

Avg Similarity: 0.7880 | Baseline: 0.7484
Dataset: 1, Model: 2... DATASET 1 2
Train results
[[70  0  0  0  0  0  0  0  0  0  0  0  0  0  5  0  0]
 [ 0 70  0  0  0  0  0  0  0  5  0  0  0  0  0  0  0]
 [ 0  0 58  0  0  7  1  0  0  0  0  0  0  5  0  4  0]
 [ 0  0  0 56  0  0  0  7  0  0  0  0 10  0  1  1  0]
 [17  1  0  2 38  0  0  0  0  0  0  0  0  0 17  0  0]
 [ 0  0  7  0  0 38  0  7  0  0  0  0  0  0  0 23  0]
 [ 0  0  6  0  0  0 60  0  2  0  0  0  0  7  0  0  0]
 [ 3  2  5 14  2  4  0 22  1  0  0  0 10  1  0 11  0]
 [ 0  5  2  0  0  0  0  0 68  0  0  0  0  0  0  0  0]
 [ 0 20  0  0  1  0  0  0 21 29  3  0  1  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 75  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0  0 20 24  0 30  0  0]
 [ 0  0  0  1  3  1  0  0  0  0  6  0 51  0  6  2  5]
 [ 0  0 12  0  0  1  9  0 16  0  0  0  0 29  0  8  0]
 [20  0  0  0  0  0  0  0  0  0  0  9  1  0 45  0  0]
 [ 0  0  0  0  0 26  0  0  0  0  0  0  0  0  0 49  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 75]]
              precision    recall  f1-score   support

           0       0.63      0.93      0.75        75
           1       0.71      0.93      0.81        75
           2       0.64      0.77      0.70        75
           3       0.77      0.75      0.76        75
           4       0.86      0.51      0.64        75
           5       0.49      0.51      0.50        75
           6       0.86      0.80      0.83        75
           7       0.61      0.29      0.40        75
           8       0.63      0.91      0.74        75
           9       0.85      0.39      0.53        75
          10       0.89      1.00      0.94        75
          11       0.69      0.27      0.38        75
          12       0.53      0.68      0.59        75
          13       0.69      0.39      0.50        75
          14       0.43      0.60      0.50        75
          15       0.50      0.65      0.57        75
          16       0.94      1.00      0.97        75

    accuracy                           0.67      1275
   macro avg       0.69      0.67      0.65      1275
weighted avg       0.69      0.67      0.65      1275

Test results
[[14  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0]
 [ 0 12  0  0  0  0  0  0  0  3  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  1  0  0  0  0  0  0  0  6  0  0  0]
 [ 0  0  0 12  0  0  0  2  0  0  0  0  0  0  0  0  1]
 [ 4  0  0  0  8  0  0  0  0  0  1  0  0  0  2  0  0]
 [ 0  0  0  0  0  9  0  1  0  0  0  0  0  0  0  5  0]
 [ 0  0  0  0  0  0 10  0  2  0  0  0  0  3  0  0  0]
 [ 0  1  1  4  1  2  0  2  0  0  0  0  1  0  0  3  0]
 [ 0  1  0  0  0  0  0  0 14  0  0  0  0  0  0  0  0]
 [ 0  4  0  0  0  0  0  0  2  8  1  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 15  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  3  5  0  7  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  3  0 10  0  0  0  2]
 [ 0  1  4  0  0  0  3  0  3  0  0  0  0  3  0  1  0]
 [ 3  0  0  0  0  0  0  0  0  0  0  0  0  0 12  0  0]
 [ 0  0  0  0  0  8  0  0  0  0  0  0  0  0  0  7  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 15]]
              precision    recall  f1-score   support

           0       0.67      0.93      0.78        15
           1       0.63      0.80      0.71        15
           2       0.62      0.53      0.57        15
           3       0.75      0.80      0.77        15
           4       0.89      0.53      0.67        15
           5       0.45      0.60      0.51        15
           6       0.77      0.67      0.71        15
           7       0.40      0.13      0.20        15
           8       0.67      0.93      0.78        15
           9       0.73      0.53      0.62        15
          10       0.75      1.00      0.86        15
          11       1.00      0.20      0.33        15
          12       0.62      0.67      0.65        15
          13       0.25      0.20      0.22        15
          14       0.55      0.80      0.65        15
          15       0.44      0.47      0.45        15
          16       0.83      1.00      0.91        15

    accuracy                           0.64       255
   macro avg       0.65      0.64      0.61       255
weighted avg       0.65      0.64      0.61       255

Model test accuracy:  0.6353

Dataset:   Crop
ML Model:  Multinomial Naive Bayes
SHAP is the explanation tool currently in use

Lower bounds:  [15]  Upper bounds:  [508] (per class for both)

-----The attack starts here!-----

Number of top features allowed to be explored (k): 3

Number of samples per class (n): 5
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9947526088428266
Average confidence score for samples classified same by surrogate model: 0.996522351481497
[SHAP3]     Sample set 0, n_queries=575, Top similarity=0.7765
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9951352129508774
Average confidence score for samples classified same by surrogate model: 0.9964452906446795
[SHAP base] Sample set 0, n_queries=585, Top similarity=0.7569
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9945965902152473
Average confidence score for samples classified same by surrogate model: 0.997530378128702
[SHAP3]     Sample set 1, n_queries=575, Top similarity=0.5216
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9945969982763055
Average confidence score for samples classified same by surrogate model: 0.9975300038170545
[SHAP base] Sample set 1, n_queries=585, Top similarity=0.5216
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9893462666165365
Average confidence score for samples classified same by surrogate model: 0.9981230499168449
[SHAP3]     Sample set 2, n_queries=575, Top similarity=0.7725
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9843024780918772
Average confidence score for samples classified same by surrogate model: 0.9999252365579334
[SHAP base] Sample set 2, n_queries=585, Top similarity=0.7569
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9937465079199717
Average confidence score for samples classified same by surrogate model: 0.9998774652713329
[SHAP3]     Sample set 3, n_queries=575, Top similarity=0.3882
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9939025340429011
Average confidence score for samples classified same by surrogate model: 0.9998728300054041
[SHAP base] Sample set 3, n_queries=585, Top similarity=0.3725
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9947207801994266
Average confidence score for samples classified same by surrogate model: 0.9975000464515488
[SHAP3]     Sample set 4, n_queries=575, Top similarity=0.5059
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9944525075826166
Average confidence score for samples classified same by surrogate model: 0.9976385886558277
[SHAP base] Sample set 4, n_queries=585, Top similarity=0.5255
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9899318399051691
Average confidence score for samples classified same by surrogate model: 0.9982460773870608
[SHAP3]     Sample set 5, n_queries=575, Top similarity=0.7451
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9907826703357056
Average confidence score for samples classified same by surrogate model: 0.9981888842583829
[SHAP base] Sample set 5, n_queries=585, Top similarity=0.7216
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9812850543181596
Average confidence score for samples classified same by surrogate model: 0.9999285786839077
[SHAP3]     Sample set 6, n_queries=575, Top similarity=0.7961
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9807517786620018
Average confidence score for samples classified same by surrogate model: 0.9999705077726249
[SHAP base] Sample set 6, n_queries=585, Top similarity=0.8
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9941333377712395
Average confidence score for samples classified same by surrogate model: 0.9966251179953154
[SHAP3]     Sample set 7, n_queries=575, Top similarity=0.8
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9939706169610932
Average confidence score for samples classified same by surrogate model: 0.9966526509723067
[SHAP base] Sample set 7, n_queries=585, Top similarity=0.8039
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9890911734411303
Average confidence score for samples classified same by surrogate model: 0.9982915584149218
[SHAP3]     Sample set 8, n_queries=575, Top similarity=0.7647
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9900244048997632
Average confidence score for samples classified same by surrogate model: 0.9982144104152262
[SHAP base] Sample set 8, n_queries=585, Top similarity=0.7451
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9910094553086164
Average confidence score for samples classified same by surrogate model: 0.9982189204670714
[SHAP3]     Sample set 9, n_queries=575, Top similarity=0.7098
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9893322246398748
Average confidence score for samples classified same by surrogate model: 0.9982631886306451
[SHAP base] Sample set 9, n_queries=585, Top similarity=0.7608
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9856298727227899
Average confidence score for samples classified same by surrogate model: 0.9982558479731017
[SHAP3]     Sample set 10, n_queries=575, Top similarity=0.8314
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9783723109371943
Average confidence score for samples classified same by surrogate model: 0.9999312871676372
[SHAP base] Sample set 10, n_queries=585, Top similarity=0.8235
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9937183560596577
Average confidence score for samples classified same by surrogate model: 0.99668523288171
[SHAP3]     Sample set 11, n_queries=575, Top similarity=0.8118
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.987607559915421
Average confidence score for samples classified same by surrogate model: 0.998361998128021
[SHAP base] Sample set 11, n_queries=585, Top similarity=0.7922
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9950427172539653
Average confidence score for samples classified same by surrogate model: 0.9998923908963585
[SHAP3]     Sample set 12, n_queries=575, Top similarity=0.2235
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.994914548211376
Average confidence score for samples classified same by surrogate model: 0.999900266009387
[SHAP base] Sample set 12, n_queries=585, Top similarity=0.2431
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.993723776932297
Average confidence score for samples classified same by surrogate model: 0.9978362680708325
[SHAP3]     Sample set 13, n_queries=575, Top similarity=0.5843
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9938391144060117
Average confidence score for samples classified same by surrogate model: 0.9977806692968533
[SHAP base] Sample set 13, n_queries=585, Top similarity=0.5804
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9876057201926882
Average confidence score for samples classified same by surrogate model: 0.99836248082755
[SHAP3]     Sample set 14, n_queries=575, Top similarity=0.7922
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9948612974073067
Average confidence score for samples classified same by surrogate model: 0.9999033826965935
[SHAP base] Sample set 14, n_queries=585, Top similarity=0.251
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9948755610786841
Average confidence score for samples classified same by surrogate model: 0.9965117468341359
[SHAP3]     Sample set 15, n_queries=575, Top similarity=0.7647
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9868640205211575
Average confidence score for samples classified same by surrogate model: 0.9983859671771692
[SHAP base] Sample set 15, n_queries=585, Top similarity=0.8039
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9943189048503192
Average confidence score for samples classified same by surrogate model: 0.9965898583505465
[SHAP3]     Sample set 16, n_queries=575, Top similarity=0.7961
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9948491654274625
Average confidence score for samples classified same by surrogate model: 0.9965113445773328
[SHAP base] Sample set 16, n_queries=585, Top similarity=0.7686
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9899197195840411
Average confidence score for samples classified same by surrogate model: 0.9982943005546606
[SHAP3]     Sample set 17, n_queries=575, Top similarity=0.7412
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9900694227215815
Average confidence score for samples classified same by surrogate model: 0.9982854945480404
[SHAP base] Sample set 17, n_queries=585, Top similarity=0.7373
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9896047103331838
Average confidence score for samples classified same by surrogate model: 0.9983121614453079
[SHAP3]     Sample set 18, n_queries=575, Top similarity=0.749
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9873237534662495
Average confidence score for samples classified same by surrogate model: 0.9983817197888306
[SHAP base] Sample set 18, n_queries=585, Top similarity=0.7961
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9842266947619429
Average confidence score for samples classified same by surrogate model: 0.9987459154943932
[SHAP3]     Sample set 19, n_queries=575, Top similarity=0.8196
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9805808412295164
Average confidence score for samples classified same by surrogate model: 0.9999184499312279
[SHAP base] Sample set 19, n_queries=585, Top similarity=0.8039

=== Query limit 500 | k=3 | n=5 ===
  [SHAP3 main]    Avg similarity: 0.6947  | All: [0.7765, 0.5216, 0.7725, 0.3882, 0.5059, 0.7451, 0.7961, 0.8, 0.7647, 0.7098, 0.8314, 0.8118, 0.2235, 0.5843, 0.7922, 0.7647, 0.7961, 0.7412, 0.749, 0.8196]
  [SHAP baseline] Avg similarity: 0.6682  | All: [0.7569, 0.5216, 0.7569, 0.3725, 0.5255, 0.7216, 0.8, 0.8039, 0.7451, 0.7608, 0.8235, 0.7922, 0.2431, 0.5804, 0.251, 0.8039, 0.7686, 0.7373, 0.7961, 0.8039]
  Difference (main - baseline): +0.0265


========== FINAL COMPARISON SUMMARY ==========
  [SHAP3 main]    Overall avg similarity: 0.6947
  [SHAP baseline] Overall avg similarity: 0.6682
  Overall difference (main - baseline): +0.0265
===============================================

Avg Similarity: 0.6947 | Baseline: 0.6682
Dataset: 1, Model: 3... DATASET 1 3
Train results
[[74  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0]
 [ 0 74  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0 67  0  0  7  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 66  1  0  0  5  0  0  0  0  0  0  0  0  3]
 [ 0  1  0  4 66  0  0  1  0  0  1  0  0  0  0  0  2]
 [ 0  0  1  0  0 70  0  0  0  0  0  0  0  0  0  4  0]
 [ 0  0  0  0  0  0 73  0  0  1  0  0  0  1  0  0  0]
 [ 0  1  1  4  2  0  0 66  0  1  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0 74  0  0  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0  2  2 65  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  0 72  0  0  0  0  0  2]
 [ 4  0  0  0  0  0  0  0  0  0  0 59  3  0  9  0  0]
 [ 0  0  0  0  0  2  0  0  0  0  2  1 66  0  1  0  3]
 [ 0  0 17  0  0  1 10  3 10  0  0  0  0 33  0  1  0]
 [14  0  0  0  0  0  0  0  0  0  0  6  0  0 55  0  0]
 [ 0  0  0  0  0 18  0  0  0  0  0  0  0  0  0 57  0]
 [ 0  0  0  0  0  0  0  0  0  0  2  0  0  0  0  0 73]]
              precision    recall  f1-score   support

           0       0.80      0.99      0.89        75
           1       0.88      0.99      0.93        75
           2       0.78      0.89      0.83        75
           3       0.89      0.88      0.89        75
           4       0.96      0.88      0.92        75
           5       0.71      0.93      0.81        75
           6       0.87      0.97      0.92        75
           7       0.85      0.88      0.86        75
           8       0.86      0.99      0.92        75
           9       0.97      0.87      0.92        75
          10       0.94      0.96      0.95        75
          11       0.89      0.79      0.84        75
          12       0.96      0.88      0.92        75
          13       0.97      0.44      0.61        75
          14       0.83      0.73      0.78        75
          15       0.92      0.76      0.83        75
          16       0.88      0.97      0.92        75

    accuracy                           0.87      1275
   macro avg       0.88      0.87      0.87      1275
weighted avg       0.88      0.87      0.87      1275

Test results
[[15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0 11  0  0  0  1  0  0  0  0  0  0  0  0  2]
 [ 0  0  0  2 12  0  0  0  0  0  0  0  0  0  0  0  1]
 [ 0  0  0  0  0 13  0  0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0 13  0  0  2  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 14  0  0  0  0  0  0  0  0  1]
 [ 0  0  0  0  0  0  0  0 15  0  0  0  0  0  0  0  0]
 [ 0  3  0  0  0  0  0  0  1 11  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 15  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 13  1  0  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  3  1  8  0  2  0  1]
 [ 0  0  3  0  0  0  2  0  3  0  0  0  0  7  0  0  0]
 [ 5  0  0  0  0  0  0  0  0  0  0  0  0  0 10  0  0]
 [ 0  0  0  0  0  3  0  0  0  0  0  0  0  0  0 12  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0 14]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86        15
           1       0.79      1.00      0.88        15
           2       0.83      1.00      0.91        15
           3       0.85      0.73      0.79        15
           4       1.00      0.80      0.89        15
           5       0.81      0.87      0.84        15
           6       0.87      0.87      0.87        15
           7       0.93      0.93      0.93        15
           8       0.79      1.00      0.88        15
           9       0.85      0.73      0.79        15
          10       0.79      1.00      0.88        15
          11       0.93      0.87      0.90        15
          12       0.89      0.53      0.67        15
          13       1.00      0.47      0.64        15
          14       0.77      0.67      0.71        15
          15       0.86      0.80      0.83        15
          16       0.74      0.93      0.82        15

    accuracy                           0.84       255
   macro avg       0.85      0.84      0.83       255
weighted avg       0.85      0.84      0.83       255

Model test accuracy:  0.8353

Dataset:   Crop
ML Model:  K Nearest Neighbor
SHAP is the explanation tool currently in use

Lower bounds:  [15]  Upper bounds:  [508] (per class for both)

-----The attack starts here!-----

Number of top features allowed to be explored (k): 3

Number of samples per class (n): 5
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.705118411000764
Average confidence score for samples classified same by surrogate model: 0.8109715796430925
[SHAP3]     Sample set 0, n_queries=575, Top similarity=0.698
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6980968858131489
Average confidence score for samples classified same by surrogate model: 0.8084303240012573
[SHAP base] Sample set 0, n_queries=585, Top similarity=0.7333
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 8
Diverse samples left to process: 3

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6805555555555557
Average confidence score for samples classified same by surrogate model: 0.8177434908389578
[SHAP3]     Sample set 1, n_queries=575, Top similarity=0.7176
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7079584775086506
Average confidence score for samples classified same by surrogate model: 0.8145328719723178
[SHAP base] Sample set 1, n_queries=585, Top similarity=0.6667
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 6
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7044649184975197
Average confidence score for samples classified same by surrogate model: 0.8149794801641581
[SHAP3]     Sample set 2, n_queries=575, Top similarity=0.6745
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7211072664359862
Average confidence score for samples classified same by surrogate model: 0.80795847750865
[SHAP base] Sample set 2, n_queries=585, Top similarity=0.6667
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 6
Diverse samples left to process: 3

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6947133283693225
Average confidence score for samples classified same by surrogate model: 0.8168449197860955
[SHAP3]     Sample set 3, n_queries=575, Top similarity=0.6902
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.702338766832034
Average confidence score for samples classified same by surrogate model: 0.8160054719562236
[SHAP base] Sample set 3, n_queries=585, Top similarity=0.6745
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7037562012756909
Average confidence score for samples classified same by surrogate model: 0.8153214774281798
[SHAP3]     Sample set 4, n_queries=575, Top similarity=0.6745
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6768086544962812
Average confidence score for samples classified same by surrogate model: 0.831932773109243
[SHAP base] Sample set 4, n_queries=585, Top similarity=0.6588
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 7

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7195809830781627
Average confidence score for samples classified same by surrogate model: 0.8028442146089197
[SHAP3]     Sample set 5, n_queries=575, Top similarity=0.7137
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7038062283737025
Average confidence score for samples classified same by surrogate model: 0.8166089965397917
[SHAP base] Sample set 5, n_queries=585, Top similarity=0.6667
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 8
Diverse samples left to process: 1

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7033792240300375
Average confidence score for samples classified same by surrogate model: 0.8231640482279862
[SHAP3]     Sample set 6, n_queries=575, Top similarity=0.6314
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6899509803921567
Average confidence score for samples classified same by surrogate model: 0.832778394376618
[SHAP base] Sample set 6, n_queries=585, Top similarity=0.6235
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 7
Diverse samples left to process: 4

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6685121107266436
Average confidence score for samples classified same by surrogate model: 0.834256055363321
[SHAP3]     Sample set 7, n_queries=575, Top similarity=0.6667
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6895818568391212
Average confidence score for samples classified same by surrogate model: 0.8221614227086175
[SHAP base] Sample set 7, n_queries=585, Top similarity=0.6745
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 1

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7037302725968436
Average confidence score for samples classified same by surrogate model: 0.8146888813328791
[SHAP3]     Sample set 8, n_queries=575, Top similarity=0.6784
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6941176470588236
Average confidence score for samples classified same by surrogate model: 0.8214532871972311
[SHAP base] Sample set 8, n_queries=585, Top similarity=0.6667
Dataset name in traverse_explanations_SHAP3: crop

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7012557832121614
Average confidence score for samples classified same by surrogate model: 0.8206945428773912
[SHAP3]     Sample set 9, n_queries=575, Top similarity=0.651
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6855742296918769
Average confidence score for samples classified same by surrogate model: 0.8249054007567933
[SHAP base] Sample set 9, n_queries=585, Top similarity=0.6706
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 7
Diverse samples left to process: 5

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6753536857781088
Average confidence score for samples classified same by surrogate model: 0.825534759358288
[SHAP3]     Sample set 10, n_queries=575, Top similarity=0.6902
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6875477463712758
Average confidence score for samples classified same by surrogate model: 0.8185723727693317
[SHAP base] Sample set 10, n_queries=585, Top similarity=0.698
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 3
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7098569157392688
Average confidence score for samples classified same by surrogate model: 0.8072798180045492
[SHAP3]     Sample set 11, n_queries=575, Top similarity=0.7098
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7163865546218486
Average confidence score for samples classified same by surrogate model: 0.8097695218438246
[SHAP base] Sample set 11, n_queries=585, Top similarity=0.6706
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 5

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7300653594771241
Average confidence score for samples classified same by surrogate model: 0.8057040998217462
[SHAP3]     Sample set 12, n_queries=575, Top similarity=0.6471
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7432005060088551
Average confidence score for samples classified same by surrogate model: 0.799564270152505
[SHAP base] Sample set 12, n_queries=585, Top similarity=0.6353
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 5
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.675
Average confidence score for samples classified same by surrogate model: 0.8265546218487388
[SHAP3]     Sample set 13, n_queries=575, Top similarity=0.6863
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6669029057406096
Average confidence score for samples classified same by surrogate model: 0.833105335157318
[SHAP base] Sample set 13, n_queries=585, Top similarity=0.6745
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 5
Diverse samples left to process: 2

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6844290657439448
Average confidence score for samples classified same by surrogate model: 0.8262975778546704
[SHAP3]     Sample set 14, n_queries=575, Top similarity=0.6667
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6898395721925135
Average confidence score for samples classified same by surrogate model: 0.8259950686861564
[SHAP base] Sample set 14, n_queries=585, Top similarity=0.6549
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 7

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.738970588235294
Average confidence score for samples classified same by surrogate model: 0.797310924369747
[SHAP3]     Sample set 15, n_queries=575, Top similarity=0.6863
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7303370786516854
Average confidence score for samples classified same by surrogate model: 0.8051027639971645
[SHAP base] Sample set 15, n_queries=585, Top similarity=0.651
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 4
Diverse samples left to process: 1

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6942833471416738
Average confidence score for samples classified same by surrogate model: 0.8117007672634261
[SHAP3]     Sample set 16, n_queries=575, Top similarity=0.7216
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6990068754774639
Average confidence score for samples classified same by surrogate model: 0.8136153337739583
[SHAP base] Sample set 16, n_queries=585, Top similarity=0.698
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 1

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6830065359477127
Average confidence score for samples classified same by surrogate model: 0.8167791706846663
[SHAP3]     Sample set 17, n_queries=575, Top similarity=0.7176
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6976744186046512
Average confidence score for samples classified same by surrogate model: 0.8203967977723626
[SHAP base] Sample set 17, n_queries=585, Top similarity=0.6627
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 7
Diverse samples left to process: 2

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6621621621621622
Average confidence score for samples classified same by surrogate model: 0.8267793305167361
[SHAP3]     Sample set 18, n_queries=575, Top similarity=0.7098
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6776470588235295
Average confidence score for samples classified same by surrogate model: 0.8212418300653587
[SHAP base] Sample set 18, n_queries=585, Top similarity=0.7059
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 4

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7028657616892912
Average confidence score for samples classified same by surrogate model: 0.8125623130608168
[SHAP3]     Sample set 19, n_queries=575, Top similarity=0.6941
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7044649184975197
Average confidence score for samples classified same by surrogate model: 0.8149794801641578
[SHAP base] Sample set 19, n_queries=585, Top similarity=0.6745

=== Query limit 500 | k=3 | n=5 ===
  [SHAP3 main]    Avg similarity: 0.6863  | All: [0.698, 0.7176, 0.6745, 0.6902, 0.6745, 0.7137, 0.6314, 0.6667, 0.6784, 0.651, 0.6902, 0.7098, 0.6471, 0.6863, 0.6667, 0.6863, 0.7216, 0.7176, 0.7098, 0.6941]
  [SHAP baseline] Avg similarity: 0.6714  | All: [0.7333, 0.6667, 0.6667, 0.6745, 0.6588, 0.6667, 0.6235, 0.6745, 0.6667, 0.6706, 0.698, 0.6706, 0.6353, 0.6745, 0.6549, 0.651, 0.698, 0.6627, 0.7059, 0.6745]
  Difference (main - baseline): +0.0149


========== FINAL COMPARISON SUMMARY ==========
  [SHAP3 main]    Overall avg similarity: 0.6863
  [SHAP baseline] Overall avg similarity: 0.6714
  Overall difference (main - baseline): +0.0149
===============================================

Avg Similarity: 0.6863 | Baseline: 0.6714
Dataset: 1, Model: 4... DATASET 1 4
Train results
[[75  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 75  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 75  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 75  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 75  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 75  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 75  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 75  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 75  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 75  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 75  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 75  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 75  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 75  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 75  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 75  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 75]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        75
           1       1.00      1.00      1.00        75
           2       1.00      1.00      1.00        75
           3       1.00      1.00      1.00        75
           4       1.00      1.00      1.00        75
           5       1.00      1.00      1.00        75
           6       1.00      1.00      1.00        75
           7       1.00      1.00      1.00        75
           8       1.00      1.00      1.00        75
           9       1.00      1.00      1.00        75
          10       1.00      1.00      1.00        75
          11       1.00      1.00      1.00        75
          12       1.00      1.00      1.00        75
          13       1.00      1.00      1.00        75
          14       1.00      1.00      1.00        75
          15       1.00      1.00      1.00        75
          16       1.00      1.00      1.00        75

    accuracy                           1.00      1275
   macro avg       1.00      1.00      1.00      1275
weighted avg       1.00      1.00      1.00      1275

Test results
[[15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 15  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 15  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 15  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 15  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 15  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 15  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 15  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 15  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 15  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 15  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 15  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 15  0  0]
 [ 0  0  0  0  0  1  0  0  0  0  0  0  0  0  0 14  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 15]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00        15
           2       1.00      1.00      1.00        15
           3       1.00      1.00      1.00        15
           4       1.00      1.00      1.00        15
           5       0.94      1.00      0.97        15
           6       1.00      1.00      1.00        15
           7       1.00      1.00      1.00        15
           8       1.00      1.00      1.00        15
           9       1.00      1.00      1.00        15
          10       1.00      1.00      1.00        15
          11       1.00      1.00      1.00        15
          12       1.00      1.00      1.00        15
          13       1.00      1.00      1.00        15
          14       1.00      1.00      1.00        15
          15       1.00      0.93      0.97        15
          16       1.00      1.00      1.00        15

    accuracy                           1.00       255
   macro avg       1.00      1.00      1.00       255
weighted avg       1.00      1.00      1.00       255

Model test accuracy:  0.9961

Dataset:   Crop
ML Model:  Random Forest
SHAP is the explanation tool currently in use

Lower bounds:  [15]  Upper bounds:  [508] (per class for both)

-----The attack starts here!-----

Number of top features allowed to be explored (k): 3

Number of samples per class (n): 5
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 6
Error: unhashable type: 'numpy.ndarray'
Dataset: 1, Model: 5... DATASET 1 5
Train results
[[75  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 75  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 75  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 73  0  0  0  2  0  0  0  0  0  0  0  0  0]
 [ 2  0  0  0 72  0  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 62  0  0  0  0  0  0  2  1  0 10  0]
 [ 0  0  0  0  0  0 70  1  0  0  0  0  0  4  0  0  0]
 [ 0  3  1 12  1  5  0 48  0  0  0  0  0  5  0  0  0]
 [ 0  0  0  0  0  0  0  0 75  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  3  0  0  0  0 70  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 75  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 74  0  0  1  0  0]
 [ 1  0  0  0  0  3  0  0  0  0  5  0 63  0  3  0  0]
 [ 0  0  0  0  0  0  0  0  1  0  0  0  0 73  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 75  0  0]
 [ 0  0  0  0  0 13  0  0  0  0  0  0  0  1  0 61  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 75]]
              precision    recall  f1-score   support

           0       0.96      1.00      0.98        75
           1       0.95      1.00      0.97        75
           2       0.99      1.00      0.99        75
           3       0.86      0.97      0.91        75
           4       0.95      0.96      0.95        75
           5       0.75      0.83      0.78        75
           6       1.00      0.93      0.97        75
           7       0.94      0.64      0.76        75
           8       0.99      1.00      0.99        75
           9       0.99      0.93      0.96        75
          10       0.94      1.00      0.97        75
          11       1.00      0.99      0.99        75
          12       0.97      0.84      0.90        75
          13       0.86      0.97      0.91        75
          14       0.95      1.00      0.97        75
          15       0.85      0.81      0.83        75
          16       1.00      1.00      1.00        75

    accuracy                           0.93      1275
   macro avg       0.94      0.93      0.93      1275
weighted avg       0.94      0.93      0.93      1275

Test results
[[15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 13  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0]
 [ 0  0 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 13  0  0  0  1  0  0  0  0  0  0  0  0  1]
 [ 1  0  0  0 14  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  0  0  7  0  0  0  0  0  0  1  0  0  5  0]
 [ 0  0  0  0  0  0 13  0  0  1  0  0  0  1  0  0  0]
 [ 0  0  2  3  0  0  0 10  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0 14  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 14  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 15  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 15  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0  0  0  0 12  0  1  0  1]
 [ 0  0  1  0  0  0  0  0  2  0  0  0  0 12  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 15  0  0]
 [ 0  0  0  0  0  3  0  0  0  0  0  0  0  0  0 12  0]
 [ 0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0 14]]
              precision    recall  f1-score   support

           0       0.94      1.00      0.97        15
           1       1.00      0.87      0.93        15
           2       0.75      1.00      0.86        15
           3       0.76      0.87      0.81        15
           4       0.93      0.93      0.93        15
           5       0.70      0.47      0.56        15
           6       0.93      0.87      0.90        15
           7       0.91      0.67      0.77        15
           8       0.88      0.93      0.90        15
           9       0.82      0.93      0.87        15
          10       1.00      1.00      1.00        15
          11       1.00      1.00      1.00        15
          12       0.92      0.80      0.86        15
          13       0.86      0.80      0.83        15
          14       0.94      1.00      0.97        15
          15       0.71      0.80      0.75        15
          16       0.88      0.93      0.90        15

    accuracy                           0.87       255
   macro avg       0.88      0.87      0.87       255
weighted avg       0.88      0.87      0.87       255

Model test accuracy:  0.8745

Dataset:   Crop
ML Model:  Multilayer Perceptron
SHAP is the explanation tool currently in use

Lower bounds:  [15]  Upper bounds:  [508] (per class for both)

-----The attack starts here!-----

Number of top features allowed to be explored (k): 3

Number of samples per class (n): 5
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9614895122046395
Average confidence score for samples classified same by surrogate model: 0.9703293766626127
Average confidence score for samples classified differently by surrogate model: 0.9665857979634817
Average confidence score for samples classified same by surrogate model: 0.9223793377364924
Average confidence score for samples classified differently by surrogate model: 0.951867030559053
Average confidence score for samples classified same by surrogate model: 0.9821394277512268
Average confidence score for samples classified differently by surrogate model: 0.9501885441761025
Average confidence score for samples classified same by surrogate model: 0.9773059557011451
Average confidence score for samples classified differently by surrogate model: 0.9507381569382797
Average confidence score for samples classified same by surrogate model: 0.9769992514721846
Average confidence score for samples classified differently by surrogate model: 0.9484550928137344
Average confidence score for samples classified same by surrogate model: 0.9767673014167728
Average confidence score for samples classified differently by surrogate model: 0.9433996443613468
Average confidence score for samples classified same by surrogate model: 0.9782871292345062
Average confidence score for samples classified differently by surrogate model: 0.9430594811836129
Average confidence score for samples classified same by surrogate model: 0.9797116892641231
Average confidence score for samples classified differently by surrogate model: 0.9375920522884996
Average confidence score for samples classified same by surrogate model: 0.9804770910568605
Average confidence score for samples classified differently by surrogate model: 0.9435607098329767
Average confidence score for samples classified same by surrogate model: 0.9768733732941574
Average confidence score for samples classified differently by surrogate model: 0.9410862645293169
Average confidence score for samples classified same by surrogate model: 0.980342536335681
Average confidence score for samples classified differently by surrogate model: 0.940091516093257
Average confidence score for samples classified same by surrogate model: 0.9818574478091775
Average confidence score for samples classified differently by surrogate model: 0.9358623487955497
Average confidence score for samples classified same by surrogate model: 0.9812360710134975
Average confidence score for samples classified differently by surrogate model: 0.9399396546958906
Average confidence score for samples classified same by surrogate model: 0.9808612504214475
Average confidence score for samples classified differently by surrogate model: 0.9322531191409047
Average confidence score for samples classified same by surrogate model: 0.983061498748396
Average confidence score for samples classified differently by surrogate model: 0.9333397126604732
Average confidence score for samples classified same by surrogate model: 0.981237093080571
Average confidence score for samples classified differently by surrogate model: 0.945133803380774
Average confidence score for samples classified same by surrogate model: 0.9767181558687703
Average confidence score for samples classified differently by surrogate model: 0.9337415140981208
Average confidence score for samples classified same by surrogate model: 0.9837454141155312
Average confidence score for samples classified differently by surrogate model: 0.9477610023199022
Average confidence score for samples classified same by surrogate model: 0.974171245483413
Average confidence score for samples classified differently by surrogate model: 0.9412811366256416
Average confidence score for samples classified same by surrogate model: 0.9792037473236946
[SHAP3]     Sample set 0, n_queries=575, Top similarity=0.6471
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9562367842596602
Average confidence score for samples classified same by surrogate model: 0.9796949037087912
Average confidence score for samples classified differently by surrogate model: 0.949391999635687
Average confidence score for samples classified same by surrogate model: 0.9789248259196915
Average confidence score for samples classified differently by surrogate model: 0.9520149692892015
Average confidence score for samples classified same by surrogate model: 0.9805683995527503
Average confidence score for samples classified differently by surrogate model: 0.943551914605942
Average confidence score for samples classified same by surrogate model: 0.9819501484698665
Average confidence score for samples classified differently by surrogate model: 0.9517190806464537
Average confidence score for samples classified same by surrogate model: 0.9760852089259313
Average confidence score for samples classified differently by surrogate model: 0.9398914164347993
Average confidence score for samples classified same by surrogate model: 0.9878328264875911
Average confidence score for samples classified differently by surrogate model: 0.9374606615651889
Average confidence score for samples classified same by surrogate model: 0.9816685699433412
Average confidence score for samples classified differently by surrogate model: 0.939739290038936
Average confidence score for samples classified same by surrogate model: 0.9858508748757601
Average confidence score for samples classified differently by surrogate model: 0.9408565077318798
Average confidence score for samples classified same by surrogate model: 0.9824279315242929
Average confidence score for samples classified differently by surrogate model: 0.9430024578739188
Average confidence score for samples classified same by surrogate model: 0.9805132698731432
Average confidence score for samples classified differently by surrogate model: 0.9413705828480781
Average confidence score for samples classified same by surrogate model: 0.9804052219912572
Average confidence score for samples classified differently by surrogate model: 0.9391182023823172
Average confidence score for samples classified same by surrogate model: 0.9850435801697875
Average confidence score for samples classified differently by surrogate model: 0.9376086337777204
Average confidence score for samples classified same by surrogate model: 0.9796734046691902
Average confidence score for samples classified differently by surrogate model: 0.9421628211598936
Average confidence score for samples classified same by surrogate model: 0.9770589637646091
Average confidence score for samples classified differently by surrogate model: 0.9441152482116849
Average confidence score for samples classified same by surrogate model: 0.975742893633508
Average confidence score for samples classified differently by surrogate model: 0.9454798055542394
Average confidence score for samples classified same by surrogate model: 0.9790975963333004
Average confidence score for samples classified differently by surrogate model: 0.9487444950262938
Average confidence score for samples classified same by surrogate model: 0.9731300672105393
Average confidence score for samples classified differently by surrogate model: 0.9479831505061707
Average confidence score for samples classified same by surrogate model: 0.9781932310761942
Average confidence score for samples classified differently by surrogate model: 0.9370017427353659
Average confidence score for samples classified same by surrogate model: 0.9784853742842863
Average confidence score for samples classified differently by surrogate model: 0.9339115326855508
Average confidence score for samples classified same by surrogate model: 0.9836375177042778
[SHAP base] Sample set 0, n_queries=585, Top similarity=0.6588
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 3
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.961827798379862
Average confidence score for samples classified same by surrogate model: 0.9777929461516643
Average confidence score for samples classified differently by surrogate model: 0.9606284891947239
Average confidence score for samples classified same by surrogate model: 0.9684987371370755
Average confidence score for samples classified differently by surrogate model: 0.9594653083965629
Average confidence score for samples classified same by surrogate model: 0.9701639364708148
Average confidence score for samples classified differently by surrogate model: 0.9653317359238285
Average confidence score for samples classified same by surrogate model: 0.9440902223538878
Average confidence score for samples classified differently by surrogate model: 0.9484188780380923
Average confidence score for samples classified same by surrogate model: 0.977403739452544
Average confidence score for samples classified differently by surrogate model: 0.954071707592878
Average confidence score for samples classified same by surrogate model: 0.9724971235193066
Average confidence score for samples classified differently by surrogate model: 0.9476141987610418
Average confidence score for samples classified same by surrogate model: 0.9780647260015495
Average confidence score for samples classified differently by surrogate model: 0.9427554232859863
Average confidence score for samples classified same by surrogate model: 0.9780250486693856
Average confidence score for samples classified differently by surrogate model: 0.9450437467058485
Average confidence score for samples classified same by surrogate model: 0.9801761687611726
Average confidence score for samples classified differently by surrogate model: 0.944360833482833
Average confidence score for samples classified same by surrogate model: 0.9802247909449057
Average confidence score for samples classified differently by surrogate model: 0.9517180149513068
Average confidence score for samples classified same by surrogate model: 0.974211726036297
Average confidence score for samples classified differently by surrogate model: 0.9451138330027514
Average confidence score for samples classified same by surrogate model: 0.9769363465224602
Average confidence score for samples classified differently by surrogate model: 0.9495228567675154
Average confidence score for samples classified same by surrogate model: 0.9748675951703366
Average confidence score for samples classified differently by surrogate model: 0.9548077562677615
Average confidence score for samples classified same by surrogate model: 0.9708919724893351
Average confidence score for samples classified differently by surrogate model: 0.9481648069761515
Average confidence score for samples classified same by surrogate model: 0.9747626696782044
Average confidence score for samples classified differently by surrogate model: 0.9468067948125247
Average confidence score for samples classified same by surrogate model: 0.9770024827891665
Average confidence score for samples classified differently by surrogate model: 0.947811032058069
Average confidence score for samples classified same by surrogate model: 0.9753462041033579
Average confidence score for samples classified differently by surrogate model: 0.9437104967547486
Average confidence score for samples classified same by surrogate model: 0.9769922551425709
Average confidence score for samples classified differently by surrogate model: 0.9525792738891365
Average confidence score for samples classified same by surrogate model: 0.971079148308933
Average confidence score for samples classified differently by surrogate model: 0.9509144147733296
Average confidence score for samples classified same by surrogate model: 0.9720349007643037
[SHAP3]     Sample set 1, n_queries=575, Top similarity=0.6353
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9632156156006316
Average confidence score for samples classified same by surrogate model: 0.9669618329634718
Average confidence score for samples classified differently by surrogate model: 0.9626930046739912
Average confidence score for samples classified same by surrogate model: 0.9925485979503649
Average confidence score for samples classified differently by surrogate model: 0.9644982178866367
Average confidence score for samples classified same by surrogate model: 0.9641331225128814
Average confidence score for samples classified differently by surrogate model: 0.9559616794220702
Average confidence score for samples classified same by surrogate model: 0.9725079293841545
Average confidence score for samples classified differently by surrogate model: 0.9585643155864959
Average confidence score for samples classified same by surrogate model: 0.9697917508779487
Average confidence score for samples classified differently by surrogate model: 0.9590982621947567
Average confidence score for samples classified same by surrogate model: 0.9696072199748655
Average confidence score for samples classified differently by surrogate model: 0.9556975274462799
Average confidence score for samples classified same by surrogate model: 0.9710949050612127
Average confidence score for samples classified differently by surrogate model: 0.9529966806521368
Average confidence score for samples classified same by surrogate model: 0.9759374816953262
Average confidence score for samples classified differently by surrogate model: 0.9552181845944474
Average confidence score for samples classified same by surrogate model: 0.9718185947812525
Average confidence score for samples classified differently by surrogate model: 0.9444115020181937
Average confidence score for samples classified same by surrogate model: 0.9782765785721762
Average confidence score for samples classified differently by surrogate model: 0.9501675257363408
Average confidence score for samples classified same by surrogate model: 0.9759673502718398
Average confidence score for samples classified differently by surrogate model: 0.9488938278277056
Average confidence score for samples classified same by surrogate model: 0.9746243402569335
Average confidence score for samples classified differently by surrogate model: 0.9551950899163472
Average confidence score for samples classified same by surrogate model: 0.9708323152121071
Average confidence score for samples classified differently by surrogate model: 0.9476858139683073
Average confidence score for samples classified same by surrogate model: 0.9756122082829018
Average confidence score for samples classified differently by surrogate model: 0.9494967576575502
Average confidence score for samples classified same by surrogate model: 0.973746894164355
Average confidence score for samples classified differently by surrogate model: 0.9599997999883185
Average confidence score for samples classified same by surrogate model: 0.9676716437432881
Average confidence score for samples classified differently by surrogate model: 0.9518267101664598
Average confidence score for samples classified same by surrogate model: 0.9726690853644305
Average confidence score for samples classified differently by surrogate model: 0.9469314165596241
Average confidence score for samples classified same by surrogate model: 0.9769123846341691
Average confidence score for samples classified differently by surrogate model: 0.9569570301247267
Average confidence score for samples classified same by surrogate model: 0.9689357041115517
Average confidence score for samples classified differently by surrogate model: 0.948002643922608
Average confidence score for samples classified same by surrogate model: 0.9765233308915927
[SHAP base] Sample set 1, n_queries=585, Top similarity=0.6157
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9543363017143994
Average confidence score for samples classified same by surrogate model: 0.9892532545988517
Average confidence score for samples classified differently by surrogate model: 0.9487170272368058
Average confidence score for samples classified same by surrogate model: 0.9761780793219876
Average confidence score for samples classified differently by surrogate model: 0.9600027339873727
Average confidence score for samples classified same by surrogate model: 0.9701311498677098
Average confidence score for samples classified differently by surrogate model: 0.9488543873947578
Average confidence score for samples classified same by surrogate model: 0.974154552215742
Average confidence score for samples classified differently by surrogate model: 0.9606209879950317
Average confidence score for samples classified same by surrogate model: 0.9676832458980444
Average confidence score for samples classified differently by surrogate model: 0.9452535293718812
Average confidence score for samples classified same by surrogate model: 0.9774723671725905
Average confidence score for samples classified differently by surrogate model: 0.9609836197177901
Average confidence score for samples classified same by surrogate model: 0.9673557948648072
Average confidence score for samples classified differently by surrogate model: 0.950739032637285
Average confidence score for samples classified same by surrogate model: 0.9744804105498136
Average confidence score for samples classified differently by surrogate model: 0.9484645267154328
Average confidence score for samples classified same by surrogate model: 0.9784366762361841
Average confidence score for samples classified differently by surrogate model: 0.9534128040059262
Average confidence score for samples classified same by surrogate model: 0.9711480235997199
Average confidence score for samples classified differently by surrogate model: 0.9536583116880363
Average confidence score for samples classified same by surrogate model: 0.9711059079527001
Average confidence score for samples classified differently by surrogate model: 0.9476948834669234
Average confidence score for samples classified same by surrogate model: 0.9765554223354359
Average confidence score for samples classified differently by surrogate model: 0.9495651439584146
Average confidence score for samples classified same by surrogate model: 0.9757150244330055
Average confidence score for samples classified differently by surrogate model: 0.9536528435636697
Average confidence score for samples classified same by surrogate model: 0.9703597109808542
Average confidence score for samples classified differently by surrogate model: 0.9437461209811185
Average confidence score for samples classified same by surrogate model: 0.9820631549048523
Average confidence score for samples classified differently by surrogate model: 0.9503946716274623
Average confidence score for samples classified same by surrogate model: 0.9730319533646207
Average confidence score for samples classified differently by surrogate model: 0.9485334960801834
Average confidence score for samples classified same by surrogate model: 0.9763173098545974
Average confidence score for samples classified differently by surrogate model: 0.9486018341565206
Average confidence score for samples classified same by surrogate model: 0.9755228193097022
Average confidence score for samples classified differently by surrogate model: 0.9489499305610855
Average confidence score for samples classified same by surrogate model: 0.9752751802567903
Average confidence score for samples classified differently by surrogate model: 0.9599421053048406
Average confidence score for samples classified same by surrogate model: 0.967881521226843
[SHAP3]     Sample set 2, n_queries=575, Top similarity=0.6392
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9600480303154392
Average confidence score for samples classified same by surrogate model: 0.9715474699712275
Average confidence score for samples classified differently by surrogate model: 0.9654571518713896
Average confidence score for samples classified same by surrogate model: 0.9367692289246584
Average confidence score for samples classified differently by surrogate model: 0.9558611359215772
Average confidence score for samples classified same by surrogate model: 0.9731419746234538
Average confidence score for samples classified differently by surrogate model: 0.9503122014649549
Average confidence score for samples classified same by surrogate model: 0.9735270269465994
Average confidence score for samples classified differently by surrogate model: 0.9501172223273088
Average confidence score for samples classified same by surrogate model: 0.9773713787504145
Average confidence score for samples classified differently by surrogate model: 0.9479266060126029
Average confidence score for samples classified same by surrogate model: 0.9761928895566777
Average confidence score for samples classified differently by surrogate model: 0.9520318607059486
Average confidence score for samples classified same by surrogate model: 0.9732249013662184
Average confidence score for samples classified differently by surrogate model: 0.9430064782200608
Average confidence score for samples classified same by surrogate model: 0.9815741558911332
Average confidence score for samples classified differently by surrogate model: 0.9583898934256732
Average confidence score for samples classified same by surrogate model: 0.9687684665365647
Average confidence score for samples classified differently by surrogate model: 0.9525251152433857
Average confidence score for samples classified same by surrogate model: 0.9737278625016492
Average confidence score for samples classified differently by surrogate model: 0.9426003511220693
Average confidence score for samples classified same by surrogate model: 0.9800436278896982
Average confidence score for samples classified differently by surrogate model: 0.9435101578456393
Average confidence score for samples classified same by surrogate model: 0.9803824095616029
Average confidence score for samples classified differently by surrogate model: 0.9482063783721206
Average confidence score for samples classified same by surrogate model: 0.9782214733563982
Average confidence score for samples classified differently by surrogate model: 0.9500147152837194
Average confidence score for samples classified same by surrogate model: 0.9745176824004199
Average confidence score for samples classified differently by surrogate model: 0.9549418736900944
Average confidence score for samples classified same by surrogate model: 0.9713426730514825
Average confidence score for samples classified differently by surrogate model: 0.9475164912276509
Average confidence score for samples classified same by surrogate model: 0.9775024299317475
Average confidence score for samples classified differently by surrogate model: 0.9415191634853711
Average confidence score for samples classified same by surrogate model: 0.9800443807632995
Average confidence score for samples classified differently by surrogate model: 0.9487810189123321
Average confidence score for samples classified same by surrogate model: 0.9748700628274114
Average confidence score for samples classified differently by surrogate model: 0.9413265401672186
Average confidence score for samples classified same by surrogate model: 0.9782223059225401
Average confidence score for samples classified differently by surrogate model: 0.94175027353686
Average confidence score for samples classified same by surrogate model: 0.9796343179173699
[SHAP base] Sample set 2, n_queries=585, Top similarity=0.6235
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9679856004929692
Average confidence score for samples classified same by surrogate model: 0.9561927697591688
Average confidence score for samples classified differently by surrogate model: 0.9637058303529609
Average confidence score for samples classified same by surrogate model: 0.9782247174195099
Average confidence score for samples classified differently by surrogate model: 0.9512882853964484
Average confidence score for samples classified same by surrogate model: 0.9774786926534755
Average confidence score for samples classified differently by surrogate model: 0.945554223013336
Average confidence score for samples classified same by surrogate model: 0.9745746328881006
Average confidence score for samples classified differently by surrogate model: 0.9527536782996954
Average confidence score for samples classified same by surrogate model: 0.9758201355755897
Average confidence score for samples classified differently by surrogate model: 0.95295288636926
Average confidence score for samples classified same by surrogate model: 0.9719183012292305
Average confidence score for samples classified differently by surrogate model: 0.9494887768287407
Average confidence score for samples classified same by surrogate model: 0.979292370579984
Average confidence score for samples classified differently by surrogate model: 0.9533276020497067
Average confidence score for samples classified same by surrogate model: 0.9722881153947174
Average confidence score for samples classified differently by surrogate model: 0.9337357047293117
Average confidence score for samples classified same by surrogate model: 0.9831160198670479
Average confidence score for samples classified differently by surrogate model: 0.9496247194872609
Average confidence score for samples classified same by surrogate model: 0.9764132268335842
Average confidence score for samples classified differently by surrogate model: 0.946276718874539
Average confidence score for samples classified same by surrogate model: 0.9771769281680246
Average confidence score for samples classified differently by surrogate model: 0.9450417987682588
Average confidence score for samples classified same by surrogate model: 0.9759791309181378
Average confidence score for samples classified differently by surrogate model: 0.946704618620647
Average confidence score for samples classified same by surrogate model: 0.9747984733048458
Average confidence score for samples classified differently by surrogate model: 0.9388653796611297
Average confidence score for samples classified same by surrogate model: 0.9787060096252322
Average confidence score for samples classified differently by surrogate model: 0.9378957571336107
Average confidence score for samples classified same by surrogate model: 0.9837547804578696
Average confidence score for samples classified differently by surrogate model: 0.9559625724538626
Average confidence score for samples classified same by surrogate model: 0.9700966024008949
Average confidence score for samples classified differently by surrogate model: 0.9333598185904983
Average confidence score for samples classified same by surrogate model: 0.9772372672413858
Average confidence score for samples classified differently by surrogate model: 0.9435524941295007
Average confidence score for samples classified same by surrogate model: 0.9764643481339359
Average confidence score for samples classified differently by surrogate model: 0.9475289857839082
Average confidence score for samples classified same by surrogate model: 0.9722966338928114
Average confidence score for samples classified differently by surrogate model: 0.9539732155961556
Average confidence score for samples classified same by surrogate model: 0.9721906260838598
[SHAP3]     Sample set 3, n_queries=575, Top similarity=0.7059
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9553013056944927
Average confidence score for samples classified same by surrogate model: 0.9743332192948325
Average confidence score for samples classified differently by surrogate model: 0.9686465938397425
Average confidence score for samples classified same by surrogate model: 0.9208123794311639
Average confidence score for samples classified differently by surrogate model: 0.9553630348731703
Average confidence score for samples classified same by surrogate model: 0.9733718585352044
Average confidence score for samples classified differently by surrogate model: 0.9544254950769726
Average confidence score for samples classified same by surrogate model: 0.9717281885914164
Average confidence score for samples classified differently by surrogate model: 0.9480272559248959
Average confidence score for samples classified same by surrogate model: 0.9771023904485906
Average confidence score for samples classified differently by surrogate model: 0.9504274845041719
Average confidence score for samples classified same by surrogate model: 0.9764987047186788
Average confidence score for samples classified differently by surrogate model: 0.9565147200163497
Average confidence score for samples classified same by surrogate model: 0.9712809488575909
Average confidence score for samples classified differently by surrogate model: 0.942899172751165
Average confidence score for samples classified same by surrogate model: 0.9825035600423946
Average confidence score for samples classified differently by surrogate model: 0.9579939052930163
Average confidence score for samples classified same by surrogate model: 0.9685576219467263
Average confidence score for samples classified differently by surrogate model: 0.9464141625057465
Average confidence score for samples classified same by surrogate model: 0.9772863453352835
Average confidence score for samples classified differently by surrogate model: 0.9489096120703625
Average confidence score for samples classified same by surrogate model: 0.9772027301983792
Average confidence score for samples classified differently by surrogate model: 0.9460478702586902
Average confidence score for samples classified same by surrogate model: 0.9763237636468123
Average confidence score for samples classified differently by surrogate model: 0.9385237009024817
Average confidence score for samples classified same by surrogate model: 0.9799145862333244
Average confidence score for samples classified differently by surrogate model: 0.9604888378185212
Average confidence score for samples classified same by surrogate model: 0.967695020568623
Average confidence score for samples classified differently by surrogate model: 0.9543050867163877
Average confidence score for samples classified same by surrogate model: 0.9702856953729999
Average confidence score for samples classified differently by surrogate model: 0.9532798003652848
Average confidence score for samples classified same by surrogate model: 0.9721948701947422
Average confidence score for samples classified differently by surrogate model: 0.9422451005666357
Average confidence score for samples classified same by surrogate model: 0.9781189467656466
Average confidence score for samples classified differently by surrogate model: 0.928721663590141
Average confidence score for samples classified same by surrogate model: 0.9837560289371164
Average confidence score for samples classified differently by surrogate model: 0.952593569226242
Average confidence score for samples classified same by surrogate model: 0.9715387233088056
Average confidence score for samples classified differently by surrogate model: 0.9490981475111643
Average confidence score for samples classified same by surrogate model: 0.976454956542079
[SHAP base] Sample set 3, n_queries=585, Top similarity=0.6471
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9591064308413989
Average confidence score for samples classified same by surrogate model: 0.9739125934322889
Average confidence score for samples classified differently by surrogate model: 0.9369742300019867
Average confidence score for samples classified same by surrogate model: 0.9811278113135703
Average confidence score for samples classified differently by surrogate model: 0.9550512327160939
Average confidence score for samples classified same by surrogate model: 0.9731171117629096
Average confidence score for samples classified differently by surrogate model: 0.9473653366601289
Average confidence score for samples classified same by surrogate model: 0.9803923110830597
Average confidence score for samples classified differently by surrogate model: 0.9544249156183053
Average confidence score for samples classified same by surrogate model: 0.9746356437388567
Average confidence score for samples classified differently by surrogate model: 0.9491951093640892
Average confidence score for samples classified same by surrogate model: 0.9763777967577093
Average confidence score for samples classified differently by surrogate model: 0.9530264973347603
Average confidence score for samples classified same by surrogate model: 0.9742245684919139
Average confidence score for samples classified differently by surrogate model: 0.961675072738613
Average confidence score for samples classified same by surrogate model: 0.9659363994643397
Average confidence score for samples classified differently by surrogate model: 0.9372187731916939
Average confidence score for samples classified same by surrogate model: 0.9880563271170972
Average confidence score for samples classified differently by surrogate model: 0.940386493492771
Average confidence score for samples classified same by surrogate model: 0.9797809364416757
Average confidence score for samples classified differently by surrogate model: 0.9384425842531541
Average confidence score for samples classified same by surrogate model: 0.98022635332393
Average confidence score for samples classified differently by surrogate model: 0.9516773148339107
Average confidence score for samples classified same by surrogate model: 0.9715969396184151
Average confidence score for samples classified differently by surrogate model: 0.9502713014311901
Average confidence score for samples classified same by surrogate model: 0.9740164182045898
Average confidence score for samples classified differently by surrogate model: 0.9558754909025036
Average confidence score for samples classified same by surrogate model: 0.9705451801378667
Average confidence score for samples classified differently by surrogate model: 0.9527155883499276
Average confidence score for samples classified same by surrogate model: 0.9727305847587471
Average confidence score for samples classified differently by surrogate model: 0.9435965397247077
Average confidence score for samples classified same by surrogate model: 0.97749126323712
Average confidence score for samples classified differently by surrogate model: 0.9468129598971572
Average confidence score for samples classified same by surrogate model: 0.9776225442003416
Average confidence score for samples classified differently by surrogate model: 0.9518552309383068
Average confidence score for samples classified same by surrogate model: 0.9749103802750351
Average confidence score for samples classified differently by surrogate model: 0.9596265363258059
Average confidence score for samples classified same by surrogate model: 0.9668988256267538
Average confidence score for samples classified differently by surrogate model: 0.9340408104346617
Average confidence score for samples classified same by surrogate model: 0.9826212370818193
[SHAP3]     Sample set 4, n_queries=575, Top similarity=0.6471
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9574082113100832
Average confidence score for samples classified same by surrogate model: 0.9763931641451973
Average confidence score for samples classified differently by surrogate model: 0.9541577436854484
Average confidence score for samples classified same by surrogate model: 0.9755996433379066
Average confidence score for samples classified differently by surrogate model: 0.958025353068018
Average confidence score for samples classified same by surrogate model: 0.972779751833084
Average confidence score for samples classified differently by surrogate model: 0.9426726107971372
Average confidence score for samples classified same by surrogate model: 0.9812962383808215
Average confidence score for samples classified differently by surrogate model: 0.9557686372608174
Average confidence score for samples classified same by surrogate model: 0.9732381732306442
Average confidence score for samples classified differently by surrogate model: 0.9573439397159634
Average confidence score for samples classified same by surrogate model: 0.9704468064083616
Average confidence score for samples classified differently by surrogate model: 0.9527582337469164
Average confidence score for samples classified same by surrogate model: 0.9735423527065862
Average confidence score for samples classified differently by surrogate model: 0.9416241878196386
Average confidence score for samples classified same by surrogate model: 0.9810155252599713
Average confidence score for samples classified differently by surrogate model: 0.9535840156034632
Average confidence score for samples classified same by surrogate model: 0.972885216440461
Average confidence score for samples classified differently by surrogate model: 0.9563101050956616
Average confidence score for samples classified same by surrogate model: 0.9705157835563778
Average confidence score for samples classified differently by surrogate model: 0.9471846588697381
Average confidence score for samples classified same by surrogate model: 0.9753950232952451
Average confidence score for samples classified differently by surrogate model: 0.9552064103005814
Average confidence score for samples classified same by surrogate model: 0.9712550990667094
Average confidence score for samples classified differently by surrogate model: 0.9503360778012812
Average confidence score for samples classified same by surrogate model: 0.9744509065743224
Average confidence score for samples classified differently by surrogate model: 0.9468923351322013
Average confidence score for samples classified same by surrogate model: 0.9800800145279136
Average confidence score for samples classified differently by surrogate model: 0.944939003328335
Average confidence score for samples classified same by surrogate model: 0.9770510075426948
Average confidence score for samples classified differently by surrogate model: 0.9424673751223499
Average confidence score for samples classified same by surrogate model: 0.9801397659435498
Average confidence score for samples classified differently by surrogate model: 0.9494906381398407
Average confidence score for samples classified same by surrogate model: 0.9720179105926832
Average confidence score for samples classified differently by surrogate model: 0.9575382120539403
Average confidence score for samples classified same by surrogate model: 0.9700018841689186
Average confidence score for samples classified differently by surrogate model: 0.94460003136664
Average confidence score for samples classified same by surrogate model: 0.9768544320028172
Average confidence score for samples classified differently by surrogate model: 0.9511553602075818
Average confidence score for samples classified same by surrogate model: 0.9746524066747386
[SHAP base] Sample set 4, n_queries=585, Top similarity=0.6588
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9565436588999214
Average confidence score for samples classified same by surrogate model: 0.978131283663583
Average confidence score for samples classified differently by surrogate model: 0.9666627772208644
Average confidence score for samples classified same by surrogate model: 0.9270418643153032
Average confidence score for samples classified differently by surrogate model: 0.9563601443832992
Average confidence score for samples classified same by surrogate model: 0.975906852844794
Average confidence score for samples classified differently by surrogate model: 0.9645230643355255
Average confidence score for samples classified same by surrogate model: 0.9523513373800352
Average confidence score for samples classified differently by surrogate model: 0.9466277974223534
Average confidence score for samples classified same by surrogate model: 0.9808293592029342
Average confidence score for samples classified differently by surrogate model: 0.9409599682917082
Average confidence score for samples classified same by surrogate model: 0.9796606344173653
Average confidence score for samples classified differently by surrogate model: 0.9561526946433122
Average confidence score for samples classified same by surrogate model: 0.971158143302968
Average confidence score for samples classified differently by surrogate model: 0.9514582104845001
Average confidence score for samples classified same by surrogate model: 0.9736396349722651
Average confidence score for samples classified differently by surrogate model: 0.9438131037776475
Average confidence score for samples classified same by surrogate model: 0.9780114896236387
Average confidence score for samples classified differently by surrogate model: 0.947474783484121
Average confidence score for samples classified same by surrogate model: 0.9781792456933057
Average confidence score for samples classified differently by surrogate model: 0.9465792254813332
Average confidence score for samples classified same by surrogate model: 0.9784594508334236
Average confidence score for samples classified differently by surrogate model: 0.9489098540836814
Average confidence score for samples classified same by surrogate model: 0.9756627908618992
Average confidence score for samples classified differently by surrogate model: 0.9489533326174636
Average confidence score for samples classified same by surrogate model: 0.9754505939707312
Average confidence score for samples classified differently by surrogate model: 0.9375949278616046
Average confidence score for samples classified same by surrogate model: 0.985608927108278
Average confidence score for samples classified differently by surrogate model: 0.9439583891183422
Average confidence score for samples classified same by surrogate model: 0.9768400680585924
Average confidence score for samples classified differently by surrogate model: 0.9364593822650731
Average confidence score for samples classified same by surrogate model: 0.9814438887216751
Average confidence score for samples classified differently by surrogate model: 0.9461416155335869
Average confidence score for samples classified same by surrogate model: 0.9732678291983362
Average confidence score for samples classified differently by surrogate model: 0.9504119823021037
Average confidence score for samples classified same by surrogate model: 0.9747245782658046
Average confidence score for samples classified differently by surrogate model: 0.9463713157154318
Average confidence score for samples classified same by surrogate model: 0.9748185765247591
Average confidence score for samples classified differently by surrogate model: 0.9440012503056487
Average confidence score for samples classified same by surrogate model: 0.9764035982418757
[SHAP3]     Sample set 5, n_queries=575, Top similarity=0.6706
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9617167101642236
Average confidence score for samples classified same by surrogate model: 0.967779741126585
Average confidence score for samples classified differently by surrogate model: 0.9342165328568063
Average confidence score for samples classified same by surrogate model: 0.984739418509775
Average confidence score for samples classified differently by surrogate model: 0.9445891689259927
Average confidence score for samples classified same by surrogate model: 0.986542972439398
Average confidence score for samples classified differently by surrogate model: 0.9615392711447701
Average confidence score for samples classified same by surrogate model: 0.98078738886965
Average confidence score for samples classified differently by surrogate model: 0.9611243328066116
Average confidence score for samples classified same by surrogate model: 0.9676682498630179
Average confidence score for samples classified differently by surrogate model: 0.9528325312247917
Average confidence score for samples classified same by surrogate model: 0.97504767543248
Average confidence score for samples classified differently by surrogate model: 0.9508833769700895
Average confidence score for samples classified same by surrogate model: 0.9764761633160892
Average confidence score for samples classified differently by surrogate model: 0.9559240054216175
Average confidence score for samples classified same by surrogate model: 0.9721669835672562
Average confidence score for samples classified differently by surrogate model: 0.9483217021890581
Average confidence score for samples classified same by surrogate model: 0.9766735107968844
Average confidence score for samples classified differently by surrogate model: 0.9382590707859303
Average confidence score for samples classified same by surrogate model: 0.9841117014571341
Average confidence score for samples classified differently by surrogate model: 0.9508932670018864
Average confidence score for samples classified same by surrogate model: 0.9742055895342387
Average confidence score for samples classified differently by surrogate model: 0.9534193978590803
Average confidence score for samples classified same by surrogate model: 0.9726107636775031
Average confidence score for samples classified differently by surrogate model: 0.9315686164341421
Average confidence score for samples classified same by surrogate model: 0.9822031455676609
Average confidence score for samples classified differently by surrogate model: 0.9510696670601416
Average confidence score for samples classified same by surrogate model: 0.9742335670423379
Average confidence score for samples classified differently by surrogate model: 0.9367265874350698
Average confidence score for samples classified same by surrogate model: 0.9807229293212825
Average confidence score for samples classified differently by surrogate model: 0.9554315314402657
Average confidence score for samples classified same by surrogate model: 0.9713032375973917
Average confidence score for samples classified differently by surrogate model: 0.9563774500478518
Average confidence score for samples classified same by surrogate model: 0.9695491691097645
Average confidence score for samples classified differently by surrogate model: 0.9519652955626842
Average confidence score for samples classified same by surrogate model: 0.9758557813903531
Average confidence score for samples classified differently by surrogate model: 0.9436269696719833
Average confidence score for samples classified same by surrogate model: 0.9754330975718694
Average confidence score for samples classified differently by surrogate model: 0.9471273779199069
Average confidence score for samples classified same by surrogate model: 0.9786900622951623
[SHAP base] Sample set 5, n_queries=585, Top similarity=0.651
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9560581588129086
Average confidence score for samples classified same by surrogate model: 0.979764495896562
Average confidence score for samples classified differently by surrogate model: 0.9645306882074506
Average confidence score for samples classified same by surrogate model: 0.9621196884377878
Average confidence score for samples classified differently by surrogate model: 0.9576639218592056
Average confidence score for samples classified same by surrogate model: 0.9712670772483203
Average confidence score for samples classified differently by surrogate model: 0.9517914987249395
Average confidence score for samples classified same by surrogate model: 0.9756561429255153
Average confidence score for samples classified differently by surrogate model: 0.9505876502232634
Average confidence score for samples classified same by surrogate model: 0.9754446976757783
Average confidence score for samples classified differently by surrogate model: 0.9477414657545664
Average confidence score for samples classified same by surrogate model: 0.9767183200718429
Average confidence score for samples classified differently by surrogate model: 0.951919010740038
Average confidence score for samples classified same by surrogate model: 0.9748563060953067
Average confidence score for samples classified differently by surrogate model: 0.9539802564776626
Average confidence score for samples classified same by surrogate model: 0.9727017394275403
Average confidence score for samples classified differently by surrogate model: 0.9513761985936214
Average confidence score for samples classified same by surrogate model: 0.9764047126569797
Average confidence score for samples classified differently by surrogate model: 0.9485042685398347
Average confidence score for samples classified same by surrogate model: 0.9777514136128702
Average confidence score for samples classified differently by surrogate model: 0.9452382679407633
Average confidence score for samples classified same by surrogate model: 0.9795265508481021
Average confidence score for samples classified differently by surrogate model: 0.9381741788255686
Average confidence score for samples classified same by surrogate model: 0.9829411512901111
Average confidence score for samples classified differently by surrogate model: 0.9413067452646776
Average confidence score for samples classified same by surrogate model: 0.9815223237252527
Average confidence score for samples classified differently by surrogate model: 0.9491604148400802
Average confidence score for samples classified same by surrogate model: 0.9780319724036347
Average confidence score for samples classified differently by surrogate model: 0.9459991870407277
Average confidence score for samples classified same by surrogate model: 0.9750358441981887
Average confidence score for samples classified differently by surrogate model: 0.9493086844622248
Average confidence score for samples classified same by surrogate model: 0.975548273228454
Average confidence score for samples classified differently by surrogate model: 0.94306744340242
Average confidence score for samples classified same by surrogate model: 0.9797059327951206
Average confidence score for samples classified differently by surrogate model: 0.9454634961221456
Average confidence score for samples classified same by surrogate model: 0.9767070220090915
Average confidence score for samples classified differently by surrogate model: 0.9377853106202134
Average confidence score for samples classified same by surrogate model: 0.981179158630357
Average confidence score for samples classified differently by surrogate model: 0.9556554507501495
Average confidence score for samples classified same by surrogate model: 0.9710204129477096
[SHAP3]     Sample set 6, n_queries=575, Top similarity=0.6314
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9601313719313244
Average confidence score for samples classified same by surrogate model: 0.9719027417692268
Average confidence score for samples classified differently by surrogate model: 0.9643321352852432
Average confidence score for samples classified same by surrogate model: 0
Average confidence score for samples classified differently by surrogate model: 0.9539580449955982
Average confidence score for samples classified same by surrogate model: 0.978914582956535
Average confidence score for samples classified differently by surrogate model: 0.9585924875882366
Average confidence score for samples classified same by surrogate model: 0.971898034522204
Average confidence score for samples classified differently by surrogate model: 0.9523030939981846
Average confidence score for samples classified same by surrogate model: 0.9740577431343524
Average confidence score for samples classified differently by surrogate model: 0.9533926149534974
Average confidence score for samples classified same by surrogate model: 0.9731768538513341
Average confidence score for samples classified differently by surrogate model: 0.9588014279488489
Average confidence score for samples classified same by surrogate model: 0.969994526129645
Average confidence score for samples classified differently by surrogate model: 0.9545966538845528
Average confidence score for samples classified same by surrogate model: 0.9752845518610177
Average confidence score for samples classified differently by surrogate model: 0.9441574603704248
Average confidence score for samples classified same by surrogate model: 0.9831312641831406
Average confidence score for samples classified differently by surrogate model: 0.961849748811402
Average confidence score for samples classified same by surrogate model: 0.9677657165761618
Average confidence score for samples classified differently by surrogate model: 0.9429336874154607
Average confidence score for samples classified same by surrogate model: 0.984271598072993
Average confidence score for samples classified differently by surrogate model: 0.9536937530593931
Average confidence score for samples classified same by surrogate model: 0.9737884750415526
Average confidence score for samples classified differently by surrogate model: 0.9555878648399878
Average confidence score for samples classified same by surrogate model: 0.972228080985808
Average confidence score for samples classified differently by surrogate model: 0.9523601132827715
Average confidence score for samples classified same by surrogate model: 0.975313990054426
Average confidence score for samples classified differently by surrogate model: 0.9454748364380581
Average confidence score for samples classified same by surrogate model: 0.976102933291765
Average confidence score for samples classified differently by surrogate model: 0.9523372785750558
Average confidence score for samples classified same by surrogate model: 0.9743422315325919
Average confidence score for samples classified differently by surrogate model: 0.9554927466971764
Average confidence score for samples classified same by surrogate model: 0.9704201910015261
Average confidence score for samples classified differently by surrogate model: 0.9469826048448934
Average confidence score for samples classified same by surrogate model: 0.9755253807306287
Average confidence score for samples classified differently by surrogate model: 0.9472500754465749
Average confidence score for samples classified same by surrogate model: 0.9755353044002129
Average confidence score for samples classified differently by surrogate model: 0.9532955314372265
Average confidence score for samples classified same by surrogate model: 0.9739891636522562
[SHAP base] Sample set 6, n_queries=585, Top similarity=0.6157
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9650539341060173
Average confidence score for samples classified same by surrogate model: 0.9626635613878688
Average confidence score for samples classified differently by surrogate model: 0.9468278900973979
Average confidence score for samples classified same by surrogate model: 0.9752583520266993
Average confidence score for samples classified differently by surrogate model: 0.9555874247063377
Average confidence score for samples classified same by surrogate model: 0.9790600688918191
Average confidence score for samples classified differently by surrogate model: 0.9496273949807104
Average confidence score for samples classified same by surrogate model: 0.9762210742548637
Average confidence score for samples classified differently by surrogate model: 0.9540176060934494
Average confidence score for samples classified same by surrogate model: 0.976120168647291
Average confidence score for samples classified differently by surrogate model: 0.9461964146545727
Average confidence score for samples classified same by surrogate model: 0.9780902681774739
Average confidence score for samples classified differently by surrogate model: 0.9523947245909575
Average confidence score for samples classified same by surrogate model: 0.9749431670134956
Average confidence score for samples classified differently by surrogate model: 0.9527142291194449
Average confidence score for samples classified same by surrogate model: 0.9727315674456497
Average confidence score for samples classified differently by surrogate model: 0.93991360201769
Average confidence score for samples classified same by surrogate model: 0.9781143749209165
Average confidence score for samples classified differently by surrogate model: 0.9428036202051729
Average confidence score for samples classified same by surrogate model: 0.9794020958412906
Average confidence score for samples classified differently by surrogate model: 0.9516111421307596
Average confidence score for samples classified same by surrogate model: 0.9735290695253072
Average confidence score for samples classified differently by surrogate model: 0.9451925845177732
Average confidence score for samples classified same by surrogate model: 0.9790855390018327
Average confidence score for samples classified differently by surrogate model: 0.9347715977491183
Average confidence score for samples classified same by surrogate model: 0.979640270795021
Average confidence score for samples classified differently by surrogate model: 0.9531236587813723
Average confidence score for samples classified same by surrogate model: 0.9710995173253147
Average confidence score for samples classified differently by surrogate model: 0.9543704250716595
Average confidence score for samples classified same by surrogate model: 0.9699546956511912
Average confidence score for samples classified differently by surrogate model: 0.9407158758540778
Average confidence score for samples classified same by surrogate model: 0.9769938647393006
Average confidence score for samples classified differently by surrogate model: 0.9415557429290293
Average confidence score for samples classified same by surrogate model: 0.9741848443382114
Average confidence score for samples classified differently by surrogate model: 0.9413439946672076
Average confidence score for samples classified same by surrogate model: 0.9799096253093051
Average confidence score for samples classified differently by surrogate model: 0.9527862263128156
Average confidence score for samples classified same by surrogate model: 0.9714204464898333
Average confidence score for samples classified differently by surrogate model: 0.955242732074821
Average confidence score for samples classified same by surrogate model: 0.9707984221329244
[SHAP3]     Sample set 7, n_queries=575, Top similarity=0.698
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.959648797746054
Average confidence score for samples classified same by surrogate model: 0.9722198616670336
Average confidence score for samples classified differently by surrogate model: 0.9614440248960647
Average confidence score for samples classified same by surrogate model: 0.9683269047955063
Average confidence score for samples classified differently by surrogate model: 0.9516224175480447
Average confidence score for samples classified same by surrogate model: 0.9759906733599649
Average confidence score for samples classified differently by surrogate model: 0.9633448603996432
Average confidence score for samples classified same by surrogate model: 0.9759326151910409
Average confidence score for samples classified differently by surrogate model: 0.9543896496368064
Average confidence score for samples classified same by surrogate model: 0.9750021198835637
Average confidence score for samples classified differently by surrogate model: 0.9639275426285451
Average confidence score for samples classified same by surrogate model: 0.967748695497359
Average confidence score for samples classified differently by surrogate model: 0.9500149355585069
Average confidence score for samples classified same by surrogate model: 0.9757253998565175
Average confidence score for samples classified differently by surrogate model: 0.9559456336958662
Average confidence score for samples classified same by surrogate model: 0.9733322833323776
Average confidence score for samples classified differently by surrogate model: 0.9523834878911399
Average confidence score for samples classified same by surrogate model: 0.9767587285751084
Average confidence score for samples classified differently by surrogate model: 0.9518027292870551
Average confidence score for samples classified same by surrogate model: 0.9729616599462451
Average confidence score for samples classified differently by surrogate model: 0.9531550164766223
Average confidence score for samples classified same by surrogate model: 0.9725438960425961
Average confidence score for samples classified differently by surrogate model: 0.9552733055078992
Average confidence score for samples classified same by surrogate model: 0.9721346310058735
Average confidence score for samples classified differently by surrogate model: 0.9519347932744325
Average confidence score for samples classified same by surrogate model: 0.9725970299591157
Average confidence score for samples classified differently by surrogate model: 0.9481799858122038
Average confidence score for samples classified same by surrogate model: 0.979621192801706
Average confidence score for samples classified differently by surrogate model: 0.9343642949539761
Average confidence score for samples classified same by surrogate model: 0.9798511954567914
Average confidence score for samples classified differently by surrogate model: 0.9469605612467148
Average confidence score for samples classified same by surrogate model: 0.9807754572759093
Average confidence score for samples classified differently by surrogate model: 0.9418795735248928
Average confidence score for samples classified same by surrogate model: 0.9761634253146485
Average confidence score for samples classified differently by surrogate model: 0.9394065160454645
Average confidence score for samples classified same by surrogate model: 0.9776958709017498
Average confidence score for samples classified differently by surrogate model: 0.9425704903444676
Average confidence score for samples classified same by surrogate model: 0.9803202825886687
Average confidence score for samples classified differently by surrogate model: 0.9536376990212312
Average confidence score for samples classified same by surrogate model: 0.9725757632387511
[SHAP base] Sample set 7, n_queries=585, Top similarity=0.6588
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9488305022036255
Average confidence score for samples classified same by surrogate model: 0.9812314565955293
Average confidence score for samples classified differently by surrogate model: 0.9629044030631008
Average confidence score for samples classified same by surrogate model: 0.993243712783622
Average confidence score for samples classified differently by surrogate model: 0.9495238016121518
Average confidence score for samples classified same by surrogate model: 0.9858326966759796
Average confidence score for samples classified differently by surrogate model: 0.9526987938089363
Average confidence score for samples classified same by surrogate model: 0.9731574288189918
Average confidence score for samples classified differently by surrogate model: 0.9596003962589941
Average confidence score for samples classified same by surrogate model: 0.9700925132302398
Average confidence score for samples classified differently by surrogate model: 0.94643169951669
Average confidence score for samples classified same by surrogate model: 0.9802436337461773
Average confidence score for samples classified differently by surrogate model: 0.9446194449118371
Average confidence score for samples classified same by surrogate model: 0.9776900767882732
Average confidence score for samples classified differently by surrogate model: 0.9511408094370148
Average confidence score for samples classified same by surrogate model: 0.9753407237628996
Average confidence score for samples classified differently by surrogate model: 0.9564601354792883
Average confidence score for samples classified same by surrogate model: 0.9715530674380721
Average confidence score for samples classified differently by surrogate model: 0.9644079953279959
Average confidence score for samples classified same by surrogate model: 0.9630262588350013
Average confidence score for samples classified differently by surrogate model: 0.9568117514449049
Average confidence score for samples classified same by surrogate model: 0.9687229183969924
Average confidence score for samples classified differently by surrogate model: 0.9570899389610537
Average confidence score for samples classified same by surrogate model: 0.9709753529660772
Average confidence score for samples classified differently by surrogate model: 0.9467186915593315
Average confidence score for samples classified same by surrogate model: 0.9755098976497626
Average confidence score for samples classified differently by surrogate model: 0.9486064326379554
Average confidence score for samples classified same by surrogate model: 0.9764540310758589
Average confidence score for samples classified differently by surrogate model: 0.9546592559299473
Average confidence score for samples classified same by surrogate model: 0.9721527611469701
Average confidence score for samples classified differently by surrogate model: 0.9556310530769816
Average confidence score for samples classified same by surrogate model: 0.970522166923334
Average confidence score for samples classified differently by surrogate model: 0.9496847909667345
Average confidence score for samples classified same by surrogate model: 0.9736275653335261
Average confidence score for samples classified differently by surrogate model: 0.9431387737955452
Average confidence score for samples classified same by surrogate model: 0.9814671935109546
Average confidence score for samples classified differently by surrogate model: 0.9487346284496251
Average confidence score for samples classified same by surrogate model: 0.9769428854927624
Average confidence score for samples classified differently by surrogate model: 0.9448685936953273
Average confidence score for samples classified same by surrogate model: 0.9764813523286285
[SHAP3]     Sample set 8, n_queries=575, Top similarity=0.6314
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9586288206231989
Average confidence score for samples classified same by surrogate model: 0.9747882121656569
Average confidence score for samples classified differently by surrogate model: 0.9536280462403679
Average confidence score for samples classified same by surrogate model: 0.9784420708443948
Average confidence score for samples classified differently by surrogate model: 0.9543325598996321
Average confidence score for samples classified same by surrogate model: 0.9754060452164139
Average confidence score for samples classified differently by surrogate model: 0.9678411578054765
Average confidence score for samples classified same by surrogate model: 0.9152058200019741
Average confidence score for samples classified differently by surrogate model: 0.9436762667662382
Average confidence score for samples classified same by surrogate model: 0.9818447194643981
Average confidence score for samples classified differently by surrogate model: 0.9486011601257329
Average confidence score for samples classified same by surrogate model: 0.9780967385498133
Average confidence score for samples classified differently by surrogate model: 0.9528833759192354
Average confidence score for samples classified same by surrogate model: 0.9722173735240814
Average confidence score for samples classified differently by surrogate model: 0.9372931171828413
Average confidence score for samples classified same by surrogate model: 0.9812099937185881
Average confidence score for samples classified differently by surrogate model: 0.9529544995266962
Average confidence score for samples classified same by surrogate model: 0.9752721696684596
Average confidence score for samples classified differently by surrogate model: 0.9529192566981429
Average confidence score for samples classified same by surrogate model: 0.9754795980912462
Average confidence score for samples classified differently by surrogate model: 0.953962737839834
Average confidence score for samples classified same by surrogate model: 0.9727159034325938
Average confidence score for samples classified differently by surrogate model: 0.957075558150662
Average confidence score for samples classified same by surrogate model: 0.9723683446739506
Average confidence score for samples classified differently by surrogate model: 0.9492493322932096
Average confidence score for samples classified same by surrogate model: 0.9739039141071092
Average confidence score for samples classified differently by surrogate model: 0.9585703544851747
Average confidence score for samples classified same by surrogate model: 0.9711280818699372
Average confidence score for samples classified differently by surrogate model: 0.952251353944285
Average confidence score for samples classified same by surrogate model: 0.9712673986476439
Average confidence score for samples classified differently by surrogate model: 0.9459954425771474
Average confidence score for samples classified same by surrogate model: 0.9849609145818488
Average confidence score for samples classified differently by surrogate model: 0.9465850456038215
Average confidence score for samples classified same by surrogate model: 0.9775816748419195
Average confidence score for samples classified differently by surrogate model: 0.9494366723376266
Average confidence score for samples classified same by surrogate model: 0.9765676941350697
Average confidence score for samples classified differently by surrogate model: 0.9446044182956223
Average confidence score for samples classified same by surrogate model: 0.9777002592979455
Average confidence score for samples classified differently by surrogate model: 0.9528451498389788
Average confidence score for samples classified same by surrogate model: 0.9748690693036194
[SHAP base] Sample set 8, n_queries=585, Top similarity=0.6353
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9593044193297163
Average confidence score for samples classified same by surrogate model: 0.9708545776059245
Average confidence score for samples classified differently by surrogate model: 0.956776175939772
Average confidence score for samples classified same by surrogate model: 0.9712631656622902
Average confidence score for samples classified differently by surrogate model: 0.9575251951756646
Average confidence score for samples classified same by surrogate model: 0.970980774462039
Average confidence score for samples classified differently by surrogate model: 0.9524350521546145
Average confidence score for samples classified same by surrogate model: 0.9717583400419401
Average confidence score for samples classified differently by surrogate model: 0.9616180408870905
Average confidence score for samples classified same by surrogate model: 0.96715479345932
Average confidence score for samples classified differently by surrogate model: 0.9533659853891954
Average confidence score for samples classified same by surrogate model: 0.9711772479592081
Average confidence score for samples classified differently by surrogate model: 0.9456439358048803
Average confidence score for samples classified same by surrogate model: 0.979683156286968
Average confidence score for samples classified differently by surrogate model: 0.9443017608597217
Average confidence score for samples classified same by surrogate model: 0.9783533973831069
Average confidence score for samples classified differently by surrogate model: 0.9566857591491215
Average confidence score for samples classified same by surrogate model: 0.97156992643699
Average confidence score for samples classified differently by surrogate model: 0.9596887117585788
Average confidence score for samples classified same by surrogate model: 0.9674277509696847
Average confidence score for samples classified differently by surrogate model: 0.9508354756106068
Average confidence score for samples classified same by surrogate model: 0.9722121726108058
Average confidence score for samples classified differently by surrogate model: 0.9395744212053166
Average confidence score for samples classified same by surrogate model: 0.9811087441683498
Average confidence score for samples classified differently by surrogate model: 0.9435509884069002
Average confidence score for samples classified same by surrogate model: 0.9808692451250499
Average confidence score for samples classified differently by surrogate model: 0.9465843035130479
Average confidence score for samples classified same by surrogate model: 0.9741800175490821
Average confidence score for samples classified differently by surrogate model: 0.9536961770901635
Average confidence score for samples classified same by surrogate model: 0.9722726794171848
Average confidence score for samples classified differently by surrogate model: 0.9553190428579655
Average confidence score for samples classified same by surrogate model: 0.9722185911591095
Average confidence score for samples classified differently by surrogate model: 0.9405291106191754
Average confidence score for samples classified same by surrogate model: 0.980994252551489
Average confidence score for samples classified differently by surrogate model: 0.9479728337550506
Average confidence score for samples classified same by surrogate model: 0.9769424302147649
Average confidence score for samples classified differently by surrogate model: 0.9448245390515563
Average confidence score for samples classified same by surrogate model: 0.9761103065961471
Average confidence score for samples classified differently by surrogate model: 0.9459083418610921
Average confidence score for samples classified same by surrogate model: 0.9745550938315701
[SHAP3]     Sample set 9, n_queries=575, Top similarity=0.6431
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9605816437010638
Average confidence score for samples classified same by surrogate model: 0.9706487526901743
Average confidence score for samples classified differently by surrogate model: 0.9560953861721058
Average confidence score for samples classified same by surrogate model: 0.9725045347959324
Average confidence score for samples classified differently by surrogate model: 0.945627461506696
Average confidence score for samples classified same by surrogate model: 0.9840927180674158
Average confidence score for samples classified differently by surrogate model: 0.9675245269274485
Average confidence score for samples classified same by surrogate model: 0.9336053657290124
Average confidence score for samples classified differently by surrogate model: 0.9539509440857196
Average confidence score for samples classified same by surrogate model: 0.9747950681477533
Average confidence score for samples classified differently by surrogate model: 0.9474295174418983
Average confidence score for samples classified same by surrogate model: 0.9791219258981684
Average confidence score for samples classified differently by surrogate model: 0.945244067915501
Average confidence score for samples classified same by surrogate model: 0.979045853882751
Average confidence score for samples classified differently by surrogate model: 0.9434875177154487
Average confidence score for samples classified same by surrogate model: 0.9784571064016155
Average confidence score for samples classified differently by surrogate model: 0.9594117302211284
Average confidence score for samples classified same by surrogate model: 0.9689170581858938
Average confidence score for samples classified differently by surrogate model: 0.9502262735505875
Average confidence score for samples classified same by surrogate model: 0.9743671778615741
Average confidence score for samples classified differently by surrogate model: 0.9528156794124233
Average confidence score for samples classified same by surrogate model: 0.9720097725337885
Average confidence score for samples classified differently by surrogate model: 0.949511345206061
Average confidence score for samples classified same by surrogate model: 0.9742126620046966
Average confidence score for samples classified differently by surrogate model: 0.9355619753237534
Average confidence score for samples classified same by surrogate model: 0.9822905790828599
Average confidence score for samples classified differently by surrogate model: 0.9497591576556377
Average confidence score for samples classified same by surrogate model: 0.9759289414271103
Average confidence score for samples classified differently by surrogate model: 0.9538542679940208
Average confidence score for samples classified same by surrogate model: 0.9721546526464968
Average confidence score for samples classified differently by surrogate model: 0.9521167991788517
Average confidence score for samples classified same by surrogate model: 0.9719569947656643
Average confidence score for samples classified differently by surrogate model: 0.9450414183754517
Average confidence score for samples classified same by surrogate model: 0.9750361306437241
Average confidence score for samples classified differently by surrogate model: 0.9394571689156976
Average confidence score for samples classified same by surrogate model: 0.9817446117439236
Average confidence score for samples classified differently by surrogate model: 0.9475630630336302
Average confidence score for samples classified same by surrogate model: 0.9736369253760764
Average confidence score for samples classified differently by surrogate model: 0.9447748421559804
Average confidence score for samples classified same by surrogate model: 0.9759442780807415
[SHAP base] Sample set 9, n_queries=585, Top similarity=0.6431
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9594011961434509
Average confidence score for samples classified same by surrogate model: 0.9763929458888153
Average confidence score for samples classified differently by surrogate model: 0.9597295918865717
Average confidence score for samples classified same by surrogate model: 0.9691187804198594
Average confidence score for samples classified differently by surrogate model: 0.9533922088722265
Average confidence score for samples classified same by surrogate model: 0.9792225906807358
Average confidence score for samples classified differently by surrogate model: 0.9546498772495275
Average confidence score for samples classified same by surrogate model: 0.9732136050623641
Average confidence score for samples classified differently by surrogate model: 0.9535515148312128
Average confidence score for samples classified same by surrogate model: 0.9723806806927027
Average confidence score for samples classified differently by surrogate model: 0.9626183777745362
Average confidence score for samples classified same by surrogate model: 0.9917522554565535
Average confidence score for samples classified differently by surrogate model: 0.9457232874822703
Average confidence score for samples classified same by surrogate model: 0.9827956014647534
Average confidence score for samples classified differently by surrogate model: 0.9529950784007919
Average confidence score for samples classified same by surrogate model: 0.972140439364599
Average confidence score for samples classified differently by surrogate model: 0.9613486930577322
Average confidence score for samples classified same by surrogate model: 0.9667442800649313
Average confidence score for samples classified differently by surrogate model: 0.9415783999128847
Average confidence score for samples classified same by surrogate model: 0.9778421656625799
Average confidence score for samples classified differently by surrogate model: 0.9366818567167631
Average confidence score for samples classified same by surrogate model: 0.9827656543308954
Average confidence score for samples classified differently by surrogate model: 0.9562962548281303
Average confidence score for samples classified same by surrogate model: 0.9696024205201014
Average confidence score for samples classified differently by surrogate model: 0.9368221222955065
Average confidence score for samples classified same by surrogate model: 0.9793375969160073
Average confidence score for samples classified differently by surrogate model: 0.9436328932880461
Average confidence score for samples classified same by surrogate model: 0.9754299216572331
Average confidence score for samples classified differently by surrogate model: 0.9492956247080326
Average confidence score for samples classified same by surrogate model: 0.9740331098511844
Average confidence score for samples classified differently by surrogate model: 0.9495216224784587
Average confidence score for samples classified same by surrogate model: 0.9725501637329089
Average confidence score for samples classified differently by surrogate model: 0.9506188909607628
Average confidence score for samples classified same by surrogate model: 0.9727510257882456
Average confidence score for samples classified differently by surrogate model: 0.9473129210920967
Average confidence score for samples classified same by surrogate model: 0.9749555938261868
Average confidence score for samples classified differently by surrogate model: 0.9447323701789692
Average confidence score for samples classified same by surrogate model: 0.974132017838379
Average confidence score for samples classified differently by surrogate model: 0.9540191034711224
Average confidence score for samples classified same by surrogate model: 0.9721558145925058
[SHAP3]     Sample set 10, n_queries=575, Top similarity=0.6667
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9583491236018591
Average confidence score for samples classified same by surrogate model: 0.9804602537361031
Average confidence score for samples classified differently by surrogate model: 0.9659962424813221
Average confidence score for samples classified same by surrogate model: 0.895271686647972
Average confidence score for samples classified differently by surrogate model: 0.9593027830815358
Average confidence score for samples classified same by surrogate model: 0.9735526143253718
Average confidence score for samples classified differently by surrogate model: 0.9538564836506769
Average confidence score for samples classified same by surrogate model: 0.9733549593208534
Average confidence score for samples classified differently by surrogate model: 0.947989230909105
Average confidence score for samples classified same by surrogate model: 0.9743654373389466
Average confidence score for samples classified differently by surrogate model: 0.9517534373435851
Average confidence score for samples classified same by surrogate model: 0.9749966835401257
Average confidence score for samples classified differently by surrogate model: 0.9639567903335683
Average confidence score for samples classified same by surrogate model: 0.964665775242286
Average confidence score for samples classified differently by surrogate model: 0.9490447858957314
Average confidence score for samples classified same by surrogate model: 0.9735622330298527
Average confidence score for samples classified differently by surrogate model: 0.9557546097151668
Average confidence score for samples classified same by surrogate model: 0.9709439779121757
Average confidence score for samples classified differently by surrogate model: 0.9532324914877914
Average confidence score for samples classified same by surrogate model: 0.9714931957997263
Average confidence score for samples classified differently by surrogate model: 0.95068841367254
Average confidence score for samples classified same by surrogate model: 0.9741961772619935
Average confidence score for samples classified differently by surrogate model: 0.9417107688923966
Average confidence score for samples classified same by surrogate model: 0.981220689647024
Average confidence score for samples classified differently by surrogate model: 0.9392507475669337
Average confidence score for samples classified same by surrogate model: 0.9824653007302355
Average confidence score for samples classified differently by surrogate model: 0.9388809119895811
Average confidence score for samples classified same by surrogate model: 0.9786972429122412
Average confidence score for samples classified differently by surrogate model: 0.9546645050054157
Average confidence score for samples classified same by surrogate model: 0.9705693161109368
Average confidence score for samples classified differently by surrogate model: 0.945130418264399
Average confidence score for samples classified same by surrogate model: 0.9801049742666491
Average confidence score for samples classified differently by surrogate model: 0.9504697072463177
Average confidence score for samples classified same by surrogate model: 0.972985115844571
Average confidence score for samples classified differently by surrogate model: 0.9487941182024546
Average confidence score for samples classified same by surrogate model: 0.9752087472431937
Average confidence score for samples classified differently by surrogate model: 0.9445582146664624
Average confidence score for samples classified same by surrogate model: 0.9754928757571917
Average confidence score for samples classified differently by surrogate model: 0.9478599438276941
Average confidence score for samples classified same by surrogate model: 0.9744448097876612
[SHAP base] Sample set 10, n_queries=585, Top similarity=0.6392
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9556303306241762
Average confidence score for samples classified same by surrogate model: 0.9802854438305305
Average confidence score for samples classified differently by surrogate model: 0.9444786777475901
Average confidence score for samples classified same by surrogate model: 0.9803838669114293
Average confidence score for samples classified differently by surrogate model: 0.9617077861162724
Average confidence score for samples classified same by surrogate model: 0.9667394330191846
Average confidence score for samples classified differently by surrogate model: 0.944462741141257
Average confidence score for samples classified same by surrogate model: 0.9763287506174599
Average confidence score for samples classified differently by surrogate model: 0.947581358351967
Average confidence score for samples classified same by surrogate model: 0.9796975096150135
Average confidence score for samples classified differently by surrogate model: 0.9445537701449571
Average confidence score for samples classified same by surrogate model: 0.9827619755295989
Average confidence score for samples classified differently by surrogate model: 0.9302544661582343
Average confidence score for samples classified same by surrogate model: 0.9829199548090654
Average confidence score for samples classified differently by surrogate model: 0.9420250940812062
Average confidence score for samples classified same by surrogate model: 0.9802015739941536
Average confidence score for samples classified differently by surrogate model: 0.9424960305296531
Average confidence score for samples classified same by surrogate model: 0.9811641327010094
Average confidence score for samples classified differently by surrogate model: 0.952178819948193
Average confidence score for samples classified same by surrogate model: 0.976581146018646
Average confidence score for samples classified differently by surrogate model: 0.9360270785472976
Average confidence score for samples classified same by surrogate model: 0.9835125355747703
Average confidence score for samples classified differently by surrogate model: 0.9338137300160049
Average confidence score for samples classified same by surrogate model: 0.9821503346349837
Average confidence score for samples classified differently by surrogate model: 0.9494292855377291
Average confidence score for samples classified same by surrogate model: 0.9763812478470614
Average confidence score for samples classified differently by surrogate model: 0.9442926148428964
Average confidence score for samples classified same by surrogate model: 0.9770495232582692
Average confidence score for samples classified differently by surrogate model: 0.9351098191081324
Average confidence score for samples classified same by surrogate model: 0.980825712514041
Average confidence score for samples classified differently by surrogate model: 0.9399573732296848
Average confidence score for samples classified same by surrogate model: 0.9798007342820382
Average confidence score for samples classified differently by surrogate model: 0.9499446604836198
Average confidence score for samples classified same by surrogate model: 0.9733128520403959
Average confidence score for samples classified differently by surrogate model: 0.9424992654323231
Average confidence score for samples classified same by surrogate model: 0.9796151441822857
Average confidence score for samples classified differently by surrogate model: 0.9378895554326822
Average confidence score for samples classified same by surrogate model: 0.9790045423985535
Average confidence score for samples classified differently by surrogate model: 0.9404108497462137
Average confidence score for samples classified same by surrogate model: 0.9771574028332761
[SHAP3]     Sample set 11, n_queries=575, Top similarity=0.651
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9581863590004229
Average confidence score for samples classified same by surrogate model: 0.9872080803454076
Average confidence score for samples classified differently by surrogate model: 0.9640462500963151
Average confidence score for samples classified same by surrogate model: 0.974460639121563
Average confidence score for samples classified differently by surrogate model: 0.9532214720014511
Average confidence score for samples classified same by surrogate model: 0.9766365061945641
Average confidence score for samples classified differently by surrogate model: 0.9476572271561762
Average confidence score for samples classified same by surrogate model: 0.9776016044302029
Average confidence score for samples classified differently by surrogate model: 0.9536191820641117
Average confidence score for samples classified same by surrogate model: 0.9738547603706917
Average confidence score for samples classified differently by surrogate model: 0.9641592409944577
Average confidence score for samples classified same by surrogate model: 0.9715072483528485
Average confidence score for samples classified differently by surrogate model: 0.9637643812211385
Average confidence score for samples classified same by surrogate model: 0.9649913073766169
Average confidence score for samples classified differently by surrogate model: 0.964162987894384
Average confidence score for samples classified same by surrogate model: 0.9680841319552059
Average confidence score for samples classified differently by surrogate model: 0.9499080593764135
Average confidence score for samples classified same by surrogate model: 0.9758104492126908
Average confidence score for samples classified differently by surrogate model: 0.9435638462760134
Average confidence score for samples classified same by surrogate model: 0.9852639541291894
Average confidence score for samples classified differently by surrogate model: 0.9443461856280583
Average confidence score for samples classified same by surrogate model: 0.9790156901354183
Average confidence score for samples classified differently by surrogate model: 0.9484232671515366
Average confidence score for samples classified same by surrogate model: 0.9784733514040919
Average confidence score for samples classified differently by surrogate model: 0.9434717982284917
Average confidence score for samples classified same by surrogate model: 0.9784677584223829
Average confidence score for samples classified differently by surrogate model: 0.9468351504645741
Average confidence score for samples classified same by surrogate model: 0.9756205125888994
Average confidence score for samples classified differently by surrogate model: 0.9454723190439234
Average confidence score for samples classified same by surrogate model: 0.9769053461127888
Average confidence score for samples classified differently by surrogate model: 0.9445719648047728
Average confidence score for samples classified same by surrogate model: 0.9818967312678818
Average confidence score for samples classified differently by surrogate model: 0.9587640575547867
Average confidence score for samples classified same by surrogate model: 0.9686241952024682
Average confidence score for samples classified differently by surrogate model: 0.9448247413037584
Average confidence score for samples classified same by surrogate model: 0.979855624862057
Average confidence score for samples classified differently by surrogate model: 0.9441662249747302
Average confidence score for samples classified same by surrogate model: 0.980636488302252
Average confidence score for samples classified differently by surrogate model: 0.9508656716612574
Average confidence score for samples classified same by surrogate model: 0.977079016883518
[SHAP base] Sample set 11, n_queries=585, Top similarity=0.6078
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 6
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9637342632099233
Average confidence score for samples classified same by surrogate model: 0.9665575480100438
Average confidence score for samples classified differently by surrogate model: 0.9458523124579772
Average confidence score for samples classified same by surrogate model: 0.9868293109010431
Average confidence score for samples classified differently by surrogate model: 0.9489545210611612
Average confidence score for samples classified same by surrogate model: 0.9784379167539482
Average confidence score for samples classified differently by surrogate model: 0.9630499692731185
Average confidence score for samples classified same by surrogate model: 0.9812139877782181
Average confidence score for samples classified differently by surrogate model: 0.9498943469518553
Average confidence score for samples classified same by surrogate model: 0.9777855289595347
Average confidence score for samples classified differently by surrogate model: 0.9566451348348267
Average confidence score for samples classified same by surrogate model: 0.9699797274528938
Average confidence score for samples classified differently by surrogate model: 0.9396439758871726
Average confidence score for samples classified same by surrogate model: 0.9846116947907991
Average confidence score for samples classified differently by surrogate model: 0.9417511237982482
Average confidence score for samples classified same by surrogate model: 0.979386142943238
Average confidence score for samples classified differently by surrogate model: 0.9503081865520241
Average confidence score for samples classified same by surrogate model: 0.9749709929449251
Average confidence score for samples classified differently by surrogate model: 0.9455347188539134
Average confidence score for samples classified same by surrogate model: 0.9790545873153739
Average confidence score for samples classified differently by surrogate model: 0.9421712306528344
Average confidence score for samples classified same by surrogate model: 0.9814144992727234
Average confidence score for samples classified differently by surrogate model: 0.954391201561857
Average confidence score for samples classified same by surrogate model: 0.9721180414182431
Average confidence score for samples classified differently by surrogate model: 0.9459578943813497
Average confidence score for samples classified same by surrogate model: 0.9759927112434821
Average confidence score for samples classified differently by surrogate model: 0.9396168201538515
Average confidence score for samples classified same by surrogate model: 0.9802774998861394
Average confidence score for samples classified differently by surrogate model: 0.9510193607145335
Average confidence score for samples classified same by surrogate model: 0.9742711245195383
Average confidence score for samples classified differently by surrogate model: 0.9395690878228521
Average confidence score for samples classified same by surrogate model: 0.9797893241471162
Average confidence score for samples classified differently by surrogate model: 0.9417892376007546
Average confidence score for samples classified same by surrogate model: 0.9798583694520416
Average confidence score for samples classified differently by surrogate model: 0.9457133441537162
Average confidence score for samples classified same by surrogate model: 0.9782324656505598
Average confidence score for samples classified differently by surrogate model: 0.9378145163526224
Average confidence score for samples classified same by surrogate model: 0.9808845343642025
Average confidence score for samples classified differently by surrogate model: 0.9342161947597144
Average confidence score for samples classified same by surrogate model: 0.984739647615041
[SHAP3]     Sample set 12, n_queries=575, Top similarity=0.6157
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9678834357879235
Average confidence score for samples classified same by surrogate model: 0.9574744515559273
Average confidence score for samples classified differently by surrogate model: 0.9619100072168502
Average confidence score for samples classified same by surrogate model: 0.9944175155031776
Average confidence score for samples classified differently by surrogate model: 0.9564435646803658
Average confidence score for samples classified same by surrogate model: 0.9711266705507563
Average confidence score for samples classified differently by surrogate model: 0.9497264212929046
Average confidence score for samples classified same by surrogate model: 0.9767152406265718
Average confidence score for samples classified differently by surrogate model: 0.9538452122298314
Average confidence score for samples classified same by surrogate model: 0.9763171902057116
Average confidence score for samples classified differently by surrogate model: 0.954515217559658
Average confidence score for samples classified same by surrogate model: 0.9722692177016721
Average confidence score for samples classified differently by surrogate model: 0.9491694470269778
Average confidence score for samples classified same by surrogate model: 0.9827910601213898
Average confidence score for samples classified differently by surrogate model: 0.9476675196542553
Average confidence score for samples classified same by surrogate model: 0.9769742574880599
Average confidence score for samples classified differently by surrogate model: 0.9527109411215042
Average confidence score for samples classified same by surrogate model: 0.9732901391197905
Average confidence score for samples classified differently by surrogate model: 0.9412071817800389
Average confidence score for samples classified same by surrogate model: 0.9787668196388087
Average confidence score for samples classified differently by surrogate model: 0.9441686234640342
Average confidence score for samples classified same by surrogate model: 0.9801245361522027
Average confidence score for samples classified differently by surrogate model: 0.9535311557712814
Average confidence score for samples classified same by surrogate model: 0.9717712205134008
Average confidence score for samples classified differently by surrogate model: 0.9549420353818076
Average confidence score for samples classified same by surrogate model: 0.969907507102907
Average confidence score for samples classified differently by surrogate model: 0.9454089709533146
Average confidence score for samples classified same by surrogate model: 0.9767427820224154
Average confidence score for samples classified differently by surrogate model: 0.9381783101779794
Average confidence score for samples classified same by surrogate model: 0.9814849686348105
Average confidence score for samples classified differently by surrogate model: 0.9508401074144239
Average confidence score for samples classified same by surrogate model: 0.9783638442708931
Average confidence score for samples classified differently by surrogate model: 0.9428351130445699
Average confidence score for samples classified same by surrogate model: 0.976057783780155
Average confidence score for samples classified differently by surrogate model: 0.9477628804877776
Average confidence score for samples classified same by surrogate model: 0.9753783051502188
Average confidence score for samples classified differently by surrogate model: 0.9447166332326643
Average confidence score for samples classified same by surrogate model: 0.976987297899809
Average confidence score for samples classified differently by surrogate model: 0.9542566272252407
Average confidence score for samples classified same by surrogate model: 0.9724782907380092
[SHAP base] Sample set 12, n_queries=585, Top similarity=0.6471
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9533830279828178
Average confidence score for samples classified same by surrogate model: 0.982166763674759
Average confidence score for samples classified differently by surrogate model: 0.9538154486188238
Average confidence score for samples classified same by surrogate model: 0.9716938159517353
Average confidence score for samples classified differently by surrogate model: 0.9618631120702867
Average confidence score for samples classified same by surrogate model: 0.967484548854337
Average confidence score for samples classified differently by surrogate model: 0.9528761199089337
Average confidence score for samples classified same by surrogate model: 0.9740448439738516
Average confidence score for samples classified differently by surrogate model: 0.9537169327121291
Average confidence score for samples classified same by surrogate model: 0.9737678709057872
Average confidence score for samples classified differently by surrogate model: 0.9427592657539646
Average confidence score for samples classified same by surrogate model: 0.9799287369058282
Average confidence score for samples classified differently by surrogate model: 0.9346858530837411
Average confidence score for samples classified same by surrogate model: 0.9879238950653101
Average confidence score for samples classified differently by surrogate model: 0.9567488011128173
Average confidence score for samples classified same by surrogate model: 0.9708637661782801
Average confidence score for samples classified differently by surrogate model: 0.9606721260752005
Average confidence score for samples classified same by surrogate model: 0.9670211216436404
Average confidence score for samples classified differently by surrogate model: 0.9477839192521141
Average confidence score for samples classified same by surrogate model: 0.9768859543448567
Average confidence score for samples classified differently by surrogate model: 0.9470844583490987
Average confidence score for samples classified same by surrogate model: 0.9780573993259762
Average confidence score for samples classified differently by surrogate model: 0.9481701549014986
Average confidence score for samples classified same by surrogate model: 0.9760168102924085
Average confidence score for samples classified differently by surrogate model: 0.9454073888772224
Average confidence score for samples classified same by surrogate model: 0.9744785354678559
Average confidence score for samples classified differently by surrogate model: 0.9520947483490028
Average confidence score for samples classified same by surrogate model: 0.9722272236312033
Average confidence score for samples classified differently by surrogate model: 0.9442560233929155
Average confidence score for samples classified same by surrogate model: 0.9774989359418981
Average confidence score for samples classified differently by surrogate model: 0.9417779112366016
Average confidence score for samples classified same by surrogate model: 0.9814422362876593
Average confidence score for samples classified differently by surrogate model: 0.9571710308261847
Average confidence score for samples classified same by surrogate model: 0.9692642867007522
Average confidence score for samples classified differently by surrogate model: 0.9502971128648402
Average confidence score for samples classified same by surrogate model: 0.9735369227168047
Average confidence score for samples classified differently by surrogate model: 0.9429790555010616
Average confidence score for samples classified same by surrogate model: 0.973569141708737
Average confidence score for samples classified differently by surrogate model: 0.940615671448531
Average confidence score for samples classified same by surrogate model: 0.9774918804629301
[SHAP3]     Sample set 13, n_queries=575, Top similarity=0.698
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9505969523113836
Average confidence score for samples classified same by surrogate model: 0.9827297198190346
Average confidence score for samples classified differently by surrogate model: 0.947010788534696
Average confidence score for samples classified same by surrogate model: 0.9787873599115973
Average confidence score for samples classified differently by surrogate model: 0.9556839180927806
Average confidence score for samples classified same by surrogate model: 0.9745325965891711
Average confidence score for samples classified differently by surrogate model: 0.9580321361855627
Average confidence score for samples classified same by surrogate model: 0.9712001670906305
Average confidence score for samples classified differently by surrogate model: 0.9563711288138466
Average confidence score for samples classified same by surrogate model: 0.971750345860861
Average confidence score for samples classified differently by surrogate model: 0.9513235117988058
Average confidence score for samples classified same by surrogate model: 0.9723184421091939
Average confidence score for samples classified differently by surrogate model: 0.9433760511512476
Average confidence score for samples classified same by surrogate model: 0.9780760605939013
Average confidence score for samples classified differently by surrogate model: 0.9460540922925811
Average confidence score for samples classified same by surrogate model: 0.9769209860881347
Average confidence score for samples classified differently by surrogate model: 0.9508304699105489
Average confidence score for samples classified same by surrogate model: 0.9727599264108472
Average confidence score for samples classified differently by surrogate model: 0.9517540666700028
Average confidence score for samples classified same by surrogate model: 0.9756899435124364
Average confidence score for samples classified differently by surrogate model: 0.9416719913082445
Average confidence score for samples classified same by surrogate model: 0.9799391218654261
Average confidence score for samples classified differently by surrogate model: 0.9465528365814662
Average confidence score for samples classified same by surrogate model: 0.9778198791294865
Average confidence score for samples classified differently by surrogate model: 0.9509976912047884
Average confidence score for samples classified same by surrogate model: 0.9738183840941559
Average confidence score for samples classified differently by surrogate model: 0.9442913307608949
Average confidence score for samples classified same by surrogate model: 0.9772616865912728
Average confidence score for samples classified differently by surrogate model: 0.9307750835936989
Average confidence score for samples classified same by surrogate model: 0.9823235666138415
Average confidence score for samples classified differently by surrogate model: 0.9440306253495409
Average confidence score for samples classified same by surrogate model: 0.9818181073466494
Average confidence score for samples classified differently by surrogate model: 0.9476452484484144
Average confidence score for samples classified same by surrogate model: 0.975639696760198
Average confidence score for samples classified differently by surrogate model: 0.9504718278346814
Average confidence score for samples classified same by surrogate model: 0.9741924882366482
Average confidence score for samples classified differently by surrogate model: 0.9439071377968286
Average confidence score for samples classified same by surrogate model: 0.9783996832242822
Average confidence score for samples classified differently by surrogate model: 0.9592189958770844
Average confidence score for samples classified same by surrogate model: 0.9674193137958287
[SHAP base] Sample set 13, n_queries=585, Top similarity=0.651
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9543542557209145
Average confidence score for samples classified same by surrogate model: 0.9803171056076857
Average confidence score for samples classified differently by surrogate model: 0.9515102270174793
Average confidence score for samples classified same by surrogate model: 0.9762798225347487
Average confidence score for samples classified differently by surrogate model: 0.9486022426594064
Average confidence score for samples classified same by surrogate model: 0.9887134688552883
Average confidence score for samples classified differently by surrogate model: 0.9637882025709685
Average confidence score for samples classified same by surrogate model: 0.971947193285087
Average confidence score for samples classified differently by surrogate model: 0.9444954091258475
Average confidence score for samples classified same by surrogate model: 0.9849623304910126
Average confidence score for samples classified differently by surrogate model: 0.9634730090783025
Average confidence score for samples classified same by surrogate model: 0.9999858728732821
Average confidence score for samples classified differently by surrogate model: 0.9505919205056514
Average confidence score for samples classified same by surrogate model: 0.9731967899817529
Average confidence score for samples classified differently by surrogate model: 0.957206481753116
Average confidence score for samples classified same by surrogate model: 0.9693200927577308
Average confidence score for samples classified differently by surrogate model: 0.9566055711238142
Average confidence score for samples classified same by surrogate model: 0.9699182323478965
Average confidence score for samples classified differently by surrogate model: 0.9547869531878757
Average confidence score for samples classified same by surrogate model: 0.9730878662316987
Average confidence score for samples classified differently by surrogate model: 0.9442676305334774
Average confidence score for samples classified same by surrogate model: 0.9797985243647278
Average confidence score for samples classified differently by surrogate model: 0.9471480671828969
Average confidence score for samples classified same by surrogate model: 0.9769571649114557
Average confidence score for samples classified differently by surrogate model: 0.9485170025391132
Average confidence score for samples classified same by surrogate model: 0.9788392495335712
Average confidence score for samples classified differently by surrogate model: 0.9463264687117982
Average confidence score for samples classified same by surrogate model: 0.9767333890841704
Average confidence score for samples classified differently by surrogate model: 0.948079677878703
Average confidence score for samples classified same by surrogate model: 0.9738211476840916
Average confidence score for samples classified differently by surrogate model: 0.9404224853893296
Average confidence score for samples classified same by surrogate model: 0.9758699314559447
Average confidence score for samples classified differently by surrogate model: 0.9538919870878112
Average confidence score for samples classified same by surrogate model: 0.9708489156887345
Average confidence score for samples classified differently by surrogate model: 0.9552671496693509
Average confidence score for samples classified same by surrogate model: 0.970992124717326
Average confidence score for samples classified differently by surrogate model: 0.9486330044006753
Average confidence score for samples classified same by surrogate model: 0.973970209309312
Average confidence score for samples classified differently by surrogate model: 0.9495602589885543
Average confidence score for samples classified same by surrogate model: 0.9748409868788591
[SHAP3]     Sample set 14, n_queries=575, Top similarity=0.6745
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9598096382955704
Average confidence score for samples classified same by surrogate model: 0.9843465900480485
Average confidence score for samples classified differently by surrogate model: 0.964212635058522
Average confidence score for samples classified same by surrogate model: 0.9644665730403026
Average confidence score for samples classified differently by surrogate model: 0.9483225711918993
Average confidence score for samples classified same by surrogate model: 0.9823428948902532
Average confidence score for samples classified differently by surrogate model: 0.9547615088377094
Average confidence score for samples classified same by surrogate model: 0.9724463620559767
Average confidence score for samples classified differently by surrogate model: 0.961208883411212
Average confidence score for samples classified same by surrogate model: 0.9676316997650646
Average confidence score for samples classified differently by surrogate model: 0.9476593074917113
Average confidence score for samples classified same by surrogate model: 0.979868179365578
Average confidence score for samples classified differently by surrogate model: 0.9593389339314865
Average confidence score for samples classified same by surrogate model: 0.9703153679418975
Average confidence score for samples classified differently by surrogate model: 0.9474439129542966
Average confidence score for samples classified same by surrogate model: 0.9791093298248197
Average confidence score for samples classified differently by surrogate model: 0.9474424434571747
Average confidence score for samples classified same by surrogate model: 0.9824576582226807
Average confidence score for samples classified differently by surrogate model: 0.9520435096615909
Average confidence score for samples classified same by surrogate model: 0.9749164989610881
Average confidence score for samples classified differently by surrogate model: 0.9506188416719802
Average confidence score for samples classified same by surrogate model: 0.9779382937921506
Average confidence score for samples classified differently by surrogate model: 0.9536186271480671
Average confidence score for samples classified same by surrogate model: 0.9763848319395642
Average confidence score for samples classified differently by surrogate model: 0.9412457538333845
Average confidence score for samples classified same by surrogate model: 0.9792265749316024
Average confidence score for samples classified differently by surrogate model: 0.9428307322450946
Average confidence score for samples classified same by surrogate model: 0.980129084457596
Average confidence score for samples classified differently by surrogate model: 0.9441866445288882
Average confidence score for samples classified same by surrogate model: 0.9793722619458082
Average confidence score for samples classified differently by surrogate model: 0.9523340159638588
Average confidence score for samples classified same by surrogate model: 0.9743449542872601
Average confidence score for samples classified differently by surrogate model: 0.943804626481527
Average confidence score for samples classified same by surrogate model: 0.9804096246979424
Average confidence score for samples classified differently by surrogate model: 0.9430530302772638
Average confidence score for samples classified same by surrogate model: 0.9804749046016396
Average confidence score for samples classified differently by surrogate model: 0.9499157754351764
Average confidence score for samples classified same by surrogate model: 0.9756232702727066
Average confidence score for samples classified differently by surrogate model: 0.9549288281808865
Average confidence score for samples classified same by surrogate model: 0.9728231812526082
[SHAP base] Sample set 14, n_queries=585, Top similarity=0.6078
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9583753750712249
Average confidence score for samples classified same by surrogate model: 0.9747084272709503
Average confidence score for samples classified differently by surrogate model: 0.958905821511627
Average confidence score for samples classified same by surrogate model: 0.9713716774780404
Average confidence score for samples classified differently by surrogate model: 0.9553508532947098
Average confidence score for samples classified same by surrogate model: 0.9780263672312022
Average confidence score for samples classified differently by surrogate model: 0.9576475250508351
Average confidence score for samples classified same by surrogate model: 0.9692432774982764
Average confidence score for samples classified differently by surrogate model: 0.953452543253513
Average confidence score for samples classified same by surrogate model: 0.97800383500653
Average confidence score for samples classified differently by surrogate model: 0.9494576660114241
Average confidence score for samples classified same by surrogate model: 0.9749139724867504
Average confidence score for samples classified differently by surrogate model: 0.9522460348301436
Average confidence score for samples classified same by surrogate model: 0.9754186334470621
Average confidence score for samples classified differently by surrogate model: 0.9545141066686937
Average confidence score for samples classified same by surrogate model: 0.9717802949253825
Average confidence score for samples classified differently by surrogate model: 0.9573009653955358
Average confidence score for samples classified same by surrogate model: 0.9713083741601855
Average confidence score for samples classified differently by surrogate model: 0.9457835888608717
Average confidence score for samples classified same by surrogate model: 0.9790925982849177
Average confidence score for samples classified differently by surrogate model: 0.9449775983525172
Average confidence score for samples classified same by surrogate model: 0.979251257504218
Average confidence score for samples classified differently by surrogate model: 0.9538079570470053
Average confidence score for samples classified same by surrogate model: 0.9724445226772165
Average confidence score for samples classified differently by surrogate model: 0.9505252634725795
Average confidence score for samples classified same by surrogate model: 0.9739969455541063
Average confidence score for samples classified differently by surrogate model: 0.9532026095218441
Average confidence score for samples classified same by surrogate model: 0.9716313697144838
Average confidence score for samples classified differently by surrogate model: 0.949532417855965
Average confidence score for samples classified same by surrogate model: 0.9740384434693786
Average confidence score for samples classified differently by surrogate model: 0.9582522828010589
Average confidence score for samples classified same by surrogate model: 0.9681905032078973
Average confidence score for samples classified differently by surrogate model: 0.9590400264126703
Average confidence score for samples classified same by surrogate model: 0.968283093279149
Average confidence score for samples classified differently by surrogate model: 0.9506118569956984
Average confidence score for samples classified same by surrogate model: 0.9734789874782712
Average confidence score for samples classified differently by surrogate model: 0.9434428373893397
Average confidence score for samples classified same by surrogate model: 0.9769445415620139
Average confidence score for samples classified differently by surrogate model: 0.9454803212421625
Average confidence score for samples classified same by surrogate model: 0.9771067198012765
[SHAP3]     Sample set 15, n_queries=575, Top similarity=0.6235
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9564792165855521
Average confidence score for samples classified same by surrogate model: 0.976305892510513
Average confidence score for samples classified differently by surrogate model: 0.9622131512235297
Average confidence score for samples classified same by surrogate model: 0.9847273568792354
Average confidence score for samples classified differently by surrogate model: 0.9577603195260829
Average confidence score for samples classified same by surrogate model: 0.9709556976251823
Average confidence score for samples classified differently by surrogate model: 0.9548168012519357
Average confidence score for samples classified same by surrogate model: 0.9736261824805649
Average confidence score for samples classified differently by surrogate model: 0.9552376223134431
Average confidence score for samples classified same by surrogate model: 0.9726744704924566
Average confidence score for samples classified differently by surrogate model: 0.9481371517853262
Average confidence score for samples classified same by surrogate model: 0.9778473733139488
Average confidence score for samples classified differently by surrogate model: 0.9484870767673971
Average confidence score for samples classified same by surrogate model: 0.975604458794582
Average confidence score for samples classified differently by surrogate model: 0.9468723972264734
Average confidence score for samples classified same by surrogate model: 0.9791349566828941
Average confidence score for samples classified differently by surrogate model: 0.9477103549630376
Average confidence score for samples classified same by surrogate model: 0.9759673815107853
Average confidence score for samples classified differently by surrogate model: 0.9452767858324508
Average confidence score for samples classified same by surrogate model: 0.9774563494778936
Average confidence score for samples classified differently by surrogate model: 0.9491201102401071
Average confidence score for samples classified same by surrogate model: 0.9762464486073061
Average confidence score for samples classified differently by surrogate model: 0.9468973410020703
Average confidence score for samples classified same by surrogate model: 0.9773485227980214
Average confidence score for samples classified differently by surrogate model: 0.9475630474273673
Average confidence score for samples classified same by surrogate model: 0.9758817057304013
Average confidence score for samples classified differently by surrogate model: 0.9573239017479706
Average confidence score for samples classified same by surrogate model: 0.969821101412336
Average confidence score for samples classified differently by surrogate model: 0.9547963641703713
Average confidence score for samples classified same by surrogate model: 0.9724168107956764
Average confidence score for samples classified differently by surrogate model: 0.952791721783948
Average confidence score for samples classified same by surrogate model: 0.9757823893060577
Average confidence score for samples classified differently by surrogate model: 0.9419872259191845
Average confidence score for samples classified same by surrogate model: 0.9810142936475731
Average confidence score for samples classified differently by surrogate model: 0.9612740433192124
Average confidence score for samples classified same by surrogate model: 0.967137302351826
Average confidence score for samples classified differently by surrogate model: 0.9435570980627973
Average confidence score for samples classified same by surrogate model: 0.978874661340954
Average confidence score for samples classified differently by surrogate model: 0.9558690714298571
Average confidence score for samples classified same by surrogate model: 0.9711746124449151
[SHAP base] Sample set 15, n_queries=585, Top similarity=0.5922
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9586629894153961
Average confidence score for samples classified same by surrogate model: 0.9711253359396267
Average confidence score for samples classified differently by surrogate model: 0.9658114481429442
Average confidence score for samples classified same by surrogate model: 0.9186583508037267
Average confidence score for samples classified differently by surrogate model: 0.9511803141130888
Average confidence score for samples classified same by surrogate model: 0.9782263979751783
Average confidence score for samples classified differently by surrogate model: 0.9536921276488252
Average confidence score for samples classified same by surrogate model: 0.97424668785554
Average confidence score for samples classified differently by surrogate model: 0.9405729810563438
Average confidence score for samples classified same by surrogate model: 0.986471347180352
Average confidence score for samples classified differently by surrogate model: 0.9546387964198594
Average confidence score for samples classified same by surrogate model: 0.9719241209700178
Average confidence score for samples classified differently by surrogate model: 0.9522842899626041
Average confidence score for samples classified same by surrogate model: 0.9755585366086095
Average confidence score for samples classified differently by surrogate model: 0.9452551909405494
Average confidence score for samples classified same by surrogate model: 0.9829654297614535
Average confidence score for samples classified differently by surrogate model: 0.9501216561063639
Average confidence score for samples classified same by surrogate model: 0.9758214588766756
Average confidence score for samples classified differently by surrogate model: 0.945529961547939
Average confidence score for samples classified same by surrogate model: 0.9829874170402229
Average confidence score for samples classified differently by surrogate model: 0.9383582401991973
Average confidence score for samples classified same by surrogate model: 0.9828102082994759
Average confidence score for samples classified differently by surrogate model: 0.9436608059851156
Average confidence score for samples classified same by surrogate model: 0.9805222673245023
Average confidence score for samples classified differently by surrogate model: 0.9494601157867605
Average confidence score for samples classified same by surrogate model: 0.9773451523464137
Average confidence score for samples classified differently by surrogate model: 0.9402115031973626
Average confidence score for samples classified same by surrogate model: 0.9829251225196491
Average confidence score for samples classified differently by surrogate model: 0.9474652476636671
Average confidence score for samples classified same by surrogate model: 0.9752139982669035
Average confidence score for samples classified differently by surrogate model: 0.9514186169218436
Average confidence score for samples classified same by surrogate model: 0.9759928496283112
Average confidence score for samples classified differently by surrogate model: 0.9419530477764284
Average confidence score for samples classified same by surrogate model: 0.9790093290410229
Average confidence score for samples classified differently by surrogate model: 0.9510725811277323
Average confidence score for samples classified same by surrogate model: 0.9763053147856802
Average confidence score for samples classified differently by surrogate model: 0.9455138130377991
Average confidence score for samples classified same by surrogate model: 0.9770840247029177
Average confidence score for samples classified differently by surrogate model: 0.9490495307204108
Average confidence score for samples classified same by surrogate model: 0.9783507650364409
[SHAP3]     Sample set 16, n_queries=575, Top similarity=0.6078
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9557992649493852
Average confidence score for samples classified same by surrogate model: 0.9750548573002134
Average confidence score for samples classified differently by surrogate model: 0.9463097060329215
Average confidence score for samples classified same by surrogate model: 0.9808639876821081
Average confidence score for samples classified differently by surrogate model: 0.9430676185126254
Average confidence score for samples classified same by surrogate model: 0.9829385874612816
Average confidence score for samples classified differently by surrogate model: 0.9487366601359594
Average confidence score for samples classified same by surrogate model: 0.979327784467245
Average confidence score for samples classified differently by surrogate model: 0.9471258011207152
Average confidence score for samples classified same by surrogate model: 0.9793876776792032
Average confidence score for samples classified differently by surrogate model: 0.9561097411805727
Average confidence score for samples classified same by surrogate model: 0.9731561679829362
Average confidence score for samples classified differently by surrogate model: 0.9518138100636805
Average confidence score for samples classified same by surrogate model: 0.9739816776435295
Average confidence score for samples classified differently by surrogate model: 0.9482126300376201
Average confidence score for samples classified same by surrogate model: 0.976366560435864
Average confidence score for samples classified differently by surrogate model: 0.9471929593931938
Average confidence score for samples classified same by surrogate model: 0.9781893413256217
Average confidence score for samples classified differently by surrogate model: 0.9459912347909742
Average confidence score for samples classified same by surrogate model: 0.9822465032098759
Average confidence score for samples classified differently by surrogate model: 0.9552058220970434
Average confidence score for samples classified same by surrogate model: 0.970617807944664
Average confidence score for samples classified differently by surrogate model: 0.9432153234764479
Average confidence score for samples classified same by surrogate model: 0.983102634670837
Average confidence score for samples classified differently by surrogate model: 0.950932759884571
Average confidence score for samples classified same by surrogate model: 0.9738645768454512
Average confidence score for samples classified differently by surrogate model: 0.945248559003135
Average confidence score for samples classified same by surrogate model: 0.9762441765313984
Average confidence score for samples classified differently by surrogate model: 0.9425750135519037
Average confidence score for samples classified same by surrogate model: 0.9768223347988261
Average confidence score for samples classified differently by surrogate model: 0.9504993355127024
Average confidence score for samples classified same by surrogate model: 0.974825983388548
Average confidence score for samples classified differently by surrogate model: 0.9388127623848301
Average confidence score for samples classified same by surrogate model: 0.9819083921173141
Average confidence score for samples classified differently by surrogate model: 0.9428356716774164
Average confidence score for samples classified same by surrogate model: 0.9859978623860429
Average confidence score for samples classified differently by surrogate model: 0.9508723728581009
Average confidence score for samples classified same by surrogate model: 0.9730158529801722
Average confidence score for samples classified differently by surrogate model: 0.9432755739371457
Average confidence score for samples classified same by surrogate model: 0.9790717282289098
[SHAP base] Sample set 16, n_queries=585, Top similarity=0.6353
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9550354460360146
Average confidence score for samples classified same by surrogate model: 0.9850437467771936
Average confidence score for samples classified differently by surrogate model: 0.9556240976275788
Average confidence score for samples classified same by surrogate model: 0.9744423145996483
Average confidence score for samples classified differently by surrogate model: 0.9464165168043543
Average confidence score for samples classified same by surrogate model: 0.9823888216281842
Average confidence score for samples classified differently by surrogate model: 0.9499979117237219
Average confidence score for samples classified same by surrogate model: 0.9742047131024486
Average confidence score for samples classified differently by surrogate model: 0.9471951538777729
Average confidence score for samples classified same by surrogate model: 0.9790924550376611
Average confidence score for samples classified differently by surrogate model: 0.9450055595168506
Average confidence score for samples classified same by surrogate model: 0.9787608802082195
Average confidence score for samples classified differently by surrogate model: 0.9531943024936251
Average confidence score for samples classified same by surrogate model: 0.9745487939361993
Average confidence score for samples classified differently by surrogate model: 0.9632061034888239
Average confidence score for samples classified same by surrogate model: 0.9791582206047578
Average confidence score for samples classified differently by surrogate model: 0.9447154543236513
Average confidence score for samples classified same by surrogate model: 0.9789774655921831
Average confidence score for samples classified differently by surrogate model: 0.9508307563515369
Average confidence score for samples classified same by surrogate model: 0.972759747613288
Average confidence score for samples classified differently by surrogate model: 0.9495637502204661
Average confidence score for samples classified same by surrogate model: 0.9737043796532737
Average confidence score for samples classified differently by surrogate model: 0.9485439529268527
Average confidence score for samples classified same by surrogate model: 0.9741871790503521
Average confidence score for samples classified differently by surrogate model: 0.9490684769195941
Average confidence score for samples classified same by surrogate model: 0.973702862256558
Average confidence score for samples classified differently by surrogate model: 0.9480047501293718
Average confidence score for samples classified same by surrogate model: 0.9746937450956986
Average confidence score for samples classified differently by surrogate model: 0.9442677200732394
Average confidence score for samples classified same by surrogate model: 0.9779284166460076
Average confidence score for samples classified differently by surrogate model: 0.9385072347851632
Average confidence score for samples classified same by surrogate model: 0.983612369220233
Average confidence score for samples classified differently by surrogate model: 0.9385289297239998
Average confidence score for samples classified same by surrogate model: 0.9772337380658637
Average confidence score for samples classified differently by surrogate model: 0.9487862729101583
Average confidence score for samples classified same by surrogate model: 0.9771019508076325
Average confidence score for samples classified differently by surrogate model: 0.9410748919144565
Average confidence score for samples classified same by surrogate model: 0.9759607569706354
Average confidence score for samples classified differently by surrogate model: 0.951130525958749
Average confidence score for samples classified same by surrogate model: 0.9762529914681204
[SHAP3]     Sample set 17, n_queries=575, Top similarity=0.6667
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.960141628431572
Average confidence score for samples classified same by surrogate model: 0.969274784394699
Average confidence score for samples classified differently by surrogate model: 0.963122916228938
Average confidence score for samples classified same by surrogate model: 0.9759708687021768
Average confidence score for samples classified differently by surrogate model: 0.9654092118643652
Average confidence score for samples classified same by surrogate model: 0.9634189616638119
Average confidence score for samples classified differently by surrogate model: 0.9602545592013989
Average confidence score for samples classified same by surrogate model: 0.9677892106606742
Average confidence score for samples classified differently by surrogate model: 0.9581974900850857
Average confidence score for samples classified same by surrogate model: 0.970048509221752
Average confidence score for samples classified differently by surrogate model: 0.9649390001892444
Average confidence score for samples classified same by surrogate model: 0.9552670907817199
Average confidence score for samples classified differently by surrogate model: 0.9584251151109905
Average confidence score for samples classified same by surrogate model: 0.9697506049187665
Average confidence score for samples classified differently by surrogate model: 0.9606871530196429
Average confidence score for samples classified same by surrogate model: 0.966967358950236
Average confidence score for samples classified differently by surrogate model: 0.951309993882852
Average confidence score for samples classified same by surrogate model: 0.9743700359495853
Average confidence score for samples classified differently by surrogate model: 0.9521605266393216
Average confidence score for samples classified same by surrogate model: 0.9743302423872484
Average confidence score for samples classified differently by surrogate model: 0.9416581629275793
Average confidence score for samples classified same by surrogate model: 0.9777948063726049
Average confidence score for samples classified differently by surrogate model: 0.9512695608620515
Average confidence score for samples classified same by surrogate model: 0.9709793625065114
Average confidence score for samples classified differently by surrogate model: 0.9519272318207781
Average confidence score for samples classified same by surrogate model: 0.9727380896065572
Average confidence score for samples classified differently by surrogate model: 0.9474333342644244
Average confidence score for samples classified same by surrogate model: 0.9771519153700007
Average confidence score for samples classified differently by surrogate model: 0.950251326334125
Average confidence score for samples classified same by surrogate model: 0.971497517355042
Average confidence score for samples classified differently by surrogate model: 0.9403084992516627
Average confidence score for samples classified same by surrogate model: 0.9785961691801806
Average confidence score for samples classified differently by surrogate model: 0.9456385798034688
Average confidence score for samples classified same by surrogate model: 0.9754314338525456
Average confidence score for samples classified differently by surrogate model: 0.9487626177755981
Average confidence score for samples classified same by surrogate model: 0.9763336383655932
Average confidence score for samples classified differently by surrogate model: 0.9451699519975763
Average confidence score for samples classified same by surrogate model: 0.9746058359635694
Average confidence score for samples classified differently by surrogate model: 0.9448198697977834
Average confidence score for samples classified same by surrogate model: 0.9767149191522836
[SHAP base] Sample set 17, n_queries=585, Top similarity=0.6627
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9601184777450653
Average confidence score for samples classified same by surrogate model: 0.9769072695067106
Average confidence score for samples classified differently by surrogate model: 0.9593875865183875
Average confidence score for samples classified same by surrogate model: 0.9680831722807873
Average confidence score for samples classified differently by surrogate model: 0.945689532506111
Average confidence score for samples classified same by surrogate model: 0.9901181652974985
Average confidence score for samples classified differently by surrogate model: 0.9409629676302842
Average confidence score for samples classified same by surrogate model: 0.9844603234844028
Average confidence score for samples classified differently by surrogate model: 0.9495809606021054
Average confidence score for samples classified same by surrogate model: 0.9774442905591416
Average confidence score for samples classified differently by surrogate model: 0.9544159141572229
Average confidence score for samples classified same by surrogate model: 0.9696486634803856
Average confidence score for samples classified differently by surrogate model: 0.9568421726418458
Average confidence score for samples classified same by surrogate model: 0.9710954597617423
Average confidence score for samples classified differently by surrogate model: 0.9539579605071447
Average confidence score for samples classified same by surrogate model: 0.9717124206978482
Average confidence score for samples classified differently by surrogate model: 0.9506012489363819
Average confidence score for samples classified same by surrogate model: 0.9771268248375895
Average confidence score for samples classified differently by surrogate model: 0.9526353128606785
Average confidence score for samples classified same by surrogate model: 0.973064694492622
Average confidence score for samples classified differently by surrogate model: 0.9468302945463104
Average confidence score for samples classified same by surrogate model: 0.9778231375215021
Average confidence score for samples classified differently by surrogate model: 0.9531371650194465
Average confidence score for samples classified same by surrogate model: 0.9728248713489495
Average confidence score for samples classified differently by surrogate model: 0.9385846749209822
Average confidence score for samples classified same by surrogate model: 0.9829468532512952
Average confidence score for samples classified differently by surrogate model: 0.9482695693550763
Average confidence score for samples classified same by surrogate model: 0.9729439929225003
Average confidence score for samples classified differently by surrogate model: 0.9371357341467829
Average confidence score for samples classified same by surrogate model: 0.9786631730108978
Average confidence score for samples classified differently by surrogate model: 0.9425090492868792
Average confidence score for samples classified same by surrogate model: 0.9781814013995884
Average confidence score for samples classified differently by surrogate model: 0.9435549882021291
Average confidence score for samples classified same by surrogate model: 0.9756651246033046
Average confidence score for samples classified differently by surrogate model: 0.9452541109358461
Average confidence score for samples classified same by surrogate model: 0.975850942439595
Average confidence score for samples classified differently by surrogate model: 0.9430209165861292
Average confidence score for samples classified same by surrogate model: 0.9765663534273256
Average confidence score for samples classified differently by surrogate model: 0.9360819038819836
Average confidence score for samples classified same by surrogate model: 0.9813888787740023
[SHAP3]     Sample set 18, n_queries=575, Top similarity=0.6549
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9559734600149378
Average confidence score for samples classified same by surrogate model: 0.9748359573063324
Average confidence score for samples classified differently by surrogate model: 0.9527166529203263
Average confidence score for samples classified same by surrogate model: 0.9732857362748649
Average confidence score for samples classified differently by surrogate model: 0.956494689582661
Average confidence score for samples classified same by surrogate model: 0.9757115035649512
Average confidence score for samples classified differently by surrogate model: 0.9513781524548021
Average confidence score for samples classified same by surrogate model: 0.977388117980489
Average confidence score for samples classified differently by surrogate model: 0.9529751044004751
Average confidence score for samples classified same by surrogate model: 0.972542961668148
Average confidence score for samples classified differently by surrogate model: 0.9503146145281439
Average confidence score for samples classified same by surrogate model: 0.9778105206286062
Average confidence score for samples classified differently by surrogate model: 0.94452041464634
Average confidence score for samples classified same by surrogate model: 0.9779772938709768
Average confidence score for samples classified differently by surrogate model: 0.947776793789197
Average confidence score for samples classified same by surrogate model: 0.9766919450322898
Average confidence score for samples classified differently by surrogate model: 0.9410141546103672
Average confidence score for samples classified same by surrogate model: 0.9828879931462343
Average confidence score for samples classified differently by surrogate model: 0.9434437971292545
Average confidence score for samples classified same by surrogate model: 0.9791922953156761
Average confidence score for samples classified differently by surrogate model: 0.9566722336271481
Average confidence score for samples classified same by surrogate model: 0.9693558370220445
Average confidence score for samples classified differently by surrogate model: 0.96068755794006
Average confidence score for samples classified same by surrogate model: 0.9665326348144092
Average confidence score for samples classified differently by surrogate model: 0.9439631691288122
Average confidence score for samples classified same by surrogate model: 0.9764262089406225
Average confidence score for samples classified differently by surrogate model: 0.9426790924397491
Average confidence score for samples classified same by surrogate model: 0.9769742845242262
Average confidence score for samples classified differently by surrogate model: 0.9411158831140347
Average confidence score for samples classified same by surrogate model: 0.9767794030155887
Average confidence score for samples classified differently by surrogate model: 0.9487578205704105
Average confidence score for samples classified same by surrogate model: 0.9710693388416588
Average confidence score for samples classified differently by surrogate model: 0.9423679789271928
Average confidence score for samples classified same by surrogate model: 0.9789749061906085
Average confidence score for samples classified differently by surrogate model: 0.950421802334546
Average confidence score for samples classified same by surrogate model: 0.9743889300536512
Average confidence score for samples classified differently by surrogate model: 0.9358573551303835
Average confidence score for samples classified same by surrogate model: 0.9804037903419727
Average confidence score for samples classified differently by surrogate model: 0.9441874345841962
Average confidence score for samples classified same by surrogate model: 0.9786632646430332
[SHAP base] Sample set 18, n_queries=585, Top similarity=0.698
Dataset name in traverse_explanations_SHAP3: crop
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 0

  0%|          | 0/85 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.956963188942413
Average confidence score for samples classified same by surrogate model: 0.9810539750632031
Average confidence score for samples classified differently by surrogate model: 0.9661550332799247
Average confidence score for samples classified same by surrogate model: 0.9440198433445032
Average confidence score for samples classified differently by surrogate model: 0.9485756559480955
Average confidence score for samples classified same by surrogate model: 0.9820581745395324
Average confidence score for samples classified differently by surrogate model: 0.9671156039623037
Average confidence score for samples classified same by surrogate model: 0.9276831310372761
Average confidence score for samples classified differently by surrogate model: 0.9481152685612642
Average confidence score for samples classified same by surrogate model: 0.9751433797678949
Average confidence score for samples classified differently by surrogate model: 0.9453801321578804
Average confidence score for samples classified same by surrogate model: 0.9765592340770886
Average confidence score for samples classified differently by surrogate model: 0.9533198247596312
Average confidence score for samples classified same by surrogate model: 0.9742760873270256
Average confidence score for samples classified differently by surrogate model: 0.9338277008141631
Average confidence score for samples classified same by surrogate model: 0.9818439402593808
Average confidence score for samples classified differently by surrogate model: 0.9461096334365618
Average confidence score for samples classified same by surrogate model: 0.9795394030150761
Average confidence score for samples classified differently by surrogate model: 0.9449137450553454
Average confidence score for samples classified same by surrogate model: 0.9770675730334218
Average confidence score for samples classified differently by surrogate model: 0.9465466913430315
Average confidence score for samples classified same by surrogate model: 0.9758066152479591
Average confidence score for samples classified differently by surrogate model: 0.9556919025254419
Average confidence score for samples classified same by surrogate model: 0.9702830240734494
Average confidence score for samples classified differently by surrogate model: 0.9421045248643314
Average confidence score for samples classified same by surrogate model: 0.9847213719119426
Average confidence score for samples classified differently by surrogate model: 0.948061576084001
Average confidence score for samples classified same by surrogate model: 0.9770755103239765
Average confidence score for samples classified differently by surrogate model: 0.9518287346610913
Average confidence score for samples classified same by surrogate model: 0.971881358303598
Average confidence score for samples classified differently by surrogate model: 0.9486572037923016
Average confidence score for samples classified same by surrogate model: 0.9737962448658862
Average confidence score for samples classified differently by surrogate model: 0.9499240415775656
Average confidence score for samples classified same by surrogate model: 0.9737815993402769
Average confidence score for samples classified differently by surrogate model: 0.9470369676064843
Average confidence score for samples classified same by surrogate model: 0.975862247071081
Average confidence score for samples classified differently by surrogate model: 0.9403997629754598
Average confidence score for samples classified same by surrogate model: 0.9769432057239309
Average confidence score for samples classified differently by surrogate model: 0.9463974414592394
Average confidence score for samples classified same by surrogate model: 0.9764852501804944
[SHAP3]     Sample set 19, n_queries=575, Top similarity=0.6549
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9592108810024421
Average confidence score for samples classified same by surrogate model: 0.9813451156145471
Average confidence score for samples classified differently by surrogate model: 0.9646895725644599
Average confidence score for samples classified same by surrogate model: 0.9603492627454002
Average confidence score for samples classified differently by surrogate model: 0.955492576424385
Average confidence score for samples classified same by surrogate model: 0.975984281056372
Average confidence score for samples classified differently by surrogate model: 0.9489121879432558
Average confidence score for samples classified same by surrogate model: 0.9776135497841794
Average confidence score for samples classified differently by surrogate model: 0.9472696615408606
Average confidence score for samples classified same by surrogate model: 0.9774844587965367
Average confidence score for samples classified differently by surrogate model: 0.9487500312924382
Average confidence score for samples classified same by surrogate model: 0.9786254938350325
Average confidence score for samples classified differently by surrogate model: 0.9580349704070322
Average confidence score for samples classified same by surrogate model: 0.9695048064352007
Average confidence score for samples classified differently by surrogate model: 0.9434195167203372
Average confidence score for samples classified same by surrogate model: 0.9792095686267184
Average confidence score for samples classified differently by surrogate model: 0.958596129487143
Average confidence score for samples classified same by surrogate model: 0.9694308071057751
Average confidence score for samples classified differently by surrogate model: 0.9473833236580684
Average confidence score for samples classified same by surrogate model: 0.9803752852224145
Average confidence score for samples classified differently by surrogate model: 0.9475349588763996
Average confidence score for samples classified same by surrogate model: 0.9797400715399704
Average confidence score for samples classified differently by surrogate model: 0.9484913040557722
Average confidence score for samples classified same by surrogate model: 0.97713961585375
Average confidence score for samples classified differently by surrogate model: 0.9507526584280522
Average confidence score for samples classified same by surrogate model: 0.9736848875577439
Average confidence score for samples classified differently by surrogate model: 0.9378982620181338
Average confidence score for samples classified same by surrogate model: 0.9811074779355226
Average confidence score for samples classified differently by surrogate model: 0.9502587710460292
Average confidence score for samples classified same by surrogate model: 0.9755313617572919
Average confidence score for samples classified differently by surrogate model: 0.9476646353771859
Average confidence score for samples classified same by surrogate model: 0.9791476907590702
Average confidence score for samples classified differently by surrogate model: 0.9426119193636375
Average confidence score for samples classified same by surrogate model: 0.9808095404671495
Average confidence score for samples classified differently by surrogate model: 0.9472012458219146
Average confidence score for samples classified same by surrogate model: 0.9773279824643186
Average confidence score for samples classified differently by surrogate model: 0.9390183563622283
Average confidence score for samples classified same by surrogate model: 0.9835356917095976
Average confidence score for samples classified differently by surrogate model: 0.9452015327336794
Average confidence score for samples classified same by surrogate model: 0.9790786414187385
[SHAP base] Sample set 19, n_queries=585, Top similarity=0.6118

=== Query limit 500 | k=3 | n=5 ===
  [SHAP3 main]    Avg similarity: 0.6531  | All: [0.6471, 0.6353, 0.6392, 0.7059, 0.6471, 0.6706, 0.6314, 0.698, 0.6314, 0.6431, 0.6667, 0.651, 0.6157, 0.698, 0.6745, 0.6235, 0.6078, 0.6667, 0.6549, 0.6549]
  [SHAP baseline] Avg similarity: 0.638  | All: [0.6588, 0.6157, 0.6235, 0.6471, 0.6588, 0.651, 0.6157, 0.6588, 0.6353, 0.6431, 0.6392, 0.6078, 0.6471, 0.651, 0.6078, 0.5922, 0.6353, 0.6627, 0.698, 0.6118]
  Difference (main - baseline): +0.0151


========== FINAL COMPARISON SUMMARY ==========
  [SHAP3 main]    Overall avg similarity: 0.6531
  [SHAP baseline] Overall avg similarity: 0.638
  Overall difference (main - baseline): +0.0151
===============================================

Avg Similarity: 0.6531 | Baseline: 0.6380
Dataset: 2, Model: 0... DATASET 2 0
Train results
[[17728   778]
 [ 1529  4385]]
              precision    recall  f1-score   support

           0       0.92      0.96      0.94     18506
           1       0.85      0.74      0.79      5914

    accuracy                           0.91     24420
   macro avg       0.88      0.85      0.87     24420
weighted avg       0.90      0.91      0.90     24420

Test results
[[3355  332]
 [ 436  761]]
              precision    recall  f1-score   support

           0       0.88      0.91      0.90      3687
           1       0.70      0.64      0.66      1197

    accuracy                           0.84      4884
   macro avg       0.79      0.77      0.78      4884
weighted avg       0.84      0.84      0.84      4884

Model test accuracy:  0.8428

Dataset:   Adult Income
ML Model:  Decision Tree
SHAP is the explanation tool currently in use

Lower bounds:  [126]  Upper bounds:  [626] (per class for both)

-----The attack starts here!-----

Number of top features allowed to be explored (k): 3

Number of samples per class (n): 5
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0
Error: unhashable type: 'numpy.ndarray'
Dataset: 2, Model: 1... DATASET 2 1
Train results
[[17251  1255]
 [ 2815  3099]]
              precision    recall  f1-score   support

           0       0.86      0.93      0.89     18506
           1       0.71      0.52      0.60      5914

    accuracy                           0.83     24420
   macro avg       0.79      0.73      0.75     24420
weighted avg       0.82      0.83      0.82     24420

Test results
[[3409  278]
 [ 570  627]]
              precision    recall  f1-score   support

           0       0.86      0.92      0.89      3687
           1       0.69      0.52      0.60      1197

    accuracy                           0.83      4884
   macro avg       0.77      0.72      0.74      4884
weighted avg       0.82      0.83      0.82      4884

Model test accuracy:  0.8264

Dataset:   Adult Income
ML Model:  Logistic Regression
SHAP is the explanation tool currently in use

Lower bounds:  [126]  Upper bounds:  [626] (per class for both)

-----The attack starts here!-----

Number of top features allowed to be explored (k): 3

Number of samples per class (n): 5
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6666742134374949
Average confidence score for samples classified same by surrogate model: 0.8538772269783409
[SHAP3]     Sample set 0, n_queries=500, Top similarity=0.9208
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7828466489506042
Average confidence score for samples classified same by surrogate model: 0.8473661075418489
[SHAP base] Sample set 0, n_queries=510, Top similarity=0.871
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 6
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7048024496153317
Average confidence score for samples classified same by surrogate model: 0.8580594964597987
[SHAP3]     Sample set 1, n_queries=500, Top similarity=0.8759
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8245853091430296
Average confidence score for samples classified same by surrogate model: 0.8406266904395657
[SHAP base] Sample set 1, n_queries=510, Top similarity=0.9013
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 8
Diverse samples left to process: 6
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6998116046677711
Average confidence score for samples classified same by surrogate model: 0.8597008435872426
[SHAP3]     Sample set 2, n_queries=500, Top similarity=0.8708
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7348644555718721
Average confidence score for samples classified same by surrogate model: 0.8597566522603557
[SHAP base] Sample set 2, n_queries=510, Top similarity=0.8342
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 8
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6985862026612857
Average confidence score for samples classified same by surrogate model: 0.8619569567751677
[SHAP3]     Sample set 3, n_queries=500, Top similarity=0.8597
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7789829245973949
Average confidence score for samples classified same by surrogate model: 0.8522803275429803
[SHAP base] Sample set 3, n_queries=510, Top similarity=0.8194
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 8
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7025553219803247
Average confidence score for samples classified same by surrogate model: 0.8660199168233853
[SHAP3]     Sample set 4, n_queries=500, Top similarity=0.835
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7636236752033722
Average confidence score for samples classified same by surrogate model: 0.8589032356349888
[SHAP base] Sample set 4, n_queries=510, Top similarity=0.7916
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 1

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6324177293888311
Average confidence score for samples classified same by surrogate model: 0.8567254911107376
[SHAP3]     Sample set 5, n_queries=500, Top similarity=0.9212
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.716514142303985
Average confidence score for samples classified same by surrogate model: 0.8575543825371313
[SHAP base] Sample set 5, n_queries=510, Top similarity=0.8688
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 5
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6849386574391904
Average confidence score for samples classified same by surrogate model: 0.8654731758821983
[SHAP3]     Sample set 6, n_queries=500, Top similarity=0.8536
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7095061340506537
Average confidence score for samples classified same by surrogate model: 0.8619545320310185
[SHAP base] Sample set 6, n_queries=510, Top similarity=0.8497
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6124835269866523
Average confidence score for samples classified same by surrogate model: 0.8532405471170043
[SHAP3]     Sample set 7, n_queries=500, Top similarity=0.941
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7155833341558857
Average confidence score for samples classified same by surrogate model: 0.860078854478091
[SHAP base] Sample set 7, n_queries=510, Top similarity=0.8544
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7351672051669873
Average confidence score for samples classified same by surrogate model: 0.8630230973762467
[SHAP3]     Sample set 8, n_queries=500, Top similarity=0.8124
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7364740107186334
Average confidence score for samples classified same by surrogate model: 0.865219768100309
[SHAP base] Sample set 8, n_queries=510, Top similarity=0.7967
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7223715065044549
Average confidence score for samples classified same by surrogate model: 0.8533660749077076
[SHAP3]     Sample set 9, n_queries=500, Top similarity=0.8907
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7909210239976882
Average confidence score for samples classified same by surrogate model: 0.8481617763399186
[SHAP base] Sample set 9, n_queries=510, Top similarity=0.8407
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 1

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6619581817505176
Average confidence score for samples classified same by surrogate model: 0.8593303977825532
[SHAP3]     Sample set 10, n_queries=500, Top similarity=0.8972
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8488947335144913
Average confidence score for samples classified same by surrogate model: 0.8375446348679079
[SHAP base] Sample set 10, n_queries=510, Top similarity=0.8679
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 5
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7796738128084891
Average confidence score for samples classified same by surrogate model: 0.8522913706760682
[SHAP3]     Sample set 11, n_queries=500, Top similarity=0.8176
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7844170217999602
Average confidence score for samples classified same by surrogate model: 0.8468546711916993
[SHAP base] Sample set 11, n_queries=510, Top similarity=0.8749
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7095803276917928
Average confidence score for samples classified same by surrogate model: 0.8643657597297826
[SHAP3]     Sample set 12, n_queries=500, Top similarity=0.8364
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7267221513495318
Average confidence score for samples classified same by surrogate model: 0.8603261024286329
[SHAP base] Sample set 12, n_queries=510, Top similarity=0.8407
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6183753220837378
Average confidence score for samples classified same by surrogate model: 0.8557115337694752
[SHAP3]     Sample set 13, n_queries=500, Top similarity=0.9298
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6985058273909757
Average confidence score for samples classified same by surrogate model: 0.8621649474063271
[SHAP base] Sample set 13, n_queries=510, Top similarity=0.8587
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7514579834403705
Average confidence score for samples classified same by surrogate model: 0.858775599897755
[SHAP3]     Sample set 14, n_queries=500, Top similarity=0.8161
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8106220364433905
Average confidence score for samples classified same by surrogate model: 0.8431380318363134
[SHAP base] Sample set 14, n_queries=510, Top similarity=0.8741
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6544749372322071
Average confidence score for samples classified same by surrogate model: 0.8624659886580978
[SHAP3]     Sample set 15, n_queries=500, Top similarity=0.8874
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8019551136615206
Average confidence score for samples classified same by surrogate model: 0.844606405208269
[SHAP base] Sample set 15, n_queries=510, Top similarity=0.8696
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6934974626696355
Average confidence score for samples classified same by surrogate model: 0.8657405454521421
[SHAP3]     Sample set 16, n_queries=500, Top similarity=0.845
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.769436184934437
Average confidence score for samples classified same by surrogate model: 0.8572590945449019
[SHAP base] Sample set 16, n_queries=510, Top similarity=0.7926
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7439463541554806
Average confidence score for samples classified same by surrogate model: 0.866107010816852
[SHAP3]     Sample set 17, n_queries=500, Top similarity=0.7785
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7803931200912444
Average confidence score for samples classified same by surrogate model: 0.8564145669586184
[SHAP base] Sample set 17, n_queries=510, Top similarity=0.7715
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7350212935251261
Average confidence score for samples classified same by surrogate model: 0.8615895079608981
[SHAP3]     Sample set 18, n_queries=500, Top similarity=0.8219
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7675569252641671
Average confidence score for samples classified same by surrogate model: 0.8583371611798478
[SHAP base] Sample set 18, n_queries=510, Top similarity=0.7875
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6160530241419467
Average confidence score for samples classified same by surrogate model: 0.8616191662868489
[SHAP3]     Sample set 19, n_queries=500, Top similarity=0.9081
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7106199492261966
Average confidence score for samples classified same by surrogate model: 0.863637997116209
[SHAP base] Sample set 19, n_queries=510, Top similarity=0.8393

=== Query limit 500 | k=3 | n=5 ===
  [SHAP3 main]    Avg similarity: 0.866  | All: [0.9208, 0.8759, 0.8708, 0.8597, 0.835, 0.9212, 0.8536, 0.941, 0.8124, 0.8907, 0.8972, 0.8176, 0.8364, 0.9298, 0.8161, 0.8874, 0.845, 0.7785, 0.8219, 0.9081]
  [SHAP baseline] Avg similarity: 0.8402  | All: [0.871, 0.9013, 0.8342, 0.8194, 0.7916, 0.8688, 0.8497, 0.8544, 0.7967, 0.8407, 0.8679, 0.8749, 0.8407, 0.8587, 0.8741, 0.8696, 0.7926, 0.7715, 0.7875, 0.8393]
  Difference (main - baseline): +0.0258


========== FINAL COMPARISON SUMMARY ==========
  [SHAP3 main]    Overall avg similarity: 0.866
  [SHAP baseline] Overall avg similarity: 0.8402
  Overall difference (main - baseline): +0.0257
===============================================

Avg Similarity: 0.8660 | Baseline: 0.8402
Dataset: 2, Model: 2... DATASET 2 2
Train results
[[16246  2260]
 [ 4655  1259]]
              precision    recall  f1-score   support

           0       0.78      0.88      0.82     18506
           1       0.36      0.21      0.27      5914

    accuracy                           0.72     24420
   macro avg       0.57      0.55      0.55     24420
weighted avg       0.68      0.72      0.69     24420

Test results
[[3233  454]
 [ 926  271]]
              precision    recall  f1-score   support

           0       0.78      0.88      0.82      3687
           1       0.37      0.23      0.28      1197

    accuracy                           0.72      4884
   macro avg       0.58      0.55      0.55      4884
weighted avg       0.68      0.72      0.69      4884

Model test accuracy:  0.7174

Dataset:   Adult Income
ML Model:  Multinomial Naive Bayes
SHAP is the explanation tool currently in use

Lower bounds:  [126]  Upper bounds:  [626] (per class for both)

-----The attack starts here!-----

Number of top features allowed to be explored (k): 3

Number of samples per class (n): 5
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8756321837925617
Average confidence score for samples classified same by surrogate model: 0.9891111596877692
[SHAP3]     Sample set 0, n_queries=500, Top similarity=0.9496
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.963027121604522
Average confidence score for samples classified same by surrogate model: 0.9905758931161116
[SHAP base] Sample set 0, n_queries=510, Top similarity=0.7394
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8600402149493996
Average confidence score for samples classified same by surrogate model: 0.9891033396349121
[SHAP3]     Sample set 1, n_queries=500, Top similarity=0.9558
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8190493758500356
Average confidence score for samples classified same by surrogate model: 0.9860626767641572
[SHAP base] Sample set 1, n_queries=510, Top similarity=0.984
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8139299102140035
Average confidence score for samples classified same by surrogate model: 0.9878831246653795
[SHAP3]     Sample set 2, n_queries=500, Top similarity=0.9742
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8698666041016587
Average confidence score for samples classified same by surrogate model: 0.9905882634555329
[SHAP base] Sample set 2, n_queries=510, Top similarity=0.9404
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7866701137771068
Average confidence score for samples classified same by surrogate model: 0.9893290971471667
[SHAP3]     Sample set 3, n_queries=500, Top similarity=0.9707
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9486066396107359
Average confidence score for samples classified same by surrogate model: 0.9912115162371147
[SHAP base] Sample set 3, n_queries=510, Top similarity=0.8165
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7541574155120107
Average confidence score for samples classified same by surrogate model: 0.9887756591172475
[SHAP3]     Sample set 4, n_queries=500, Top similarity=0.9771
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7865174277668768
Average confidence score for samples classified same by surrogate model: 0.9894621214417223
[SHAP base] Sample set 4, n_queries=510, Top similarity=0.9701
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9346025698963225
Average confidence score for samples classified same by surrogate model: 0.9886275357705445
[SHAP3]     Sample set 5, n_queries=500, Top similarity=0.9032
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.916641033839595
Average confidence score for samples classified same by surrogate model: 0.9888830605562473
[SHAP base] Sample set 5, n_queries=510, Top similarity=0.924
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7164864441256511
Average confidence score for samples classified same by surrogate model: 0.9889176421894273
[SHAP3]     Sample set 6, n_queries=500, Top similarity=0.9797
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8515755701054158
Average confidence score for samples classified same by surrogate model: 0.9903871249674244
[SHAP base] Sample set 6, n_queries=510, Top similarity=0.9496
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8734253618420402
Average confidence score for samples classified same by surrogate model: 0.9891284227227638
[SHAP3]     Sample set 7, n_queries=500, Top similarity=0.9505
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9412783874741104
Average confidence score for samples classified same by surrogate model: 0.9906304583525349
[SHAP base] Sample set 7, n_queries=510, Top similarity=0.8534
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9334774719958103
Average confidence score for samples classified same by surrogate model: 0.9886481220562977
[SHAP3]     Sample set 8, n_queries=500, Top similarity=0.9048
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8787900373812431
Average confidence score for samples classified same by surrogate model: 0.9891101698094126
[SHAP base] Sample set 8, n_queries=510, Top similarity=0.9482
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7509291295635241
Average confidence score for samples classified same by surrogate model: 0.9866287781117057
[SHAP3]     Sample set 9, n_queries=500, Top similarity=0.9863
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9119578835934228
Average confidence score for samples classified same by surrogate model: 0.9909125729744038
[SHAP base] Sample set 9, n_queries=510, Top similarity=0.9048
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7384911613941191
Average confidence score for samples classified same by surrogate model: 0.9885668970403597
[SHAP3]     Sample set 10, n_queries=500, Top similarity=0.9793
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9399666539029952
Average confidence score for samples classified same by surrogate model: 0.9908313872801185
[SHAP base] Sample set 10, n_queries=510, Top similarity=0.8538
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8835736242369553
Average confidence score for samples classified same by surrogate model: 0.9890994889710584
[SHAP3]     Sample set 11, n_queries=500, Top similarity=0.9459
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8369807808798845
Average confidence score for samples classified same by surrogate model: 0.9867062712541487
[SHAP base] Sample set 11, n_queries=510, Top similarity=0.9779
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7939345488167114
Average confidence score for samples classified same by surrogate model: 0.9895225300942478
[SHAP3]     Sample set 12, n_queries=500, Top similarity=0.9687
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9331495067147019
Average confidence score for samples classified same by surrogate model: 0.9914949382530348
[SHAP base] Sample set 12, n_queries=510, Top similarity=0.8612
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9043997182872746
Average confidence score for samples classified same by surrogate model: 0.9889896879715084
[SHAP3]     Sample set 13, n_queries=500, Top similarity=0.9339
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9022065938583332
Average confidence score for samples classified same by surrogate model: 0.9906773817746065
[SHAP base] Sample set 13, n_queries=510, Top similarity=0.9177
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.826179679251438
Average confidence score for samples classified same by surrogate model: 0.988411143942082
[SHAP3]     Sample set 14, n_queries=500, Top similarity=0.9691
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8432584994539608
Average confidence score for samples classified same by surrogate model: 0.9897543394607453
[SHAP base] Sample set 14, n_queries=510, Top similarity=0.9566
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7097954419326745
Average confidence score for samples classified same by surrogate model: 0.9861681694291917
[SHAP3]     Sample set 15, n_queries=500, Top similarity=0.99
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7704532468063531
Average confidence score for samples classified same by surrogate model: 0.9899571341939888
[SHAP base] Sample set 15, n_queries=510, Top similarity=0.9701
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9126760096138185
Average confidence score for samples classified same by surrogate model: 0.988921803187979
[SHAP3]     Sample set 16, n_queries=500, Top similarity=0.9275
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8097389044732345
Average confidence score for samples classified same by surrogate model: 0.9865448803743322
[SHAP base] Sample set 16, n_queries=510, Top similarity=0.9822
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9138638136932189
Average confidence score for samples classified same by surrogate model: 0.9889118158517057
[SHAP3]     Sample set 17, n_queries=500, Top similarity=0.9265
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8366939137208873
Average confidence score for samples classified same by surrogate model: 0.988460488860058
[SHAP base] Sample set 17, n_queries=510, Top similarity=0.9666
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6961341334381919
Average confidence score for samples classified same by surrogate model: 0.9867273331342798
[SHAP3]     Sample set 18, n_queries=500, Top similarity=0.9885
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7478297800084381
Average confidence score for samples classified same by surrogate model: 0.9866223143138824
[SHAP base] Sample set 18, n_queries=510, Top similarity=0.9865
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8383126381646518
Average confidence score for samples classified same by surrogate model: 0.988595597029695
[SHAP3]     Sample set 19, n_queries=500, Top similarity=0.9654
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8379383782737976
Average confidence score for samples classified same by surrogate model: 0.9902239166136935
[SHAP base] Sample set 19, n_queries=510, Top similarity=0.9552

=== Query limit 500 | k=3 | n=5 ===
  [SHAP3 main]    Avg similarity: 0.9573  | All: [0.9496, 0.9558, 0.9742, 0.9707, 0.9771, 0.9032, 0.9797, 0.9505, 0.9048, 0.9863, 0.9793, 0.9459, 0.9687, 0.9339, 0.9691, 0.99, 0.9275, 0.9265, 0.9885, 0.9654]
  [SHAP baseline] Avg similarity: 0.9229  | All: [0.7394, 0.984, 0.9404, 0.8165, 0.9701, 0.924, 0.9496, 0.8534, 0.9482, 0.9048, 0.8538, 0.9779, 0.8612, 0.9177, 0.9566, 0.9701, 0.9822, 0.9666, 0.9865, 0.9552]
  Difference (main - baseline): +0.0344


========== FINAL COMPARISON SUMMARY ==========
  [SHAP3 main]    Overall avg similarity: 0.9573
  [SHAP baseline] Overall avg similarity: 0.9229
  Overall difference (main - baseline): +0.0344
===============================================

Avg Similarity: 0.9573 | Baseline: 0.9229
Dataset: 2, Model: 3... DATASET 2 3
Train results
[[18452    54]
 [ 2168  3746]]
              precision    recall  f1-score   support

           0       0.89      1.00      0.94     18506
           1       0.99      0.63      0.77      5914

    accuracy                           0.91     24420
   macro avg       0.94      0.82      0.86     24420
weighted avg       0.92      0.91      0.90     24420

Test results
[[3503  184]
 [ 574  623]]
              precision    recall  f1-score   support

           0       0.86      0.95      0.90      3687
           1       0.77      0.52      0.62      1197

    accuracy                           0.84      4884
   macro avg       0.82      0.74      0.76      4884
weighted avg       0.84      0.84      0.83      4884

Model test accuracy:  0.8448

Dataset:   Adult Income
ML Model:  K Nearest Neighbor
SHAP is the explanation tool currently in use

Lower bounds:  [126]  Upper bounds:  [626] (per class for both)

-----The attack starts here!-----

Number of top features allowed to be explored (k): 3

Number of samples per class (n): 5
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9596518987341772
Average confidence score for samples classified same by surrogate model: 0.9006349952963312
[SHAP3]     Sample set 0, n_queries=500, Top similarity=0.8706
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9962406015037594
Average confidence score for samples classified same by surrogate model: 0.891091532060695
[SHAP base] Sample set 0, n_queries=510, Top similarity=0.8366
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9651851851851851
Average confidence score for samples classified same by surrogate model: 0.8991446899501069
[SHAP3]     Sample set 1, n_queries=500, Top similarity=0.8618
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9750712250712251
Average confidence score for samples classified same by surrogate model: 0.8970588235294118
[SHAP base] Sample set 1, n_queries=510, Top similarity=0.8563
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9863013698630136
Average confidence score for samples classified same by surrogate model: 0.8976744186046511
[SHAP3]     Sample set 2, n_queries=500, Top similarity=0.8804
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9922178988326849
Average confidence score for samples classified same by surrogate model: 0.8925358619012886
[SHAP base] Sample set 2, n_queries=510, Top similarity=0.8421
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 8
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9311926605504587
Average confidence score for samples classified same by surrogate model: 0.9047281323877069
[SHAP3]     Sample set 3, n_queries=500, Top similarity=0.8661
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9328125
Average confidence score for samples classified same by surrogate model: 0.9045711592836946
[SHAP base] Sample set 3, n_queries=510, Top similarity=0.869
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 2
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.984251968503937
Average confidence score for samples classified same by surrogate model: 0.8969169216286185
[SHAP3]     Sample set 4, n_queries=500, Top similarity=0.87
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.982089552238806
Average confidence score for samples classified same by surrogate model: 0.8965353583293783
[SHAP base] Sample set 4, n_queries=510, Top similarity=0.8628
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9524590163934427
Average confidence score for samples classified same by surrogate model: 0.901965372016846
[SHAP3]     Sample set 5, n_queries=500, Top similarity=0.8751
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9553429027113237
Average confidence score for samples classified same by surrogate model: 0.9013389711064129
[SHAP base] Sample set 5, n_queries=510, Top similarity=0.8716
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9744224422442245
Average confidence score for samples classified same by surrogate model: 0.898901355773726
[SHAP3]     Sample set 6, n_queries=500, Top similarity=0.8759
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9859504132231405
Average confidence score for samples classified same by surrogate model: 0.8972890862351016
[SHAP base] Sample set 6, n_queries=510, Top similarity=0.8761
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9561128526645768
Average confidence score for samples classified same by surrogate model: 0.9010833725859633
[SHAP3]     Sample set 7, n_queries=500, Top similarity=0.8694
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9592457420924574
Average confidence score for samples classified same by surrogate model: 0.8979566715903495
[SHAP base] Sample set 7, n_queries=510, Top similarity=0.8317
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9824561403508771
Average confidence score for samples classified same by surrogate model: 0.8984700973574409
[SHAP3]     Sample set 8, n_queries=500, Top similarity=0.8833
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9486531986531986
Average confidence score for samples classified same by surrogate model: 0.9026806526806527
[SHAP base] Sample set 8, n_queries=510, Top similarity=0.8784
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 8
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9526578073089701
Average confidence score for samples classified same by surrogate model: 0.9020317608594115
[SHAP3]     Sample set 9, n_queries=500, Top similarity=0.8767
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9708265802269044
Average confidence score for samples classified same by surrogate model: 0.8992266229200844
[SHAP base] Sample set 9, n_queries=510, Top similarity=0.8737
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.956997084548105
Average confidence score for samples classified same by surrogate model: 0.9003096712720343
[SHAP3]     Sample set 10, n_queries=500, Top similarity=0.8595
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.964200477326969
Average confidence score for samples classified same by surrogate model: 0.8966880869995056
[SHAP base] Sample set 10, n_queries=510, Top similarity=0.8284
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.969311377245509
Average confidence score for samples classified same by surrogate model: 0.898600569259962
[SHAP3]     Sample set 11, n_queries=500, Top similarity=0.8632
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9537815126050421
Average confidence score for samples classified same by surrogate model: 0.9004796163069544
[SHAP base] Sample set 11, n_queries=510, Top similarity=0.8538
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9588709677419355
Average confidence score for samples classified same by surrogate model: 0.9009146341463414
[SHAP3]     Sample set 12, n_queries=500, Top similarity=0.8731
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9537313432835821
Average confidence score for samples classified same by surrogate model: 0.9010441385856668
[SHAP base] Sample set 12, n_queries=510, Top similarity=0.8628
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9273858921161826
Average confidence score for samples classified same by surrogate model: 0.9049507329968758
[SHAP3]     Sample set 13, n_queries=500, Top similarity=0.852
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9403927068723703
Average confidence score for samples classified same by surrogate model: 0.902781107648046
[SHAP base] Sample set 13, n_queries=510, Top similarity=0.854
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9788732394366197
Average confidence score for samples classified same by surrogate model: 0.8976442873969376
[SHAP3]     Sample set 14, n_queries=500, Top similarity=0.8692
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.973604826546003
Average confidence score for samples classified same by surrogate model: 0.8980099502487562
[SHAP base] Sample set 14, n_queries=510, Top similarity=0.8643
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9144654088050315
Average confidence score for samples classified same by surrogate model: 0.9070677427243825
[SHAP3]     Sample set 15, n_queries=500, Top similarity=0.8372
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9631901840490797
Average confidence score for samples classified same by surrogate model: 0.8998109640831758
[SHAP base] Sample set 15, n_queries=510, Top similarity=0.8665
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9720767888307156
Average confidence score for samples classified same by surrogate model: 0.8997912317327766
[SHAP3]     Sample set 16, n_queries=500, Top similarity=0.8827
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9432348367029549
Average confidence score for samples classified same by surrogate model: 0.9029709974062721
[SHAP base] Sample set 16, n_queries=510, Top similarity=0.8683
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.967828418230563
Average confidence score for samples classified same by surrogate model: 0.8975350410826486
[SHAP3]     Sample set 17, n_queries=500, Top similarity=0.8473
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9696531791907514
Average confidence score for samples classified same by surrogate model: 0.8981393129770993
[SHAP base] Sample set 17, n_queries=510, Top similarity=0.8583
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9402748414376322
Average confidence score for samples classified same by surrogate model: 0.9005840528186897
[SHAP3]     Sample set 18, n_queries=500, Top similarity=0.8063
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9422843256379101
Average confidence score for samples classified same by surrogate model: 0.9013789706968727
[SHAP base] Sample set 18, n_queries=510, Top similarity=0.8315
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9616639477977161
Average confidence score for samples classified same by surrogate model: 0.9006087567314446
[SHAP3]     Sample set 19, n_queries=500, Top similarity=0.8745
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9657228017883756
Average confidence score for samples classified same by surrogate model: 0.899121765962497
[SHAP base] Sample set 19, n_queries=510, Top similarity=0.8626

=== Query limit 500 | k=3 | n=5 ===
  [SHAP3 main]    Avg similarity: 0.8647  | All: [0.8706, 0.8618, 0.8804, 0.8661, 0.87, 0.8751, 0.8759, 0.8694, 0.8833, 0.8767, 0.8595, 0.8632, 0.8731, 0.852, 0.8692, 0.8372, 0.8827, 0.8473, 0.8063, 0.8745]
  [SHAP baseline] Avg similarity: 0.8574  | All: [0.8366, 0.8563, 0.8421, 0.869, 0.8628, 0.8716, 0.8761, 0.8317, 0.8784, 0.8737, 0.8284, 0.8538, 0.8628, 0.854, 0.8643, 0.8665, 0.8683, 0.8583, 0.8315, 0.8626]
  Difference (main - baseline): +0.0073


========== FINAL COMPARISON SUMMARY ==========
  [SHAP3 main]    Overall avg similarity: 0.8647
  [SHAP baseline] Overall avg similarity: 0.8574
  Overall difference (main - baseline): +0.0073
===============================================

Avg Similarity: 0.8647 | Baseline: 0.8574
Dataset: 2, Model: 4... DATASET 2 4
Train results
[[17890   616]
 [ 1616  4298]]
              precision    recall  f1-score   support

           0       0.92      0.97      0.94     18506
           1       0.87      0.73      0.79      5914

    accuracy                           0.91     24420
   macro avg       0.90      0.85      0.87     24420
weighted avg       0.91      0.91      0.91     24420

Test results
[[3464  223]
 [ 454  743]]
              precision    recall  f1-score   support

           0       0.88      0.94      0.91      3687
           1       0.77      0.62      0.69      1197

    accuracy                           0.86      4884
   macro avg       0.83      0.78      0.80      4884
weighted avg       0.86      0.86      0.86      4884

Model test accuracy:  0.8614

Dataset:   Adult Income
ML Model:  Random Forest
SHAP is the explanation tool currently in use

Lower bounds:  [126]  Upper bounds:  [626] (per class for both)

-----The attack starts here!-----

Number of top features allowed to be explored (k): 3

Number of samples per class (n): 5
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 8
Diverse samples left to process: 6
Diverse samples left to process: 4
Diverse samples left to process: 2
Error: unhashable type: 'numpy.ndarray'
Dataset: 2, Model: 5... DATASET 2 5
Train results
[[9329 9177]
 [ 825 5089]]
              precision    recall  f1-score   support

           0       0.92      0.50      0.65     18506
           1       0.36      0.86      0.50      5914

    accuracy                           0.59     24420
   macro avg       0.64      0.68      0.58     24420
weighted avg       0.78      0.59      0.62     24420

Test results
[[1837 1850]
 [ 156 1041]]
              precision    recall  f1-score   support

           0       0.92      0.50      0.65      3687
           1       0.36      0.87      0.51      1197

    accuracy                           0.59      4884
   macro avg       0.64      0.68      0.58      4884
weighted avg       0.78      0.59      0.61      4884

Model test accuracy:  0.5893

Dataset:   Adult Income
ML Model:  Multilayer Perceptron
SHAP is the explanation tool currently in use

Lower bounds:  [126]  Upper bounds:  [626] (per class for both)

-----The attack starts here!-----

Number of top features allowed to be explored (k): 3

Number of samples per class (n): 5
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.7025503736711315
Average confidence score for samples classified same by surrogate model: 0.8507809635669878
Average confidence score for samples classified differently by surrogate model: 0.7995078853713805
Average confidence score for samples classified same by surrogate model: 0.8774402488650486
Average confidence score for samples classified differently by surrogate model: 0.7849401126688752
Average confidence score for samples classified same by surrogate model: 0.8449844462634314
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.773632746409068
Average confidence score for samples classified same by surrogate model: 0.8464607839035958
Average confidence score for samples classified differently by surrogate model: 0.8067532817256855
Average confidence score for samples classified same by surrogate model: 0.8523424226695939
Average confidence score for samples classified differently by surrogate model: 0.8095427095046198
Average confidence score for samples classified same by surrogate model: 0.8580647975676827
Average confidence score for samples classified differently by surrogate model: 0.8434301310697044
Average confidence score for samples classified same by surrogate model: 0.8223694087690464
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.7942912563442553
Average confidence score for samples classified same by surrogate model: 0.8746707571441243
Average confidence score for samples classified differently by surrogate model: 0.8491184127971598
Average confidence score for samples classified same by surrogate model: 0.8177506834495383
Average confidence score for samples classified differently by surrogate model: 0.7121332821269494
Average confidence score for samples classified same by surrogate model: 0.8502051153805414
Average confidence score for samples classified differently by surrogate model: 0.7184638947310312
Average confidence score for samples classified same by surrogate model: 0.8505029766857984
Average confidence score for samples classified differently by surrogate model: 0.7835570054422205
Average confidence score for samples classified same by surrogate model: 0.8725379874255998
Average confidence score for samples classified differently by surrogate model: 0.6295472358257154
Average confidence score for samples classified same by surrogate model: 0.8447353912256393
[SHAP3]     Sample set 0, n_queries=500, Top similarity=0.9335
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8361713459677589
Average confidence score for samples classified same by surrogate model: 0.8265744345763361
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503419177612985
Average confidence score for samples classified same by surrogate model: 0.8167026415410682
Average confidence score for samples classified differently by surrogate model: 0.7229933986851581
Average confidence score for samples classified same by surrogate model: 0.8637639221793193
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.7935305179557923
Average confidence score for samples classified same by surrogate model: 0.8783461726379801
Average confidence score for samples classified differently by surrogate model: 0.8481214290167661
Average confidence score for samples classified same by surrogate model: 0.8185578190759691
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.7873566693305896
Average confidence score for samples classified same by surrogate model: 0.8708759414634165
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.727285282225384
Average confidence score for samples classified same by surrogate model: 0.8551578848789182
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8201932227178339
Average confidence score for samples classified same by surrogate model: 0.8349298816573714
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8497771612432373
Average confidence score for samples classified same by surrogate model: 0.8171702111498181
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.7876101469006329
Average confidence score for samples classified same by surrogate model: 0.8748289799329095
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.7040093127527863
Average confidence score for samples classified same by surrogate model: 0.850827390459431
[SHAP base] Sample set 0, n_queries=510, Top similarity=0.861
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8284379269637118
Average confidence score for samples classified same by surrogate model: 0.8319179935884553
Average confidence score for samples classified differently by surrogate model: 0.7273929497077432
Average confidence score for samples classified same by surrogate model: 0.8709491077301216
Average confidence score for samples classified differently by surrogate model: 0.8458278316533748
Average confidence score for samples classified same by surrogate model: 0.8203982270743114
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.846824503359733
Average confidence score for samples classified same by surrogate model: 0.8200220370828486
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.7957115066139385
Average confidence score for samples classified same by surrogate model: 0.8542191013459297
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.8496595539977934
Average confidence score for samples classified same by surrogate model: 0.8173509388433873
Average confidence score for samples classified differently by surrogate model: 0.8010650948709084
Average confidence score for samples classified same by surrogate model: 0.8417431813895048
Average confidence score for samples classified differently by surrogate model: 0.8194188889997709
Average confidence score for samples classified same by surrogate model: 0.8376564599220694
Average confidence score for samples classified differently by surrogate model: 0.7221512595215305
Average confidence score for samples classified same by surrogate model: 0.8521647212225124
Average confidence score for samples classified differently by surrogate model: 0.8239624557265263
Average confidence score for samples classified same by surrogate model: 0.8353042572640231
Average confidence score for samples classified differently by surrogate model: 0.8188777576629824
Average confidence score for samples classified same by surrogate model: 0.835456907946903
Average confidence score for samples classified differently by surrogate model: 0.798931443255636
Average confidence score for samples classified same by surrogate model: 0.8708876114262165
Average confidence score for samples classified differently by surrogate model: 0.8483356784421041
Average confidence score for samples classified same by surrogate model: 0.8187880912475798
Average confidence score for samples classified differently by surrogate model: 0.8502326697839874
Average confidence score for samples classified same by surrogate model: 0.8176232159484285
Average confidence score for samples classified differently by surrogate model: 0.8487016272320097
Average confidence score for samples classified same by surrogate model: 0.818252514664645
Average confidence score for samples classified differently by surrogate model: 0.8212623703803039
Average confidence score for samples classified same by surrogate model: 0.8353430265389331
Average confidence score for samples classified differently by surrogate model: 0.8405420384934958
Average confidence score for samples classified same by surrogate model: 0.8246908154931173
[SHAP3]     Sample set 1, n_queries=500, Top similarity=0.8327
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8151058636608014
Average confidence score for samples classified same by surrogate model: 0.8422965771596026
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.7495464013687869
Average confidence score for samples classified same by surrogate model: 0.8621688353453754
Average confidence score for samples classified differently by surrogate model: 0.8060763547139368
Average confidence score for samples classified same by surrogate model: 0.8659929796222995
Average confidence score for samples classified differently by surrogate model: 0.8419362239470658
Average confidence score for samples classified same by surrogate model: 0.8234462411943818
Average confidence score for samples classified differently by surrogate model: 0.7557489279264459
Average confidence score for samples classified same by surrogate model: 0.8710061138456285
Average confidence score for samples classified differently by surrogate model: 0.7471827118525092
Average confidence score for samples classified same by surrogate model: 0.8684207481046406
Average confidence score for samples classified differently by surrogate model: 0.7948728512590926
Average confidence score for samples classified same by surrogate model: 0.8638957119714774
Average confidence score for samples classified differently by surrogate model: 0.7639998913903948
Average confidence score for samples classified same by surrogate model: 0.852699927127436
Average confidence score for samples classified differently by surrogate model: 0.8431443578322009
Average confidence score for samples classified same by surrogate model: 0.822121177780995
Average confidence score for samples classified differently by surrogate model: 0.8333468233044231
Average confidence score for samples classified same by surrogate model: 0.8286489615460544
Average confidence score for samples classified differently by surrogate model: 0.8167197351540207
Average confidence score for samples classified same by surrogate model: 0.8503002139435882
Average confidence score for samples classified differently by surrogate model: 0.764733725983274
Average confidence score for samples classified same by surrogate model: 0.869362552643008
Average confidence score for samples classified differently by surrogate model: 0.8264590078886794
Average confidence score for samples classified same by surrogate model: 0.8334763302244623
Average confidence score for samples classified differently by surrogate model: 0.8090903005559638
Average confidence score for samples classified same by surrogate model: 0.839140638791891
Average confidence score for samples classified differently by surrogate model: 0.783593207058424
Average confidence score for samples classified same by surrogate model: 0.8494958805361502
Average confidence score for samples classified differently by surrogate model: 0.8287418777108914
Average confidence score for samples classified same by surrogate model: 0.8312599465439867
[SHAP base] Sample set 1, n_queries=510, Top similarity=0.7488
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8489456896014445
Average confidence score for samples classified same by surrogate model: 0.818535996129536
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.8089570780355375
Average confidence score for samples classified same by surrogate model: 0.8424839913802233
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8334988128133568
Average confidence score for samples classified same by surrogate model: 0.8282008882745177
Average confidence score for samples classified differently by surrogate model: 0.7762751917765189
Average confidence score for samples classified same by surrogate model: 0.8595581724393644
Average confidence score for samples classified differently by surrogate model: 0.8154762524441808
Average confidence score for samples classified same by surrogate model: 0.8390744035773229
Average confidence score for samples classified differently by surrogate model: 0.8501119686785045
Average confidence score for samples classified same by surrogate model: 0.8168953406450926
Average confidence score for samples classified differently by surrogate model: 0.840151285957115
Average confidence score for samples classified same by surrogate model: 0.8242064903925618
Average confidence score for samples classified differently by surrogate model: 0.8187066335872906
Average confidence score for samples classified same by surrogate model: 0.8352877590731483
Average confidence score for samples classified differently by surrogate model: 0.8337163606170988
Average confidence score for samples classified same by surrogate model: 0.8282466609181306
Average confidence score for samples classified differently by surrogate model: 0.7348108399333196
Average confidence score for samples classified same by surrogate model: 0.8558098961672445
Average confidence score for samples classified differently by surrogate model: 0.849272802207398
Average confidence score for samples classified same by surrogate model: 0.8178832774153472
Average confidence score for samples classified differently by surrogate model: 0.767379395384451
Average confidence score for samples classified same by surrogate model: 0.8724905367922344
Average confidence score for samples classified differently by surrogate model: 0.8229494578596984
Average confidence score for samples classified same by surrogate model: 0.8375769540708057
Average confidence score for samples classified differently by surrogate model: 0.8487324677216151
Average confidence score for samples classified same by surrogate model: 0.8182631652313858
Average confidence score for samples classified differently by surrogate model: 0.8439710326045973
Average confidence score for samples classified same by surrogate model: 0.8218443537945026
Average confidence score for samples classified differently by surrogate model: 0.8493109071512501
Average confidence score for samples classified same by surrogate model: 0.8183849787713403
Average confidence score for samples classified differently by surrogate model: 0.8197383719631915
Average confidence score for samples classified same by surrogate model: 0.8353988198829586
Average confidence score for samples classified differently by surrogate model: 0.7662608633227104
Average confidence score for samples classified same by surrogate model: 0.8675649188587377
[SHAP3]     Sample set 2, n_queries=500, Top similarity=0.7901
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.7187784758810455
Average confidence score for samples classified same by surrogate model: 0.8656239981105164
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.816287061076403
Average confidence score for samples classified same by surrogate model: 0.8381380724582587
Average confidence score for samples classified differently by surrogate model: 0.8334472348825214
Average confidence score for samples classified same by surrogate model: 0.8282616674831583
Average confidence score for samples classified differently by surrogate model: 0.8233879772117765
Average confidence score for samples classified same by surrogate model: 0.8376128506219471
Average confidence score for samples classified differently by surrogate model: 0.8225344707372212
Average confidence score for samples classified same by surrogate model: 0.8350079461618694
Average confidence score for samples classified differently by surrogate model: 0.8443733144462613
Average confidence score for samples classified same by surrogate model: 0.8215899696887456
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.7899366339899244
Average confidence score for samples classified same by surrogate model: 0.84719147900419
Average confidence score for samples classified differently by surrogate model: 0.6816771638334563
Average confidence score for samples classified same by surrogate model: 0.8598135620871217
Average confidence score for samples classified differently by surrogate model: 0.7809873767953077
Average confidence score for samples classified same by surrogate model: 0.8509002502308036
Average confidence score for samples classified differently by surrogate model: 0.815096904883472
Average confidence score for samples classified same by surrogate model: 0.8375850974864706
Average confidence score for samples classified differently by surrogate model: 0.829001593227864
Average confidence score for samples classified same by surrogate model: 0.831188272213672
Average confidence score for samples classified differently by surrogate model: 0.7008837020041657
Average confidence score for samples classified same by surrogate model: 0.8557895540249053
Average confidence score for samples classified differently by surrogate model: 0.7775326768694503
Average confidence score for samples classified same by surrogate model: 0.8730864713240064
Average confidence score for samples classified differently by surrogate model: 0.6758148115980123
Average confidence score for samples classified same by surrogate model: 0.8491952847085416
Average confidence score for samples classified differently by surrogate model: 0.8027476975606814
Average confidence score for samples classified same by surrogate model: 0.8423177547655658
[SHAP base] Sample set 2, n_queries=510, Top similarity=0.8917
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8317082281024808
Average confidence score for samples classified same by surrogate model: 0.8296190239278816
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8167197351540207
Average confidence score for samples classified same by surrogate model: 0.8503002139435882
Average confidence score for samples classified differently by surrogate model: 0.8253218741282972
Average confidence score for samples classified same by surrogate model: 0.8343133692488076
Average confidence score for samples classified differently by surrogate model: 0.8026060872136662
Average confidence score for samples classified same by surrogate model: 0.8414127644392386
Average confidence score for samples classified differently by surrogate model: 0.8489823974786076
Average confidence score for samples classified same by surrogate model: 0.818766293165223
Average confidence score for samples classified differently by surrogate model: 0.8167197351540207
Average confidence score for samples classified same by surrogate model: 0.8503002139435882
Average confidence score for samples classified differently by surrogate model: 0.8447254158117031
Average confidence score for samples classified same by surrogate model: 0.8213125412444319
Average confidence score for samples classified differently by surrogate model: 0.776680530615681
Average confidence score for samples classified same by surrogate model: 0.8461101043495602
Average confidence score for samples classified differently by surrogate model: 0.8226878523760238
Average confidence score for samples classified same by surrogate model: 0.8354263030127251
Average confidence score for samples classified differently by surrogate model: 0.7459080017410408
Average confidence score for samples classified same by surrogate model: 0.8659594327293512
Average confidence score for samples classified differently by surrogate model: 0.840780198893654
Average confidence score for samples classified same by surrogate model: 0.8238394388014332
Average confidence score for samples classified differently by surrogate model: 0.7243407694764062
Average confidence score for samples classified same by surrogate model: 0.8569754807202054
Average confidence score for samples classified differently by surrogate model: 0.8313629857052874
Average confidence score for samples classified same by surrogate model: 0.8298852470651691
Average confidence score for samples classified differently by surrogate model: 0.767321349142466
Average confidence score for samples classified same by surrogate model: 0.8465586931972989
Average confidence score for samples classified differently by surrogate model: 0.807857329381997
Average confidence score for samples classified same by surrogate model: 0.8443879340038069
Average confidence score for samples classified differently by surrogate model: 0.8169235130612922
Average confidence score for samples classified same by surrogate model: 0.8364891491805626
Average confidence score for samples classified differently by surrogate model: 0.8290656926452539
Average confidence score for samples classified same by surrogate model: 0.8310998250825242
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
[SHAP3]     Sample set 3, n_queries=500, Top similarity=0.7998
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.6675618306543799
Average confidence score for samples classified same by surrogate model: 0.8544461162100796
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8311583708381047
Average confidence score for samples classified same by surrogate model: 0.8299852932152475
Average confidence score for samples classified differently by surrogate model: 0.8485311466205243
Average confidence score for samples classified same by surrogate model: 0.8187015377690121
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8495251141154352
Average confidence score for samples classified same by surrogate model: 0.8183946414340707
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8452119298704935
Average confidence score for samples classified same by surrogate model: 0.8213940111999469
Average confidence score for samples classified differently by surrogate model: 0.7365920472703612
Average confidence score for samples classified same by surrogate model: 0.8550604912653467
Average confidence score for samples classified differently by surrogate model: 0.8216538496034942
Average confidence score for samples classified same by surrogate model: 0.8356525734430711
Average confidence score for samples classified differently by surrogate model: 0.7439501843719956
Average confidence score for samples classified same by surrogate model: 0.8510510719622114
Average confidence score for samples classified differently by surrogate model: 0.8470180578235376
Average confidence score for samples classified same by surrogate model: 0.820239757239289
Average confidence score for samples classified differently by surrogate model: 0.7989499730763749
Average confidence score for samples classified same by surrogate model: 0.853407744775892
Average confidence score for samples classified differently by surrogate model: 0.807366408351442
Average confidence score for samples classified same by surrogate model: 0.8401199614071906
Average confidence score for samples classified differently by surrogate model: 0.7331827725842947
Average confidence score for samples classified same by surrogate model: 0.8642583560618973
Average confidence score for samples classified differently by surrogate model: 0.7504200143621935
Average confidence score for samples classified same by surrogate model: 0.860383467808885
[SHAP base] Sample set 3, n_queries=510, Top similarity=0.8714
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.7326183532221683
Average confidence score for samples classified same by surrogate model: 0.8595836544194
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.6658462854799734
Average confidence score for samples classified same by surrogate model: 0.8592899056861972
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.6648794656280552
Average confidence score for samples classified same by surrogate model: 0.8491274579055451
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.7534262469781595
Average confidence score for samples classified same by surrogate model: 0.8706752990516626
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.6525689788386108
Average confidence score for samples classified same by surrogate model: 0.8453352033377833
[SHAP3]     Sample set 4, n_queries=500, Top similarity=0.9226
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8128405820261345
Average confidence score for samples classified same by surrogate model: 0.8424808091067343
Average confidence score for samples classified differently by surrogate model: 0.7079865101890502
Average confidence score for samples classified same by surrogate model: 0.8524875697535085
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8214439167156012
Average confidence score for samples classified same by surrogate model: 0.8344428520469734
Average confidence score for samples classified differently by surrogate model: 0.7421443307995697
Average confidence score for samples classified same by surrogate model: 0.8503025316565569
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.720659817227354
Average confidence score for samples classified same by surrogate model: 0.8509268774710113
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.6637288004772686
Average confidence score for samples classified same by surrogate model: 0.8579320539863492
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8502686522475634
Average confidence score for samples classified same by surrogate model: 0.8167646448750535
Average confidence score for samples classified differently by surrogate model: 0.659678601661274
Average confidence score for samples classified same by surrogate model: 0.8554713252413126
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.7698741130634484
Average confidence score for samples classified same by surrogate model: 0.8475636380343278
[SHAP base] Sample set 4, n_queries=510, Top similarity=0.872
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8502081698977142
Average confidence score for samples classified same by surrogate model: 0.8168408238364853
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.7363595499894922
Average confidence score for samples classified same by surrogate model: 0.8513173723349292
Average confidence score for samples classified differently by surrogate model: 0.8492650912455966
Average confidence score for samples classified same by surrogate model: 0.8176513531266272
Average confidence score for samples classified differently by surrogate model: 0.8167197351540207
Average confidence score for samples classified same by surrogate model: 0.8503002139435882
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8460690326777327
Average confidence score for samples classified same by surrogate model: 0.8204233918333875
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8308990218877276
Average confidence score for samples classified same by surrogate model: 0.8300786732581709
Average confidence score for samples classified differently by surrogate model: 0.8316399396600626
Average confidence score for samples classified same by surrogate model: 0.8297653817865305
Average confidence score for samples classified differently by surrogate model: 0.8082694276598174
Average confidence score for samples classified same by surrogate model: 0.8480062445409733
Average confidence score for samples classified differently by surrogate model: 0.8266528080430628
Average confidence score for samples classified same by surrogate model: 0.8322802378528404
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8486340661819538
Average confidence score for samples classified same by surrogate model: 0.8191616319349809
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.696018398811009
Average confidence score for samples classified same by surrogate model: 0.8586943939654279
[SHAP3]     Sample set 5, n_queries=500, Top similarity=0.8262
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.7123844950354306
Average confidence score for samples classified same by surrogate model: 0.8557839046095617
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.8413542715036424
Average confidence score for samples classified same by surrogate model: 0.8232079529633115
Average confidence score for samples classified differently by surrogate model: 0.8202668399501261
Average confidence score for samples classified same by surrogate model: 0.8350500949231769
Average confidence score for samples classified differently by surrogate model: 0.8503419177612985
Average confidence score for samples classified same by surrogate model: 0.8167026415410682
Average confidence score for samples classified differently by surrogate model: 0.7998895645153791
Average confidence score for samples classified same by surrogate model: 0.8653664495166727
Average confidence score for samples classified differently by surrogate model: 0.812802167012193
Average confidence score for samples classified same by surrogate model: 0.844569418324418
Average confidence score for samples classified differently by surrogate model: 0.7063330274069497
Average confidence score for samples classified same by surrogate model: 0.8586378764608601
Average confidence score for samples classified differently by surrogate model: 0.8503147345280389
Average confidence score for samples classified same by surrogate model: 0.8167097334236523
Average confidence score for samples classified differently by surrogate model: 0.8500167312527066
Average confidence score for samples classified same by surrogate model: 0.8169607177177746
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.7931078772186838
Average confidence score for samples classified same by surrogate model: 0.8693474704843764
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8397871205949908
Average confidence score for samples classified same by surrogate model: 0.8249608177945755
Average confidence score for samples classified differently by surrogate model: 0.8465219225169712
Average confidence score for samples classified same by surrogate model: 0.8204664176041404
Average confidence score for samples classified differently by surrogate model: 0.8311780981975007
Average confidence score for samples classified same by surrogate model: 0.829996780725098
[SHAP base] Sample set 5, n_queries=510, Top similarity=0.8231
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.7155413681427538
Average confidence score for samples classified same by surrogate model: 0.8560843186016306
Average confidence score for samples classified differently by surrogate model: 0.7991186735762305
Average confidence score for samples classified same by surrogate model: 0.85617574654926
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8497023997985309
Average confidence score for samples classified same by surrogate model: 0.8180933325586078
Average confidence score for samples classified differently by surrogate model: 0.6869954186246875
Average confidence score for samples classified same by surrogate model: 0.8483559059958167
Average confidence score for samples classified differently by surrogate model: 0.8499133149647509
Average confidence score for samples classified same by surrogate model: 0.8181079943078404
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8296032155022683
Average confidence score for samples classified same by surrogate model: 0.8309334419526603
Average confidence score for samples classified differently by surrogate model: 0.7391205163723821
Average confidence score for samples classified same by surrogate model: 0.854010209306763
Average confidence score for samples classified differently by surrogate model: 0.8469926368096544
Average confidence score for samples classified same by surrogate model: 0.8200596567905922
Average confidence score for samples classified differently by surrogate model: 0.7436823904620439
Average confidence score for samples classified same by surrogate model: 0.8524947986881992
Average confidence score for samples classified differently by surrogate model: 0.8051591353587129
Average confidence score for samples classified same by surrogate model: 0.847476213625985
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.7952478535973057
Average confidence score for samples classified same by surrogate model: 0.8491421062712332
Average confidence score for samples classified differently by surrogate model: 0.8054632387128917
Average confidence score for samples classified same by surrogate model: 0.839996829635898
Average confidence score for samples classified differently by surrogate model: 0.8488716139689453
Average confidence score for samples classified same by surrogate model: 0.8189851874492909
Average confidence score for samples classified differently by surrogate model: 0.8237095686125251
Average confidence score for samples classified same by surrogate model: 0.8334259634916352
Average confidence score for samples classified differently by surrogate model: 0.7855026159773731
Average confidence score for samples classified same by surrogate model: 0.8582095181343378
Average confidence score for samples classified differently by surrogate model: 0.6801526409889636
Average confidence score for samples classified same by surrogate model: 0.8554299282234864
[SHAP3]     Sample set 6, n_queries=500, Top similarity=0.8888
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.7678756869324326
Average confidence score for samples classified same by surrogate model: 0.8498087999321766
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.750515629271859
Average confidence score for samples classified same by surrogate model: 0.8534795255455503
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.7650230390456146
Average confidence score for samples classified same by surrogate model: 0.8487177396594159
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.7765385444505634
Average confidence score for samples classified same by surrogate model: 0.8525897725270077
Average confidence score for samples classified differently by surrogate model: 0.8426748307259299
Average confidence score for samples classified same by surrogate model: 0.8228561041372537
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.7979203361445689
Average confidence score for samples classified same by surrogate model: 0.8603794382740378
Average confidence score for samples classified differently by surrogate model: 0.7813038840950899
Average confidence score for samples classified same by surrogate model: 0.8546341593383285
Average confidence score for samples classified differently by surrogate model: 0.8493938845188689
Average confidence score for samples classified same by surrogate model: 0.8183321446565694
Average confidence score for samples classified differently by surrogate model: 0.8325542366462217
Average confidence score for samples classified same by surrogate model: 0.8293289767515046
Average confidence score for samples classified differently by surrogate model: 0.849734311162658
Average confidence score for samples classified same by surrogate model: 0.8179449326325477
Average confidence score for samples classified differently by surrogate model: 0.7593016103724327
Average confidence score for samples classified same by surrogate model: 0.8587924253773279
Average confidence score for samples classified differently by surrogate model: 0.8477079912392403
Average confidence score for samples classified same by surrogate model: 0.8193390530560372
Average confidence score for samples classified differently by surrogate model: 0.7267723824807996
Average confidence score for samples classified same by surrogate model: 0.8618658397011951
[SHAP base] Sample set 6, n_queries=510, Top similarity=0.7813
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8062077410042479
Average confidence score for samples classified same by surrogate model: 0.8429146311552281
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.7920024192489334
Average confidence score for samples classified same by surrogate model: 0.8722126307193341
Average confidence score for samples classified differently by surrogate model: 0.8167197351540207
Average confidence score for samples classified same by surrogate model: 0.8503002139435882
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.7024913619796501
Average confidence score for samples classified same by surrogate model: 0.8639759027737673
Average confidence score for samples classified differently by surrogate model: 0.8501996469251742
Average confidence score for samples classified same by surrogate model: 0.816881172669486
Average confidence score for samples classified differently by surrogate model: 0.6994538472450859
Average confidence score for samples classified same by surrogate model: 0.8650724154211733
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8502686522475634
Average confidence score for samples classified same by surrogate model: 0.8167646448750535
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.690626898361717
Average confidence score for samples classified same by surrogate model: 0.8604601641931655
[SHAP3]     Sample set 7, n_queries=500, Top similarity=0.8231
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8173440228205937
Average confidence score for samples classified same by surrogate model: 0.8426887202343597
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.7469607476323181
Average confidence score for samples classified same by surrogate model: 0.8544489356082693
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.6982345645347386
Average confidence score for samples classified same by surrogate model: 0.8578720242413126
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8503147345280389
Average confidence score for samples classified same by surrogate model: 0.8167097334236523
Average confidence score for samples classified differently by surrogate model: 0.7089711022087842
Average confidence score for samples classified same by surrogate model: 0.8631527078894056
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.7070555596167692
Average confidence score for samples classified same by surrogate model: 0.8635470263889126
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.7057865921818292
Average confidence score for samples classified same by surrogate model: 0.8627867944064866
Average confidence score for samples classified differently by surrogate model: 0.8504005891308303
Average confidence score for samples classified same by surrogate model: 0.816650597058244
Average confidence score for samples classified differently by surrogate model: 0.6916662643084643
Average confidence score for samples classified same by surrogate model: 0.8586171057370205
[SHAP base] Sample set 7, n_queries=510, Top similarity=0.8311
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.7357550562486714
Average confidence score for samples classified same by surrogate model: 0.8574192155967081
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8502588683660012
Average confidence score for samples classified same by surrogate model: 0.8167482138506159
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8167197351540207
Average confidence score for samples classified same by surrogate model: 0.8503002139435882
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.7284452449561224
Average confidence score for samples classified same by surrogate model: 0.8532009874098666
Average confidence score for samples classified differently by surrogate model: 0.8012710185598045
Average confidence score for samples classified same by surrogate model: 0.8533734510616238
Average confidence score for samples classified differently by surrogate model: 0.7638738577259759
Average confidence score for samples classified same by surrogate model: 0.8602247557714494
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.7111296489764352
Average confidence score for samples classified same by surrogate model: 0.8644036017888905
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.7755168061630439
Average confidence score for samples classified same by surrogate model: 0.8698946375395832
Average confidence score for samples classified differently by surrogate model: 0.664428450717533
Average confidence score for samples classified same by surrogate model: 0.8523475390199473
Average confidence score for samples classified differently by surrogate model: 0.7996835122387266
Average confidence score for samples classified same by surrogate model: 0.8661864925077187
Average confidence score for samples classified differently by surrogate model: 0.8477806536275078
Average confidence score for samples classified same by surrogate model: 0.8193783722893652
Average confidence score for samples classified differently by surrogate model: 0.7712807199821974
Average confidence score for samples classified same by surrogate model: 0.8478492416810305
Average confidence score for samples classified differently by surrogate model: 0.8448055432984585
Average confidence score for samples classified same by surrogate model: 0.8211982966647272
Average confidence score for samples classified differently by surrogate model: 0.8468268033546813
Average confidence score for samples classified same by surrogate model: 0.819712254185802
[SHAP3]     Sample set 8, n_queries=500, Top similarity=0.8833
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8167197351540207
Average confidence score for samples classified same by surrogate model: 0.8503002139435882
Average confidence score for samples classified differently by surrogate model: 0.8167197351540207
Average confidence score for samples classified same by surrogate model: 0.8503002139435882
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.7754758873950403
Average confidence score for samples classified same by surrogate model: 0.8549802625664993
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.8434309701631465
Average confidence score for samples classified same by surrogate model: 0.8220140705554133
Average confidence score for samples classified differently by surrogate model: 0.8167197351540207
Average confidence score for samples classified same by surrogate model: 0.8503002139435882
Average confidence score for samples classified differently by surrogate model: 0.7706163695944778
Average confidence score for samples classified same by surrogate model: 0.858745866016211
Average confidence score for samples classified differently by surrogate model: 0.8167197351540207
Average confidence score for samples classified same by surrogate model: 0.8503002139435882
Average confidence score for samples classified differently by surrogate model: 0.7959956982270703
Average confidence score for samples classified same by surrogate model: 0.8681452733773048
Average confidence score for samples classified differently by surrogate model: 0.8097583545504
Average confidence score for samples classified same by surrogate model: 0.8561666786612119
Average confidence score for samples classified differently by surrogate model: 0.8401786556869761
Average confidence score for samples classified same by surrogate model: 0.824457899295898
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.789941020374746
Average confidence score for samples classified same by surrogate model: 0.8642566432058735
Average confidence score for samples classified differently by surrogate model: 0.8428536802607178
Average confidence score for samples classified same by surrogate model: 0.8225915474547493
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.6804914473741918
Average confidence score for samples classified same by surrogate model: 0.8544181151332167
Average confidence score for samples classified differently by surrogate model: 0.7613970184639216
Average confidence score for samples classified same by surrogate model: 0.8754709480961594
Average confidence score for samples classified differently by surrogate model: 0.8167197351540207
Average confidence score for samples classified same by surrogate model: 0.8503002139435882
Average confidence score for samples classified differently by surrogate model: 0.7916829481524038
Average confidence score for samples classified same by surrogate model: 0.8448062229248585
[SHAP base] Sample set 8, n_queries=510, Top similarity=0.862
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.768524974618622
Average confidence score for samples classified same by surrogate model: 0.8721504542907861
Average confidence score for samples classified differently by surrogate model: 0.7950953768080856
Average confidence score for samples classified same by surrogate model: 0.8735427073721453
Average confidence score for samples classified differently by surrogate model: 0.813133673436238
Average confidence score for samples classified same by surrogate model: 0.840352841181632
Average confidence score for samples classified differently by surrogate model: 0.7281379663624087
Average confidence score for samples classified same by surrogate model: 0.8564847475872398
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8413061496400349
Average confidence score for samples classified same by surrogate model: 0.8235828125521044
Average confidence score for samples classified differently by surrogate model: 0.7754309354552178
Average confidence score for samples classified same by surrogate model: 0.8618081665513159
Average confidence score for samples classified differently by surrogate model: 0.8174247782405324
Average confidence score for samples classified same by surrogate model: 0.8418094374697003
Average confidence score for samples classified differently by surrogate model: 0.7111217602264666
Average confidence score for samples classified same by surrogate model: 0.8690596358824674
Average confidence score for samples classified differently by surrogate model: 0.832784091829933
Average confidence score for samples classified same by surrogate model: 0.8287806289513115
Average confidence score for samples classified differently by surrogate model: 0.7282742575999892
Average confidence score for samples classified same by surrogate model: 0.862340375880747
Average confidence score for samples classified differently by surrogate model: 0.8017053052540893
Average confidence score for samples classified same by surrogate model: 0.8635592044071927
Average confidence score for samples classified differently by surrogate model: 0.7885086686805021
Average confidence score for samples classified same by surrogate model: 0.8723575676585792
Average confidence score for samples classified differently by surrogate model: 0.7930959018476983
Average confidence score for samples classified same by surrogate model: 0.8623741670004528
Average confidence score for samples classified differently by surrogate model: 0.8502255113072434
Average confidence score for samples classified same by surrogate model: 0.8167827539676232
Average confidence score for samples classified differently by surrogate model: 0.8109559775780528
Average confidence score for samples classified same by surrogate model: 0.8434825024753292
Average confidence score for samples classified differently by surrogate model: 0.6828074111465819
Average confidence score for samples classified same by surrogate model: 0.8571532646414167
Average confidence score for samples classified differently by surrogate model: 0.773389455078004
Average confidence score for samples classified same by surrogate model: 0.869132803871432
Average confidence score for samples classified differently by surrogate model: 0.7817170785408512
Average confidence score for samples classified same by surrogate model: 0.874916643057912
[SHAP3]     Sample set 9, n_queries=500, Top similarity=0.8466
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.816737382919481
Average confidence score for samples classified same by surrogate model: 0.8502914371948757
Average confidence score for samples classified differently by surrogate model: 0.7967578437316666
Average confidence score for samples classified same by surrogate model: 0.8712756095773592
Average confidence score for samples classified differently by surrogate model: 0.744614033653989
Average confidence score for samples classified same by surrogate model: 0.8642419411261454
Average confidence score for samples classified differently by surrogate model: 0.7598155218417287
Average confidence score for samples classified same by surrogate model: 0.866767287215814
Average confidence score for samples classified differently by surrogate model: 0.812405467273664
Average confidence score for samples classified same by surrogate model: 0.8470366476187359
Average confidence score for samples classified differently by surrogate model: 0.8142011285599714
Average confidence score for samples classified same by surrogate model: 0.8471160031876347
Average confidence score for samples classified differently by surrogate model: 0.745332546059783
Average confidence score for samples classified same by surrogate model: 0.863688383509247
Average confidence score for samples classified differently by surrogate model: 0.7977976884299525
Average confidence score for samples classified same by surrogate model: 0.8593301681322191
Average confidence score for samples classified differently by surrogate model: 0.8371834963819643
Average confidence score for samples classified same by surrogate model: 0.8266403716328545
Average confidence score for samples classified differently by surrogate model: 0.798250366705859
Average confidence score for samples classified same by surrogate model: 0.8495891605782893
Average confidence score for samples classified differently by surrogate model: 0.719793660857313
Average confidence score for samples classified same by surrogate model: 0.8474287330552642
Average confidence score for samples classified differently by surrogate model: 0.7028554643504988
Average confidence score for samples classified same by surrogate model: 0.8572175585906406
Average confidence score for samples classified differently by surrogate model: 0.8180907339825183
Average confidence score for samples classified same by surrogate model: 0.8402217470231191
Average confidence score for samples classified differently by surrogate model: 0.813969322616769
Average confidence score for samples classified same by surrogate model: 0.838332479602135
Average confidence score for samples classified differently by surrogate model: 0.7831560306670701
Average confidence score for samples classified same by surrogate model: 0.8744242973586829
Average confidence score for samples classified differently by surrogate model: 0.7945221633405345
Average confidence score for samples classified same by surrogate model: 0.8462193778748542
Average confidence score for samples classified differently by surrogate model: 0.7811398253202091
Average confidence score for samples classified same by surrogate model: 0.8581032386163877
Average confidence score for samples classified differently by surrogate model: 0.8007016461725254
Average confidence score for samples classified same by surrogate model: 0.8738860437188917
Average confidence score for samples classified differently by surrogate model: 0.7771641041045089
Average confidence score for samples classified same by surrogate model: 0.86499997570013
[SHAP base] Sample set 9, n_queries=510, Top similarity=0.8667
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8468757357940302
Average confidence score for samples classified same by surrogate model: 0.8198721773872484
Average confidence score for samples classified differently by surrogate model: 0.7831127495466108
Average confidence score for samples classified same by surrogate model: 0.870590535027645
Average confidence score for samples classified differently by surrogate model: 0.8413662559179962
Average confidence score for samples classified same by surrogate model: 0.8236572182814258
Average confidence score for samples classified differently by surrogate model: 0.7448384715627417
Average confidence score for samples classified same by surrogate model: 0.8595367166584112
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.7349220129231754
Average confidence score for samples classified same by surrogate model: 0.8718948144280984
Average confidence score for samples classified differently by surrogate model: 0.8032585442097224
Average confidence score for samples classified same by surrogate model: 0.8641290216400908
Average confidence score for samples classified differently by surrogate model: 0.8285555249390779
Average confidence score for samples classified same by surrogate model: 0.8312358542719965
Average confidence score for samples classified differently by surrogate model: 0.7930955639054278
Average confidence score for samples classified same by surrogate model: 0.8744673344978147
Average confidence score for samples classified differently by surrogate model: 0.8498454664342161
Average confidence score for samples classified same by surrogate model: 0.8171121936423374
Average confidence score for samples classified differently by surrogate model: 0.7981748975042896
Average confidence score for samples classified same by surrogate model: 0.8509094255786704
Average confidence score for samples classified differently by surrogate model: 0.8016736644634919
Average confidence score for samples classified same by surrogate model: 0.8416786011979907
Average confidence score for samples classified differently by surrogate model: 0.8321191564468404
Average confidence score for samples classified same by surrogate model: 0.8293069658297623
Average confidence score for samples classified differently by surrogate model: 0.8020650702172688
Average confidence score for samples classified same by surrogate model: 0.8406779250136736
Average confidence score for samples classified differently by surrogate model: 0.7929582699778936
Average confidence score for samples classified same by surrogate model: 0.8729160102178523
Average confidence score for samples classified differently by surrogate model: 0.7337014095913651
Average confidence score for samples classified same by surrogate model: 0.8538015407372647
[SHAP3]     Sample set 10, n_queries=500, Top similarity=0.8053
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8272662310633603
Average confidence score for samples classified same by surrogate model: 0.8327740104144536
Average confidence score for samples classified differently by surrogate model: 0.8167197351540207
Average confidence score for samples classified same by surrogate model: 0.8503002139435882
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.746521821777239
Average confidence score for samples classified same by surrogate model: 0.8604647924894232
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.7304951467260326
Average confidence score for samples classified same by surrogate model: 0.8592245594485621
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.849305159562422
Average confidence score for samples classified same by surrogate model: 0.8184713029241145
Average confidence score for samples classified differently by surrogate model: 0.8155202450902105
Average confidence score for samples classified same by surrogate model: 0.8407721101441737
Average confidence score for samples classified differently by surrogate model: 0.7915861581066461
Average confidence score for samples classified same by surrogate model: 0.8723891849699601
Average confidence score for samples classified differently by surrogate model: 0.7720466786804587
Average confidence score for samples classified same by surrogate model: 0.8755599399606684
Average confidence score for samples classified differently by surrogate model: 0.7146215485013842
Average confidence score for samples classified same by surrogate model: 0.8574707168166882
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8416140300787122
Average confidence score for samples classified same by surrogate model: 0.8241127748264323
[SHAP base] Sample set 10, n_queries=510, Top similarity=0.8106
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8167197351540207
Average confidence score for samples classified same by surrogate model: 0.8503002139435882
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8356272613871997
Average confidence score for samples classified same by surrogate model: 0.8272383212507362
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.6760620357964391
Average confidence score for samples classified same by surrogate model: 0.853400195620301
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.7204610346718999
Average confidence score for samples classified same by surrogate model: 0.8649377112668664
Average confidence score for samples classified differently by surrogate model: 0.8500504859385486
Average confidence score for samples classified same by surrogate model: 0.8172434133819915
Average confidence score for samples classified differently by surrogate model: 0.7790019867770903
Average confidence score for samples classified same by surrogate model: 0.8738304598970866
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.7656243729281271
Average confidence score for samples classified same by surrogate model: 0.8811563418438204
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8166156519235643
Average confidence score for samples classified same by surrogate model: 0.8396114404757192
Average confidence score for samples classified differently by surrogate model: 0.7558056243714324
Average confidence score for samples classified same by surrogate model: 0.8726369263307069
Average confidence score for samples classified differently by surrogate model: 0.7816594492256906
Average confidence score for samples classified same by surrogate model: 0.8602232071348888
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.7890656687179665
Average confidence score for samples classified same by surrogate model: 0.8722430880847333
[SHAP3]     Sample set 11, n_queries=500, Top similarity=0.8704
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.8443015371412965
Average confidence score for samples classified same by surrogate model: 0.821566972221069
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.8203207156226312
Average confidence score for samples classified same by surrogate model: 0.8413553253240499
Average confidence score for samples classified differently by surrogate model: 0.8167197351540207
Average confidence score for samples classified same by surrogate model: 0.8503002139435882
Average confidence score for samples classified differently by surrogate model: 0.7895383362621006
Average confidence score for samples classified same by surrogate model: 0.8562873385813753
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.8472983281504404
Average confidence score for samples classified same by surrogate model: 0.8199867897451083
Average confidence score for samples classified differently by surrogate model: 0.8167197351540207
Average confidence score for samples classified same by surrogate model: 0.8503002139435882
Average confidence score for samples classified differently by surrogate model: 0.8490056557417329
Average confidence score for samples classified same by surrogate model: 0.8165102647604994
Average confidence score for samples classified differently by surrogate model: 0.812705400382477
Average confidence score for samples classified same by surrogate model: 0.8450654171325855
Average confidence score for samples classified differently by surrogate model: 0.8200772394445639
Average confidence score for samples classified same by surrogate model: 0.8364502170041642
Average confidence score for samples classified differently by surrogate model: 0.8167717557384364
Average confidence score for samples classified same by surrogate model: 0.8502414921595979
Average confidence score for samples classified differently by surrogate model: 0.8113268505720751
Average confidence score for samples classified same by surrogate model: 0.847603567321897
Average confidence score for samples classified differently by surrogate model: 0.8167197351540207
Average confidence score for samples classified same by surrogate model: 0.8503002139435882
Average confidence score for samples classified differently by surrogate model: 0.8186206613768391
Average confidence score for samples classified same by surrogate model: 0.8363790430280635
Average confidence score for samples classified differently by surrogate model: 0.8262901716338164
Average confidence score for samples classified same by surrogate model: 0.8336309009531233
Average confidence score for samples classified differently by surrogate model: 0.7900056921628079
Average confidence score for samples classified same by surrogate model: 0.8614883794927248
[SHAP base] Sample set 11, n_queries=510, Top similarity=0.6642
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8502078763352746
Average confidence score for samples classified same by surrogate model: 0.8168179738204472
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.7729148938976099
Average confidence score for samples classified same by surrogate model: 0.84728861170617
Average confidence score for samples classified differently by surrogate model: 0.7208472557658449
Average confidence score for samples classified same by surrogate model: 0.864507256592869
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.7791816088810318
Average confidence score for samples classified same by surrogate model: 0.8465923099764224
Average confidence score for samples classified differently by surrogate model: 0.6823860407531117
Average confidence score for samples classified same by surrogate model: 0.8610314761874707
Average confidence score for samples classified differently by surrogate model: 0.7627994916897984
Average confidence score for samples classified same by surrogate model: 0.8780660825547468
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.848940742951487
Average confidence score for samples classified same by surrogate model: 0.8180407810887792
Average confidence score for samples classified differently by surrogate model: 0.7891713318782716
Average confidence score for samples classified same by surrogate model: 0.8710569885236294
Average confidence score for samples classified differently by surrogate model: 0.786908615813377
Average confidence score for samples classified same by surrogate model: 0.8734977847655068
Average confidence score for samples classified differently by surrogate model: 0.770862737725793
Average confidence score for samples classified same by surrogate model: 0.8467057336027878
Average confidence score for samples classified differently by surrogate model: 0.7904829984941267
Average confidence score for samples classified same by surrogate model: 0.8755386180299934
Average confidence score for samples classified differently by surrogate model: 0.7713572979962116
Average confidence score for samples classified same by surrogate model: 0.8481933280514996
Average confidence score for samples classified differently by surrogate model: 0.791585740805696
Average confidence score for samples classified same by surrogate model: 0.8790611753749011
Average confidence score for samples classified differently by surrogate model: 0.8493865612122358
Average confidence score for samples classified same by surrogate model: 0.8180850528610519
[SHAP3]     Sample set 12, n_queries=500, Top similarity=0.8286
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.8490272357073094
Average confidence score for samples classified same by surrogate model: 0.8186165569005365
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8358502778703362
Average confidence score for samples classified same by surrogate model: 0.8275249149852456
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.792442076269563
Average confidence score for samples classified same by surrogate model: 0.8717342523022746
Average confidence score for samples classified differently by surrogate model: 0.8345249836773492
Average confidence score for samples classified same by surrogate model: 0.8278731706050521
Average confidence score for samples classified differently by surrogate model: 0.790972554133883
Average confidence score for samples classified same by surrogate model: 0.8783383345652543
Average confidence score for samples classified differently by surrogate model: 0.7671092747655636
Average confidence score for samples classified same by surrogate model: 0.8755588722001619
Average confidence score for samples classified differently by surrogate model: 0.8416048496439951
Average confidence score for samples classified same by surrogate model: 0.823758152903231
Average confidence score for samples classified differently by surrogate model: 0.8503147345280389
Average confidence score for samples classified same by surrogate model: 0.8167097334236523
Average confidence score for samples classified differently by surrogate model: 0.7773668748845228
Average confidence score for samples classified same by surrogate model: 0.8757312193435387
Average confidence score for samples classified differently by surrogate model: 0.8483097654988135
Average confidence score for samples classified same by surrogate model: 0.819130001073053
Average confidence score for samples classified differently by surrogate model: 0.7858407503279256
Average confidence score for samples classified same by surrogate model: 0.8772367518558305
Average confidence score for samples classified differently by surrogate model: 0.8269385807425974
Average confidence score for samples classified same by surrogate model: 0.832272585734497
Average confidence score for samples classified differently by surrogate model: 0.7389464713747232
Average confidence score for samples classified same by surrogate model: 0.8693044912308372
[SHAP base] Sample set 12, n_queries=510, Top similarity=0.7017
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.7797505629209451
Average confidence score for samples classified same by surrogate model: 0.8503899437188764
Average confidence score for samples classified differently by surrogate model: 0.8503146059885915
Average confidence score for samples classified same by surrogate model: 0.8167793970834067
Average confidence score for samples classified differently by surrogate model: 0.6585677851164032
Average confidence score for samples classified same by surrogate model: 0.843967925989506
Average confidence score for samples classified differently by surrogate model: 0.8167904669252581
Average confidence score for samples classified same by surrogate model: 0.8502310999795772
Average confidence score for samples classified differently by surrogate model: 0.756945046299732
Average confidence score for samples classified same by surrogate model: 0.8505859372478421
Average confidence score for samples classified differently by surrogate model: 0.6476594607456511
Average confidence score for samples classified same by surrogate model: 0.848375155362086
Average confidence score for samples classified differently by surrogate model: 0.7506013830679445
Average confidence score for samples classified same by surrogate model: 0.8713617130980595
Average confidence score for samples classified differently by surrogate model: 0.8041007089783118
Average confidence score for samples classified same by surrogate model: 0.8471572039836633
Average confidence score for samples classified differently by surrogate model: 0.6622218632345426
Average confidence score for samples classified same by surrogate model: 0.8505005522566698
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.6715779531129527
Average confidence score for samples classified same by surrogate model: 0.8466151320925075
Average confidence score for samples classified differently by surrogate model: 0.7030021478656596
Average confidence score for samples classified same by surrogate model: 0.8638003416809483
Average confidence score for samples classified differently by surrogate model: 0.8387824778533146
Average confidence score for samples classified same by surrogate model: 0.8257773468556907
Average confidence score for samples classified differently by surrogate model: 0.849894518824051
Average confidence score for samples classified same by surrogate model: 0.8171238230970067
Average confidence score for samples classified differently by surrogate model: 0.7781095778375254
Average confidence score for samples classified same by surrogate model: 0.8458899763736292
Average confidence score for samples classified differently by surrogate model: 0.7953888777286332
Average confidence score for samples classified same by surrogate model: 0.8592456233107203
Average confidence score for samples classified differently by surrogate model: 0.7870470834909657
Average confidence score for samples classified same by surrogate model: 0.8711668390394883
Average confidence score for samples classified differently by surrogate model: 0.7925358455103804
Average confidence score for samples classified same by surrogate model: 0.8693657586201645
Average confidence score for samples classified differently by surrogate model: 0.8093233464977231
Average confidence score for samples classified same by surrogate model: 0.8582621949282112
[SHAP3]     Sample set 13, n_queries=500, Top similarity=0.9269
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7931729594188478
Average confidence score for samples classified same by surrogate model: 0.8755528355236502
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.8424805376321953
Average confidence score for samples classified same by surrogate model: 0.8223770079308697
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.7835908073987115
Average confidence score for samples classified same by surrogate model: 0.8826354141140647
Average confidence score for samples classified differently by surrogate model: 0.8466419892693439
Average confidence score for samples classified same by surrogate model: 0.8198961319117942
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.8203061081890116
Average confidence score for samples classified same by surrogate model: 0.8350673840771793
Average confidence score for samples classified differently by surrogate model: 0.7208480257294549
Average confidence score for samples classified same by surrogate model: 0.8514630471056789
Average confidence score for samples classified differently by surrogate model: 0.7560267731228143
Average confidence score for samples classified same by surrogate model: 0.8662898202576339
Average confidence score for samples classified differently by surrogate model: 0.8158743595470564
Average confidence score for samples classified same by surrogate model: 0.8443397415964488
Average confidence score for samples classified differently by surrogate model: 0.8163689333112631
Average confidence score for samples classified same by surrogate model: 0.850688908273167
Average confidence score for samples classified differently by surrogate model: 0.6777125540281856
Average confidence score for samples classified same by surrogate model: 0.8534852116683905
Average confidence score for samples classified differently by surrogate model: 0.8413123785259704
Average confidence score for samples classified same by surrogate model: 0.8239943972439052
Average confidence score for samples classified differently by surrogate model: 0.7380143262274752
Average confidence score for samples classified same by surrogate model: 0.853168582656681
Average confidence score for samples classified differently by surrogate model: 0.8358937233052466
Average confidence score for samples classified same by surrogate model: 0.8273517551118336
Average confidence score for samples classified differently by surrogate model: 0.6579438245980167
Average confidence score for samples classified same by surrogate model: 0.8488671838238404
Average confidence score for samples classified differently by surrogate model: 0.6884399620888016
Average confidence score for samples classified same by surrogate model: 0.8540108134257984
Average confidence score for samples classified differently by surrogate model: 0.7842568187465014
Average confidence score for samples classified same by surrogate model: 0.8784260741697029
Average confidence score for samples classified differently by surrogate model: 0.7956371600963719
Average confidence score for samples classified same by surrogate model: 0.8438516393272465
[SHAP base] Sample set 13, n_queries=510, Top similarity=0.9034
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.7110895686573986
Average confidence score for samples classified same by surrogate model: 0.8552731527539628
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.6902774595897031
Average confidence score for samples classified same by surrogate model: 0.8520827521677022
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.7972269055742945
Average confidence score for samples classified same by surrogate model: 0.8473181581750979
Average confidence score for samples classified differently by surrogate model: 0.7555360604461449
Average confidence score for samples classified same by surrogate model: 0.8729023573081739
Average confidence score for samples classified differently by surrogate model: 0.8496787480332159
Average confidence score for samples classified same by surrogate model: 0.8172822242201406
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.8502414921595979
Average confidence score for samples classified same by surrogate model: 0.8167717557384364
Average confidence score for samples classified differently by surrogate model: 0.7008499779505232
Average confidence score for samples classified same by surrogate model: 0.8609309817275769
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8477843468811763
Average confidence score for samples classified same by surrogate model: 0.8190293469060543
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.7589752621767127
Average confidence score for samples classified same by surrogate model: 0.8757477922202171
[SHAP3]     Sample set 14, n_queries=500, Top similarity=0.8661
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8167197351540207
Average confidence score for samples classified same by surrogate model: 0.8503002139435882
Average confidence score for samples classified differently by surrogate model: 0.8167197351540207
Average confidence score for samples classified same by surrogate model: 0.8503002139435882
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.7764124724600617
Average confidence score for samples classified same by surrogate model: 0.8637768264667253
Average confidence score for samples classified differently by surrogate model: 0.8167197351540207
Average confidence score for samples classified same by surrogate model: 0.8503002139435882
Average confidence score for samples classified differently by surrogate model: 0.8163826696853086
Average confidence score for samples classified same by surrogate model: 0.8507550575980509
Average confidence score for samples classified differently by surrogate model: 0.8167197351540207
Average confidence score for samples classified same by surrogate model: 0.8503002139435882
Average confidence score for samples classified differently by surrogate model: 0.7910533623714326
Average confidence score for samples classified same by surrogate model: 0.8607332748103529
Average confidence score for samples classified differently by surrogate model: 0.8167197351540207
Average confidence score for samples classified same by surrogate model: 0.8503002139435882
Average confidence score for samples classified differently by surrogate model: 0.8061700929425942
Average confidence score for samples classified same by surrogate model: 0.8599958958105147
Average confidence score for samples classified differently by surrogate model: 0.8167097334236523
Average confidence score for samples classified same by surrogate model: 0.8503147345280389
Average confidence score for samples classified differently by surrogate model: 0.8036451846683208
Average confidence score for samples classified same by surrogate model: 0.8641768598169217
Average confidence score for samples classified differently by surrogate model: 0.8167197351540207
Average confidence score for samples classified same by surrogate model: 0.8503002139435882
Average confidence score for samples classified differently by surrogate model: 0.7058381489356167
Average confidence score for samples classified same by surrogate model: 0.8653656740639596
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.8073166030031322
Average confidence score for samples classified same by surrogate model: 0.8580665855374361
Average confidence score for samples classified differently by surrogate model: 0.8167197351540207
Average confidence score for samples classified same by surrogate model: 0.8503002139435882
Average confidence score for samples classified differently by surrogate model: 0.8002809063319497
Average confidence score for samples classified same by surrogate model: 0.8610737827118821
Average confidence score for samples classified differently by surrogate model: 0.8167197351540207
Average confidence score for samples classified same by surrogate model: 0.8503002139435882
Average confidence score for samples classified differently by surrogate model: 0.8115592061888605
Average confidence score for samples classified same by surrogate model: 0.8540979300755398
[SHAP base] Sample set 14, n_queries=510, Top similarity=0.7809
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.6742791913138233
Average confidence score for samples classified same by surrogate model: 0.853244675910006
Average confidence score for samples classified differently by surrogate model: 0.798274760788913
Average confidence score for samples classified same by surrogate model: 0.8671245715555823
Average confidence score for samples classified differently by surrogate model: 0.7535528259151887
Average confidence score for samples classified same by surrogate model: 0.8652788671268744
Average confidence score for samples classified differently by surrogate model: 0.811014121956137
Average confidence score for samples classified same by surrogate model: 0.8488117001800237
Average confidence score for samples classified differently by surrogate model: 0.7706557647639397
Average confidence score for samples classified same by surrogate model: 0.8744128728812444
Average confidence score for samples classified differently by surrogate model: 0.7845751603330585
Average confidence score for samples classified same by surrogate model: 0.8553804788575349
Average confidence score for samples classified differently by surrogate model: 0.7969537502813893
Average confidence score for samples classified same by surrogate model: 0.8444208963362088
Average confidence score for samples classified differently by surrogate model: 0.8086075468368183
Average confidence score for samples classified same by surrogate model: 0.8409329615530644
Average confidence score for samples classified differently by surrogate model: 0.7909738939292611
Average confidence score for samples classified same by surrogate model: 0.864274884146364
Average confidence score for samples classified differently by surrogate model: 0.8123590732510783
Average confidence score for samples classified same by surrogate model: 0.8511750004001941
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.8180800488002636
Average confidence score for samples classified same by surrogate model: 0.8403284025301632
Average confidence score for samples classified differently by surrogate model: 0.8329819317972454
Average confidence score for samples classified same by surrogate model: 0.8290197899519425
Average confidence score for samples classified differently by surrogate model: 0.795171883892968
Average confidence score for samples classified same by surrogate model: 0.8519436580710008
Average confidence score for samples classified differently by surrogate model: 0.7792667720904766
Average confidence score for samples classified same by surrogate model: 0.8471690785191699
Average confidence score for samples classified differently by surrogate model: 0.7839790508015715
Average confidence score for samples classified same by surrogate model: 0.86036767192861
Average confidence score for samples classified differently by surrogate model: 0.7420082468694191
Average confidence score for samples classified same by surrogate model: 0.8715561684208166
Average confidence score for samples classified differently by surrogate model: 0.7827287806423419
Average confidence score for samples classified same by surrogate model: 0.8573775420474236
Average confidence score for samples classified differently by surrogate model: 0.8167720708539985
Average confidence score for samples classified same by surrogate model: 0.8375570696656391
[SHAP3]     Sample set 15, n_queries=500, Top similarity=0.8724
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8167197351540207
Average confidence score for samples classified same by surrogate model: 0.8503002139435882
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8256442736947406
Average confidence score for samples classified same by surrogate model: 0.8328594029566411
Average confidence score for samples classified differently by surrogate model: 0.8135831432159965
Average confidence score for samples classified same by surrogate model: 0.8407156279599323
Average confidence score for samples classified differently by surrogate model: 0.8047434765955074
Average confidence score for samples classified same by surrogate model: 0.8444095191607066
Average confidence score for samples classified differently by surrogate model: 0.8257514616766225
Average confidence score for samples classified same by surrogate model: 0.8330695989758292
Average confidence score for samples classified differently by surrogate model: 0.7889522860862623
Average confidence score for samples classified same by surrogate model: 0.8747246431365598
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.7907774375874751
Average confidence score for samples classified same by surrogate model: 0.8533483797541935
Average confidence score for samples classified differently by surrogate model: 0.8039350269107648
Average confidence score for samples classified same by surrogate model: 0.8505414517067562
Average confidence score for samples classified differently by surrogate model: 0.776295061521078
Average confidence score for samples classified same by surrogate model: 0.8645804388664733
Average confidence score for samples classified differently by surrogate model: 0.8374489497104115
Average confidence score for samples classified same by surrogate model: 0.8257814326776006
Average confidence score for samples classified differently by surrogate model: 0.8050749419237748
Average confidence score for samples classified same by surrogate model: 0.8445661620531103
Average confidence score for samples classified differently by surrogate model: 0.8184149673336558
Average confidence score for samples classified same by surrogate model: 0.8369633216955159
Average confidence score for samples classified differently by surrogate model: 0.804718875451031
Average confidence score for samples classified same by surrogate model: 0.8450351338956883
[SHAP base] Sample set 15, n_queries=510, Top similarity=0.6613
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8348443786622569
Average confidence score for samples classified same by surrogate model: 0.8278312641533692
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.799027458812091
Average confidence score for samples classified same by surrogate model: 0.8411663789338057
Average confidence score for samples classified differently by surrogate model: 0.8500228292318354
Average confidence score for samples classified same by surrogate model: 0.817081653543074
Average confidence score for samples classified differently by surrogate model: 0.7070340547519848
Average confidence score for samples classified same by surrogate model: 0.8555667579396489
Average confidence score for samples classified differently by surrogate model: 0.8212767100371178
Average confidence score for samples classified same by surrogate model: 0.8359741247291708
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8501418841571571
Average confidence score for samples classified same by surrogate model: 0.8168633135241692
Average confidence score for samples classified differently by surrogate model: 0.764935773944862
Average confidence score for samples classified same by surrogate model: 0.8479804844861097
Average confidence score for samples classified differently by surrogate model: 0.8479796410483456
Average confidence score for samples classified same by surrogate model: 0.8192711180767706
Average confidence score for samples classified differently by surrogate model: 0.8324435106351836
Average confidence score for samples classified same by surrogate model: 0.8293479789999277
Average confidence score for samples classified differently by surrogate model: 0.8368169943060326
Average confidence score for samples classified same by surrogate model: 0.8261325445624894
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8021955491963966
Average confidence score for samples classified same by surrogate model: 0.8508122821649515
Average confidence score for samples classified differently by surrogate model: 0.8322203641057094
Average confidence score for samples classified same by surrogate model: 0.8294758116138895
Average confidence score for samples classified differently by surrogate model: 0.8464433375226363
Average confidence score for samples classified same by surrogate model: 0.820420145960301
Average confidence score for samples classified differently by surrogate model: 0.7228492632513699
Average confidence score for samples classified same by surrogate model: 0.8549809781712282
Average confidence score for samples classified differently by surrogate model: 0.8130367330232541
Average confidence score for samples classified same by surrogate model: 0.8431681125601662
Average confidence score for samples classified differently by surrogate model: 0.7300483321965033
Average confidence score for samples classified same by surrogate model: 0.8711930041784577
[SHAP3]     Sample set 16, n_queries=500, Top similarity=0.8307
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8127888773839262
Average confidence score for samples classified same by surrogate model: 0.8455105129209685
Average confidence score for samples classified differently by surrogate model: 0.8107032912241414
Average confidence score for samples classified same by surrogate model: 0.8393144727701584
Average confidence score for samples classified differently by surrogate model: 0.8066770719815989
Average confidence score for samples classified same by surrogate model: 0.8575505606533543
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8369616145172268
Average confidence score for samples classified same by surrogate model: 0.8255806871191919
Average confidence score for samples classified differently by surrogate model: 0.8097502400893407
Average confidence score for samples classified same by surrogate model: 0.8388454628177089
Average confidence score for samples classified differently by surrogate model: 0.7936710173540054
Average confidence score for samples classified same by surrogate model: 0.8745462996812225
Average confidence score for samples classified differently by surrogate model: 0.7484140557984285
Average confidence score for samples classified same by surrogate model: 0.8487390186545214
Average confidence score for samples classified differently by surrogate model: 0.8396966574162928
Average confidence score for samples classified same by surrogate model: 0.8238922729741305
Average confidence score for samples classified differently by surrogate model: 0.7463532422707535
Average confidence score for samples classified same by surrogate model: 0.8588977228054819
Average confidence score for samples classified differently by surrogate model: 0.844878109244148
Average confidence score for samples classified same by surrogate model: 0.8209184127355434
Average confidence score for samples classified differently by surrogate model: 0.8297954043477733
Average confidence score for samples classified same by surrogate model: 0.830785844023109
Average confidence score for samples classified differently by surrogate model: 0.8318210077972122
Average confidence score for samples classified same by surrogate model: 0.8295050098760068
Average confidence score for samples classified differently by surrogate model: 0.7586130971244621
Average confidence score for samples classified same by surrogate model: 0.8572864606262007
Average confidence score for samples classified differently by surrogate model: 0.8493429687880005
Average confidence score for samples classified same by surrogate model: 0.8179329928044671
Average confidence score for samples classified differently by surrogate model: 0.7759146050748171
Average confidence score for samples classified same by surrogate model: 0.8736328756532503
Average confidence score for samples classified differently by surrogate model: 0.8484321475807685
Average confidence score for samples classified same by surrogate model: 0.8190822114422024
Average confidence score for samples classified differently by surrogate model: 0.846781625085997
Average confidence score for samples classified same by surrogate model: 0.819995446574283
Average confidence score for samples classified differently by surrogate model: 0.8475496955108269
Average confidence score for samples classified same by surrogate model: 0.8195157884308187
Average confidence score for samples classified differently by surrogate model: 0.7341370848817931
Average confidence score for samples classified same by surrogate model: 0.8663344359299722
[SHAP base] Sample set 16, n_queries=510, Top similarity=0.8174
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7949409782529874
Average confidence score for samples classified same by surrogate model: 0.8734100735670567
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.7850793912951961
Average confidence score for samples classified same by surrogate model: 0.8447141214743806
Average confidence score for samples classified differently by surrogate model: 0.8021991951551161
Average confidence score for samples classified same by surrogate model: 0.8463409732151631
Average confidence score for samples classified differently by surrogate model: 0.8167197351540207
Average confidence score for samples classified same by surrogate model: 0.8503002139435882
Average confidence score for samples classified differently by surrogate model: 0.8261654121190765
Average confidence score for samples classified same by surrogate model: 0.8331575399235502
Average confidence score for samples classified differently by surrogate model: 0.8292937306005577
Average confidence score for samples classified same by surrogate model: 0.831150410813271
Average confidence score for samples classified differently by surrogate model: 0.8216956440375077
Average confidence score for samples classified same by surrogate model: 0.8370102699856802
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.79742567342525
Average confidence score for samples classified same by surrogate model: 0.8572121339937597
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8085565724074795
Average confidence score for samples classified same by surrogate model: 0.8448946257100399
Average confidence score for samples classified differently by surrogate model: 0.8488967305008089
Average confidence score for samples classified same by surrogate model: 0.8183828253199786
Average confidence score for samples classified differently by surrogate model: 0.7912555624979395
Average confidence score for samples classified same by surrogate model: 0.8576650531233266
Average confidence score for samples classified differently by surrogate model: 0.7877739465661003
Average confidence score for samples classified same by surrogate model: 0.8449420896383532
Average confidence score for samples classified differently by surrogate model: 0.8115674730784922
Average confidence score for samples classified same by surrogate model: 0.8445979580895076
Average confidence score for samples classified differently by surrogate model: 0.7731289949332089
Average confidence score for samples classified same by surrogate model: 0.8741725084714056
Average confidence score for samples classified differently by surrogate model: 0.8433581671128875
Average confidence score for samples classified same by surrogate model: 0.8218069267657047
Average confidence score for samples classified differently by surrogate model: 0.7771999724852505
Average confidence score for samples classified same by surrogate model: 0.8496175914941911
[SHAP3]     Sample set 17, n_queries=500, Top similarity=0.7602
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.7266529630491686
Average confidence score for samples classified same by surrogate model: 0.8769431257742324
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.7842435176569299
Average confidence score for samples classified same by surrogate model: 0.8729556183668478
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8487550304024328
Average confidence score for samples classified same by surrogate model: 0.8180705260364078
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8387297082364237
Average confidence score for samples classified same by surrogate model: 0.8258680057385972
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8260248295069718
Average confidence score for samples classified same by surrogate model: 0.8324114384792772
Average confidence score for samples classified differently by surrogate model: 0.7681719634993914
Average confidence score for samples classified same by surrogate model: 0.8724957900299422
Average confidence score for samples classified differently by surrogate model: 0.7436196247024529
Average confidence score for samples classified same by surrogate model: 0.8636743551454636
Average confidence score for samples classified differently by surrogate model: 0.815700554911109
Average confidence score for samples classified same by surrogate model: 0.8500881099614459
Average confidence score for samples classified differently by surrogate model: 0.7968162418182573
Average confidence score for samples classified same by surrogate model: 0.8480657656160975
Average confidence score for samples classified differently by surrogate model: 0.7631412258004177
Average confidence score for samples classified same by surrogate model: 0.8568843794186238
Average confidence score for samples classified differently by surrogate model: 0.8493301387406799
Average confidence score for samples classified same by surrogate model: 0.8179201090336328
[SHAP base] Sample set 17, n_queries=510, Top similarity=0.723
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8166393297027934
Average confidence score for samples classified same by surrogate model: 0.8504678937915882
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8501625128199253
Average confidence score for samples classified same by surrogate model: 0.8169294968407868
Average confidence score for samples classified differently by surrogate model: 0.6825749316365928
Average confidence score for samples classified same by surrogate model: 0.8539217598586922
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8502414921595979
Average confidence score for samples classified same by surrogate model: 0.8167717557384364
Average confidence score for samples classified differently by surrogate model: 0.7874268459419373
Average confidence score for samples classified same by surrogate model: 0.8746552566858652
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.6934627485294279
Average confidence score for samples classified same by surrogate model: 0.8587405929631626
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.6160224486845031
Average confidence score for samples classified same by surrogate model: 0.8451968546520962
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.6465719408558641
Average confidence score for samples classified same by surrogate model: 0.8482552609594142
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
[SHAP3]     Sample set 18, n_queries=500, Top similarity=0.9355
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8111663568958045
Average confidence score for samples classified same by surrogate model: 0.8389979179265747
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.7888365863835662
Average confidence score for samples classified same by surrogate model: 0.8472246290355823
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503147345280389
Average confidence score for samples classified same by surrogate model: 0.8167097334236523
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.6667793568674891
Average confidence score for samples classified same by surrogate model: 0.8492453662967653
Average confidence score for samples classified differently by surrogate model: 0.8101831380841705
Average confidence score for samples classified same by surrogate model: 0.8561873530925346
Average confidence score for samples classified differently by surrogate model: 0.7341551768828736
Average confidence score for samples classified same by surrogate model: 0.8498671178981562
[SHAP base] Sample set 18, n_queries=510, Top similarity=0.8968
Dataset name in traverse_explanations_SHAP3: adult
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.8166576733916754
Average confidence score for samples classified same by surrogate model: 0.8503733900982047
Average confidence score for samples classified differently by surrogate model: 0.8322624443875495
Average confidence score for samples classified same by surrogate model: 0.8288606042714664
Average confidence score for samples classified differently by surrogate model: 0.7662642972713746
Average confidence score for samples classified same by surrogate model: 0.8726175465475666
Average confidence score for samples classified differently by surrogate model: 0.8001347900435861
Average confidence score for samples classified same by surrogate model: 0.8766840579877806
Average confidence score for samples classified differently by surrogate model: 0.8378077245531683
Average confidence score for samples classified same by surrogate model: 0.826472896774009
Average confidence score for samples classified differently by surrogate model: 0.7837804440917514
Average confidence score for samples classified same by surrogate model: 0.8693109778119694
Average confidence score for samples classified differently by surrogate model: 0.781164424935409
Average confidence score for samples classified same by surrogate model: 0.8699917694171385
Average confidence score for samples classified differently by surrogate model: 0.7905854106415893
Average confidence score for samples classified same by surrogate model: 0.8442051335378205
Average confidence score for samples classified differently by surrogate model: 0.7821457708601384
Average confidence score for samples classified same by surrogate model: 0.8784101870953944
Average confidence score for samples classified differently by surrogate model: 0.8195116294095829
Average confidence score for samples classified same by surrogate model: 0.8387448190826249
Average confidence score for samples classified differently by surrogate model: 0.8165522953243514
Average confidence score for samples classified same by surrogate model: 0.8372019110233214
Average confidence score for samples classified differently by surrogate model: 0.8377737295819088
Average confidence score for samples classified same by surrogate model: 0.8257108242321304
Average confidence score for samples classified differently by surrogate model: 0.7641646749743949
Average confidence score for samples classified same by surrogate model: 0.859081432869996
Average confidence score for samples classified differently by surrogate model: 0.8069018725916081
Average confidence score for samples classified same by surrogate model: 0.8523301773794418
Average confidence score for samples classified differently by surrogate model: 0.8086656315200283
Average confidence score for samples classified same by surrogate model: 0.8497598504357871
Average confidence score for samples classified differently by surrogate model: 0.8345597004445612
Average confidence score for samples classified same by surrogate model: 0.8277178895148178
Average confidence score for samples classified differently by surrogate model: 0.7816484261848892
Average confidence score for samples classified same by surrogate model: 0.8649574806633964
Average confidence score for samples classified differently by surrogate model: 0.7903692569655549
Average confidence score for samples classified same by surrogate model: 0.8757043569748425
Average confidence score for samples classified differently by surrogate model: 0.8213869940089474
Average confidence score for samples classified same by surrogate model: 0.8348026987553289
[SHAP3]     Sample set 19, n_queries=500, Top similarity=0.7428
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8503419177612985
Average confidence score for samples classified same by surrogate model: 0.8167026415410682
Average confidence score for samples classified differently by surrogate model: 0.7716598783866864
Average confidence score for samples classified same by surrogate model: 0.8548139363989928
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.7746180307383713
Average confidence score for samples classified same by surrogate model: 0.8656390855529503
Average confidence score for samples classified differently by surrogate model: 0.8503733900982047
Average confidence score for samples classified same by surrogate model: 0.8166576733916754
Average confidence score for samples classified differently by surrogate model: 0.8143557451879301
Average confidence score for samples classified same by surrogate model: 0.8377840727695314
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.7026972570565516
Average confidence score for samples classified same by surrogate model: 0.857097776060722
Average confidence score for samples classified differently by surrogate model: 0.7858976870265895
Average confidence score for samples classified same by surrogate model: 0.8576321630421591
Average confidence score for samples classified differently by surrogate model: 0.848330296187281
Average confidence score for samples classified same by surrogate model: 0.8185604199240537
Average confidence score for samples classified differently by surrogate model: 0.8502914371948757
Average confidence score for samples classified same by surrogate model: 0.816737382919481
Average confidence score for samples classified differently by surrogate model: 0.7984082854946092
Average confidence score for samples classified same by surrogate model: 0.8716972840344048
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.8486344776800264
Average confidence score for samples classified same by surrogate model: 0.8182453763315992
Average confidence score for samples classified differently by surrogate model: 0.7918391398570327
Average confidence score for samples classified same by surrogate model: 0.8816433062914035
Average confidence score for samples classified differently by surrogate model: 0.748404756213041
Average confidence score for samples classified same by surrogate model: 0.8670840661083168
Average confidence score for samples classified differently by surrogate model: 0.8503002139435882
Average confidence score for samples classified same by surrogate model: 0.8167197351540207
Average confidence score for samples classified differently by surrogate model: 0.7843185258303812
Average confidence score for samples classified same by surrogate model: 0.8739799436262696
[SHAP base] Sample set 19, n_queries=510, Top similarity=0.8272

=== Query limit 500 | k=3 | n=5 ===
  [SHAP3 main]    Avg similarity: 0.8493  | All: [0.9335, 0.8327, 0.7901, 0.7998, 0.9226, 0.8262, 0.8888, 0.8231, 0.8833, 0.8466, 0.8053, 0.8704, 0.8286, 0.9269, 0.8661, 0.8724, 0.8307, 0.7602, 0.9355, 0.7428]
  [SHAP baseline] Avg similarity: 0.8098  | All: [0.861, 0.7488, 0.8917, 0.8714, 0.872, 0.8231, 0.7813, 0.8311, 0.862, 0.8667, 0.8106, 0.6642, 0.7017, 0.9034, 0.7809, 0.6613, 0.8174, 0.723, 0.8968, 0.8272]
  Difference (main - baseline): +0.0395


========== FINAL COMPARISON SUMMARY ==========
  [SHAP3 main]    Overall avg similarity: 0.8493
  [SHAP baseline] Overall avg similarity: 0.8098
  Overall difference (main - baseline): +0.0395
===============================================

Avg Similarity: 0.8493 | Baseline: 0.8098
Dataset: 3, Model: 0... DATASET 3 0
Train results
[[159   0]
 [  0 267]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       159
           1       1.00      1.00      1.00       267

    accuracy                           1.00       426
   macro avg       1.00      1.00      1.00       426
weighted avg       1.00      1.00      1.00       426

Test results
[[29  3]
 [ 3 50]]
              precision    recall  f1-score   support

           0       0.91      0.91      0.91        32
           1       0.94      0.94      0.94        53

    accuracy                           0.93        85
   macro avg       0.92      0.92      0.92        85
weighted avg       0.93      0.93      0.93        85

Model test accuracy:  0.9294

Dataset:   Breast Cancer
ML Model:  Decision Tree
SHAP is the explanation tool currently in use

Lower bounds:  [126]  Upper bounds:  [626] (per class for both)

-----The attack starts here!-----

Number of top features allowed to be explored (k): 3

Number of samples per class (n): 5
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0
Error: unhashable type: 'numpy.ndarray'
Dataset: 3, Model: 1... DATASET 3 1
Train results
[[147  12]
 [  5 262]]
              precision    recall  f1-score   support

           0       0.97      0.92      0.95       159
           1       0.96      0.98      0.97       267

    accuracy                           0.96       426
   macro avg       0.96      0.95      0.96       426
weighted avg       0.96      0.96      0.96       426

Test results
[[31  1]
 [ 3 50]]
              precision    recall  f1-score   support

           0       0.91      0.97      0.94        32
           1       0.98      0.94      0.96        53

    accuracy                           0.95        85
   macro avg       0.95      0.96      0.95        85
weighted avg       0.95      0.95      0.95        85

Model test accuracy:  0.9529

Dataset:   Breast Cancer
ML Model:  Logistic Regression
SHAP is the explanation tool currently in use

Lower bounds:  [126]  Upper bounds:  [626] (per class for both)

-----The attack starts here!-----

Number of top features allowed to be explored (k): 3

Number of samples per class (n): 5
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8422138534931393
Average confidence score for samples classified same by surrogate model: 0.973634105442193
[SHAP3]     Sample set 0, n_queries=500, Top similarity=0.9059
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8353523763286055
Average confidence score for samples classified same by surrogate model: 0.9761758626320595
[SHAP base] Sample set 0, n_queries=510, Top similarity=0.8941
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.690738997264952
Average confidence score for samples classified same by surrogate model: 0.9746244562707922
[SHAP3]     Sample set 1, n_queries=500, Top similarity=0.9529
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6097854573288142
Average confidence score for samples classified same by surrogate model: 0.9697345305100764
[SHAP base] Sample set 1, n_queries=510, Top similarity=0.9765
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 8
Diverse samples left to process: 6
Diverse samples left to process: 4
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8221398303031059
Average confidence score for samples classified same by surrogate model: 0.9737507453188748
[SHAP3]     Sample set 2, n_queries=500, Top similarity=0.9176
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7664909016830331
Average confidence score for samples classified same by surrogate model: 0.9734385304822352
[SHAP base] Sample set 2, n_queries=510, Top similarity=0.9412
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 2
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.690738997264952
Average confidence score for samples classified same by surrogate model: 0.9746244562707922
[SHAP3]     Sample set 3, n_queries=500, Top similarity=0.9529
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8371825912771866
Average confidence score for samples classified same by surrogate model: 0.9741568339841101
[SHAP base] Sample set 3, n_queries=510, Top similarity=0.9059
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 2
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7506973001175804
Average confidence score for samples classified same by surrogate model: 0.9772576347631454
[SHAP3]     Sample set 4, n_queries=500, Top similarity=0.9294
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6883467506228942
Average confidence score for samples classified same by surrogate model: 0.974742591907437
[SHAP base] Sample set 4, n_queries=510, Top similarity=0.9529
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8394413746601991
Average confidence score for samples classified same by surrogate model: 0.9739221551910701
[SHAP3]     Sample set 5, n_queries=500, Top similarity=0.9059
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8394413746601991
Average confidence score for samples classified same by surrogate model: 0.9739221551910701
[SHAP base] Sample set 5, n_queries=510, Top similarity=0.9059
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0
Average confidence score for samples classified same by surrogate model: 0.96126514055287
[SHAP3]     Sample set 6, n_queries=500, Top similarity=1.0
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7444123579409219
Average confidence score for samples classified same by surrogate model: 0.9777349721436511
[SHAP base] Sample set 6, n_queries=510, Top similarity=0.9294
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 5
Diverse samples left to process: 2

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7774985086204586
Average confidence score for samples classified same by surrogate model: 0.9777570177775738
[SHAP3]     Sample set 7, n_queries=500, Top similarity=0.9176
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7440981365443671
Average confidence score for samples classified same by surrogate model: 0.977758837059845
[SHAP base] Sample set 7, n_queries=510, Top similarity=0.9294
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6666771578899878
Average confidence score for samples classified same by surrogate model: 0.972042749674683
[SHAP3]     Sample set 8, n_queries=500, Top similarity=0.9647
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8294883296271933
Average confidence score for samples classified same by surrogate model: 0.9749562377919017
[SHAP base] Sample set 8, n_queries=510, Top similarity=0.9059
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8184230568827685
Average confidence score for samples classified same by surrogate model: 0.9761058765185953
[SHAP3]     Sample set 9, n_queries=500, Top similarity=0.9059
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6698668200793984
Average confidence score for samples classified same by surrogate model: 0.9719260547165339
[SHAP base] Sample set 9, n_queries=510, Top similarity=0.9647
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8054733824177426
Average confidence score for samples classified same by surrogate model: 0.9774512972422341
[SHAP3]     Sample set 10, n_queries=500, Top similarity=0.9059
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7444123579409219
Average confidence score for samples classified same by surrogate model: 0.9777349721436511
[SHAP base] Sample set 10, n_queries=510, Top similarity=0.9294
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8299667743016537
Average confidence score for samples classified same by surrogate model: 0.9730483272677231
[SHAP3]     Sample set 11, n_queries=500, Top similarity=0.9176
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7491376009766363
Average confidence score for samples classified same by surrogate model: 0.9745231117763848
[SHAP base] Sample set 11, n_queries=510, Top similarity=0.9412
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8113422598282909
Average confidence score for samples classified same by surrogate model: 0.9812548579828141
[SHAP3]     Sample set 12, n_queries=500, Top similarity=0.8824
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8046703144657182
Average confidence score for samples classified same by surrogate model: 0.9775347328736134
[SHAP base] Sample set 12, n_queries=510, Top similarity=0.9059
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8249746207115178
Average confidence score for samples classified same by surrogate model: 0.9754251945623614
[SHAP3]     Sample set 13, n_queries=500, Top similarity=0.9059
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8104708147756154
Average confidence score for samples classified same by surrogate model: 0.9747979646610855
[SHAP base] Sample set 13, n_queries=510, Top similarity=0.9176
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8243391963565738
Average confidence score for samples classified same by surrogate model: 0.975491212677161
[SHAP3]     Sample set 14, n_queries=500, Top similarity=0.9059
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8257695155497892
Average confidence score for samples classified same by surrogate model: 0.9773106750927087
[SHAP base] Sample set 14, n_queries=510, Top similarity=0.8941
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7665024558599977
Average confidence score for samples classified same by surrogate model: 0.9734378083461748
[SHAP3]     Sample set 15, n_queries=500, Top similarity=0.9412
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7524147222299051
Average confidence score for samples classified same by surrogate model: 0.9715787414577081
[SHAP base] Sample set 15, n_queries=510, Top similarity=0.9529
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7792303897502417
Average confidence score for samples classified same by surrogate model: 0.977601592547978
[SHAP3]     Sample set 16, n_queries=500, Top similarity=0.9176
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7865432976986015
Average confidence score for samples classified same by surrogate model: 0.9721852557312619
[SHAP base] Sample set 16, n_queries=510, Top similarity=0.9412
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7671576440546329
Average confidence score for samples classified same by surrogate model: 0.9760074820590655
[SHAP3]     Sample set 17, n_queries=500, Top similarity=0.9294
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8055642348263815
Average confidence score for samples classified same by surrogate model: 0.9752382987590936
[SHAP base] Sample set 17, n_queries=510, Top similarity=0.9176
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8269262623705934
Average confidence score for samples classified same by surrogate model: 0.9733211937230746
[SHAP3]     Sample set 18, n_queries=500, Top similarity=0.9176
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7424588241166485
Average confidence score for samples classified same by surrogate model: 0.9720703907472517
[SHAP base] Sample set 18, n_queries=510, Top similarity=0.9529
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7852450522964511
Average confidence score for samples classified same by surrogate model: 0.9655065884626632
[SHAP3]     Sample set 19, n_queries=500, Top similarity=0.9765
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.6698668200793984
Average confidence score for samples classified same by surrogate model: 0.9719260547165339
[SHAP base] Sample set 19, n_queries=510, Top similarity=0.9647

=== Query limit 500 | k=3 | n=5 ===
  [SHAP3 main]    Avg similarity: 0.9276  | All: [0.9059, 0.9529, 0.9176, 0.9529, 0.9294, 0.9059, 1.0, 0.9176, 0.9647, 0.9059, 0.9059, 0.9176, 0.8824, 0.9059, 0.9059, 0.9412, 0.9176, 0.9294, 0.9176, 0.9765]
  [SHAP baseline] Avg similarity: 0.9312  | All: [0.8941, 0.9765, 0.9412, 0.9059, 0.9529, 0.9059, 0.9294, 0.9294, 0.9059, 0.9647, 0.9294, 0.9412, 0.9059, 0.9176, 0.8941, 0.9529, 0.9412, 0.9176, 0.9529, 0.9647]
  Difference (main - baseline): -0.0036


========== FINAL COMPARISON SUMMARY ==========
  [SHAP3 main]    Overall avg similarity: 0.9276
  [SHAP baseline] Overall avg similarity: 0.9312
  Overall difference (main - baseline): -0.0035
===============================================

Avg Similarity: 0.9276 | Baseline: 0.9312
Dataset: 3, Model: 2... DATASET 3 2
Train results
[[119  40]
 [  7 260]]
              precision    recall  f1-score   support

           0       0.94      0.75      0.84       159
           1       0.87      0.97      0.92       267

    accuracy                           0.89       426
   macro avg       0.91      0.86      0.88       426
weighted avg       0.90      0.89      0.89       426

Test results
[[25  7]
 [ 2 51]]
              precision    recall  f1-score   support

           0       0.93      0.78      0.85        32
           1       0.88      0.96      0.92        53

    accuracy                           0.89        85
   macro avg       0.90      0.87      0.88        85
weighted avg       0.90      0.89      0.89        85

Model test accuracy:  0.8941

Dataset:   Breast Cancer
ML Model:  Multinomial Naive Bayes
SHAP is the explanation tool currently in use

Lower bounds:  [126]  Upper bounds:  [626] (per class for both)

-----The attack starts here!-----

Number of top features allowed to be explored (k): 3

Number of samples per class (n): 5
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9781872611628486
Average confidence score for samples classified same by surrogate model: 0.9969126619635953
[SHAP3]     Sample set 0, n_queries=500, Top similarity=0.9176
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9715825426990569
Average confidence score for samples classified same by surrogate model: 0.9992809308070095
[SHAP base] Sample set 0, n_queries=510, Top similarity=0.8588
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9781872611628486
Average confidence score for samples classified same by surrogate model: 0.9969126619635953
[SHAP3]     Sample set 1, n_queries=500, Top similarity=0.9176
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9781872611628486
Average confidence score for samples classified same by surrogate model: 0.9969126619635953
[SHAP base] Sample set 1, n_queries=510, Top similarity=0.9176
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9862170695911843
Average confidence score for samples classified same by surrogate model: 0.9967312256188832
[SHAP3]     Sample set 2, n_queries=500, Top similarity=0.8706
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9747317189656494
Average confidence score for samples classified same by surrogate model: 0.9969380778165376
[SHAP base] Sample set 2, n_queries=510, Top similarity=0.9294
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9781872611628486
Average confidence score for samples classified same by surrogate model: 0.9969126619635953
[SHAP3]     Sample set 3, n_queries=500, Top similarity=0.9176
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.973530686489045
Average confidence score for samples classified same by surrogate model: 0.9993138824575387
[SHAP base] Sample set 3, n_queries=510, Top similarity=0.8471
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.951284605517963
Average confidence score for samples classified same by surrogate model: 0.999327002854803
[SHAP3]     Sample set 4, n_queries=500, Top similarity=0.9176
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9783424292299153
Average confidence score for samples classified same by surrogate model: 0.9968987366242431
[SHAP base] Sample set 4, n_queries=510, Top similarity=0.9176
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9810484844780587
Average confidence score for samples classified same by surrogate model: 0.9968585790321546
[SHAP3]     Sample set 5, n_queries=500, Top similarity=0.9059
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9862170695911843
Average confidence score for samples classified same by surrogate model: 0.9967312256188832
[SHAP base] Sample set 5, n_queries=510, Top similarity=0.8706
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9573740298282176
Average confidence score for samples classified same by surrogate model: 0.9993182626321381
[SHAP3]     Sample set 6, n_queries=500, Top similarity=0.9059
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9770599282902934
Average confidence score for samples classified same by surrogate model: 0.9992942790992282
[SHAP base] Sample set 6, n_queries=510, Top similarity=0.8235
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9810490929477115
Average confidence score for samples classified same by surrogate model: 0.9968585158145284
[SHAP3]     Sample set 7, n_queries=500, Top similarity=0.9059
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9842041545026947
Average confidence score for samples classified same by surrogate model: 0.9973867285106297
[SHAP base] Sample set 7, n_queries=510, Top similarity=0.8471
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9781872611628486
Average confidence score for samples classified same by surrogate model: 0.9969126619635953
[SHAP3]     Sample set 8, n_queries=500, Top similarity=0.9176
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9658992026005453
Average confidence score for samples classified same by surrogate model: 0.9993000858039324
[SHAP base] Sample set 8, n_queries=510, Top similarity=0.8824
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9754213517396001
Average confidence score for samples classified same by surrogate model: 0.9993042188302249
[SHAP3]     Sample set 9, n_queries=500, Top similarity=0.8353
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.985332305406423
Average confidence score for samples classified same by surrogate model: 0.9973499462762037
[SHAP base] Sample set 9, n_queries=510, Top similarity=0.8353
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9781872611628486
Average confidence score for samples classified same by surrogate model: 0.9969126619635953
[SHAP3]     Sample set 10, n_queries=500, Top similarity=0.9176
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9747317189656494
Average confidence score for samples classified same by surrogate model: 0.9969380778165376
[SHAP base] Sample set 10, n_queries=510, Top similarity=0.9294
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9781872611628486
Average confidence score for samples classified same by surrogate model: 0.9969126619635953
[SHAP3]     Sample set 11, n_queries=500, Top similarity=0.9176
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9573740298282176
Average confidence score for samples classified same by surrogate model: 0.9993182626321381
[SHAP base] Sample set 11, n_queries=510, Top similarity=0.9059
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9781872611628486
Average confidence score for samples classified same by surrogate model: 0.9969126619635953
[SHAP3]     Sample set 12, n_queries=500, Top similarity=0.9176
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9891705546787877
Average confidence score for samples classified same by surrogate model: 0.996593108391512
[SHAP base] Sample set 12, n_queries=510, Top similarity=0.8353
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9696798885157667
Average confidence score for samples classified same by surrogate model: 0.9969762377340192
[SHAP3]     Sample set 13, n_queries=500, Top similarity=0.9412
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9696798885157667
Average confidence score for samples classified same by surrogate model: 0.9969762377340192
[SHAP base] Sample set 13, n_queries=510, Top similarity=0.9412
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9781872611628486
Average confidence score for samples classified same by surrogate model: 0.9969126619635953
[SHAP3]     Sample set 14, n_queries=500, Top similarity=0.9176
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9891705546787877
Average confidence score for samples classified same by surrogate model: 0.996593108391512
[SHAP base] Sample set 14, n_queries=510, Top similarity=0.8353
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9737684892386496
Average confidence score for samples classified same by surrogate model: 0.9992709458499712
[SHAP3]     Sample set 15, n_queries=500, Top similarity=0.8471
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.951284605517963
Average confidence score for samples classified same by surrogate model: 0.999327002854803
[SHAP base] Sample set 15, n_queries=510, Top similarity=0.9176
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9573740298282176
Average confidence score for samples classified same by surrogate model: 0.9993182626321381
[SHAP3]     Sample set 16, n_queries=500, Top similarity=0.9059
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9754213517396001
Average confidence score for samples classified same by surrogate model: 0.9993042188302249
[SHAP base] Sample set 16, n_queries=510, Top similarity=0.8353
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9737684892386496
Average confidence score for samples classified same by surrogate model: 0.9992709458499712
[SHAP3]     Sample set 17, n_queries=500, Top similarity=0.8471
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9689992750911155
Average confidence score for samples classified same by surrogate model: 0.9992906275040285
[SHAP base] Sample set 17, n_queries=510, Top similarity=0.8706
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9689992935619176
Average confidence score for samples classified same by surrogate model: 0.9992906247583686
[SHAP3]     Sample set 18, n_queries=500, Top similarity=0.8706
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9809138531126821
Average confidence score for samples classified same by surrogate model: 0.9968725667064795
[SHAP base] Sample set 18, n_queries=510, Top similarity=0.9059
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9696798885157667
Average confidence score for samples classified same by surrogate model: 0.9969762377340192
[SHAP3]     Sample set 19, n_queries=500, Top similarity=0.9412
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.983154196167003
Average confidence score for samples classified same by surrogate model: 0.9968172459973337
[SHAP base] Sample set 19, n_queries=510, Top similarity=0.8941

=== Query limit 500 | k=3 | n=5 ===
  [SHAP3 main]    Avg similarity: 0.9018  | All: [0.9176, 0.9176, 0.8706, 0.9176, 0.9176, 0.9059, 0.9059, 0.9059, 0.9176, 0.8353, 0.9176, 0.9176, 0.9176, 0.9412, 0.9176, 0.8471, 0.9059, 0.8471, 0.8706, 0.9412]
  [SHAP baseline] Avg similarity: 0.88  | All: [0.8588, 0.9176, 0.9294, 0.8471, 0.9176, 0.8706, 0.8235, 0.8471, 0.8824, 0.8353, 0.9294, 0.9059, 0.8353, 0.9412, 0.8353, 0.9176, 0.8353, 0.8706, 0.9059, 0.8941]
  Difference (main - baseline): +0.0218


========== FINAL COMPARISON SUMMARY ==========
  [SHAP3 main]    Overall avg similarity: 0.9018
  [SHAP baseline] Overall avg similarity: 0.88
  Overall difference (main - baseline): +0.0218
===============================================

Avg Similarity: 0.9018 | Baseline: 0.8800
Dataset: 3, Model: 3... DATASET 3 3
Train results
[[159   0]
 [ 12 255]]
              precision    recall  f1-score   support

           0       0.93      1.00      0.96       159
           1       1.00      0.96      0.98       267

    accuracy                           0.97       426
   macro avg       0.96      0.98      0.97       426
weighted avg       0.97      0.97      0.97       426

Test results
[[30  2]
 [ 4 49]]
              precision    recall  f1-score   support

           0       0.88      0.94      0.91        32
           1       0.96      0.92      0.94        53

    accuracy                           0.93        85
   macro avg       0.92      0.93      0.93        85
weighted avg       0.93      0.93      0.93        85

Model test accuracy:  0.9294

Dataset:   Breast Cancer
ML Model:  K Nearest Neighbor
SHAP is the explanation tool currently in use

Lower bounds:  [126]  Upper bounds:  [626] (per class for both)

-----The attack starts here!-----

Number of top features allowed to be explored (k): 3

Number of samples per class (n): 5
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.875
Average confidence score for samples classified same by surrogate model: 0.961038961038961
[SHAP3]     Sample set 0, n_queries=500, Top similarity=0.9059
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8125
Average confidence score for samples classified same by surrogate model: 0.9675324675324676
[SHAP base] Sample set 0, n_queries=510, Top similarity=0.9059
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9545454545454546
Average confidence score for samples classified same by surrogate model: 0.9523809523809523
[SHAP3]     Sample set 1, n_queries=500, Top similarity=0.7412
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8636363636363636
Average confidence score for samples classified same by surrogate model: 0.9662162162162162
[SHAP base] Sample set 1, n_queries=510, Top similarity=0.8706
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9615384615384616
Average confidence score for samples classified same by surrogate model: 0.9513888888888888
[SHAP3]     Sample set 2, n_queries=500, Top similarity=0.8471
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 0.9444444444444444
[SHAP base] Sample set 2, n_queries=510, Top similarity=0.8471
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.875
Average confidence score for samples classified same by surrogate model: 0.9567901234567902
[SHAP3]     Sample set 3, n_queries=500, Top similarity=0.9529
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.875
Average confidence score for samples classified same by surrogate model: 0.9567901234567902
[SHAP base] Sample set 3, n_queries=510, Top similarity=0.9529
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9666666666666667
Average confidence score for samples classified same by surrogate model: 0.95
[SHAP3]     Sample set 4, n_queries=500, Top similarity=0.8235
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 0.9459459459459459
[SHAP base] Sample set 4, n_queries=510, Top similarity=0.8706
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9285714285714286
Average confidence score for samples classified same by surrogate model: 0.9609375
[SHAP3]     Sample set 5, n_queries=500, Top similarity=0.7529
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.7222222222222222
Average confidence score for samples classified same by surrogate model: 0.9802631578947368
[SHAP base] Sample set 5, n_queries=510, Top similarity=0.8941
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 2
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 0.9487179487179487
[SHAP3]     Sample set 6, n_queries=500, Top similarity=0.9176
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9615384615384616
Average confidence score for samples classified same by surrogate model: 0.9513888888888888
[SHAP base] Sample set 6, n_queries=510, Top similarity=0.8471
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8333333333333334
Average confidence score for samples classified same by surrogate model: 0.9620253164556962
[SHAP3]     Sample set 7, n_queries=500, Top similarity=0.9294
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.875
Average confidence score for samples classified same by surrogate model: 0.9567901234567902
[SHAP base] Sample set 7, n_queries=510, Top similarity=0.9529
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9166666666666666
Average confidence score for samples classified same by surrogate model: 0.958904109589041
[SHAP3]     Sample set 8, n_queries=500, Top similarity=0.8588
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9615384615384616
Average confidence score for samples classified same by surrogate model: 0.9513888888888888
[SHAP base] Sample set 8, n_queries=510, Top similarity=0.8471
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.875
Average confidence score for samples classified same by surrogate model: 0.9567901234567902
[SHAP3]     Sample set 9, n_queries=500, Top similarity=0.9529
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.5
Average confidence score for samples classified same by surrogate model: 0.98125
[SHAP base] Sample set 9, n_queries=510, Top similarity=0.9412
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9230769230769231
Average confidence score for samples classified same by surrogate model: 0.9583333333333334
[SHAP3]     Sample set 10, n_queries=500, Top similarity=0.8471
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9166666666666666
Average confidence score for samples classified same by surrogate model: 0.958904109589041
[SHAP base] Sample set 10, n_queries=510, Top similarity=0.8588
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9285714285714286
Average confidence score for samples classified same by surrogate model: 0.9577464788732394
[SHAP3]     Sample set 11, n_queries=500, Top similarity=0.8353
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.8846153846153846
Average confidence score for samples classified same by surrogate model: 0.9652777777777778
[SHAP base] Sample set 11, n_queries=510, Top similarity=0.8471
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9615384615384616
Average confidence score for samples classified same by surrogate model: 0.9513888888888888
[SHAP3]     Sample set 12, n_queries=500, Top similarity=0.8471
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9166666666666666
Average confidence score for samples classified same by surrogate model: 0.9556962025316456
[SHAP base] Sample set 12, n_queries=510, Top similarity=0.9294
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.875
Average confidence score for samples classified same by surrogate model: 0.9657534246575342
[SHAP3]     Sample set 13, n_queries=500, Top similarity=0.8588
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.875
Average confidence score for samples classified same by surrogate model: 0.9710144927536232
[SHAP base] Sample set 13, n_queries=510, Top similarity=0.8118
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 8
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 3
Diverse samples left to process: 2
Diverse samples left to process: 1
Diverse samples left to process: 0

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 0.9642857142857143
Average confidence score for samples classified same by surrogate model: 0.9507042253521126
[SHAP3]     Sample set 14, n_queries=500, Top similarity=0.8353
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 0.9493670886075949
[SHAP base] Sample set 14, n_queries=510, Top similarity=0.9294
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 8
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 3

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 0.9466666666666667
[SHAP3]     Sample set 15, n_queries=500, Top similarity=0.8824
1 2 3 4 5 Average confidence score for samples classified differently by surrogate model: 1.0
Average confidence score for samples classified same by surrogate model: 0.9466666666666667
[SHAP base] Sample set 15, n_queries=510, Top similarity=0.8824
Dataset name in traverse_explanations_SHAP3: breast
Diverse samples left to process: 9
Diverse samples left to process: 7
Diverse samples left to process: 6
Diverse samples left to process: 5
Diverse samples left to process: 4
Diverse samples left to process: 2

  0%|          | 0/10 [00:00<?, ?it/s]

1 2 3

In [ ]:
import pandas as pd
import numpy as np

# Create DataFrames from the collected results dynamically
dataset_names = ['iris', 'crop', 'adult']
model_names = ['DT', 'LR', 'NB', 'KNN', 'RF', 'P']

# Results DataFrame (Main)
results_df = pd.DataFrame(all_results)
results_pivot = results_df.pivot(index='dataset', columns='model', values='avg_similarity')
results_pivot.index = dataset_names[:len(results_pivot.index)]
results_pivot.columns = model_names[:len(results_pivot.columns)]

# Baseline DataFrame
baseline_df_raw = pd.DataFrame(baseline_results)
baseline_df = baseline_df_raw.pivot(index='dataset', columns='model', values='avg_similarity')
baseline_df.index = dataset_names[:len(baseline_df.index)]
baseline_df.columns = model_names[:len(baseline_df.columns)]

print("\nResults Pivot Table (Main):")
display(results_pivot)

print("\nBaseline Pivot Table:")
display(baseline_df)

# Calculate Differences
diff_df = results_pivot - baseline_df
pct_change_df = (diff_df / baseline_df) * 100

# Professional Styling
# Find the largest absolute change to center the color scale at zero
v_limit = max(abs(diff_df.min().min()), abs(diff_df.max().max()), 0.001)

# --- Table 1: Final Results (Colored by Change Magnitude) ---
styled_results = results_pivot.style.background_gradient(
    cmap='RdYlGn', 
    axis=None, 
    gmap=diff_df, # Use the difference values for the background color
    vmin=-v_limit, 
    vmax=v_limit
).format(precision=4, na_rep="N/A").set_caption("Similarity Results (Colors = Change from Baseline)")

# --- Table 2: Percentage Change Table ---
styled_pct = pct_change_df.style.background_gradient(
    cmap='RdYlGn', 
    axis=None, 
    vmin=-10, # Intensity caps at +/- 10%
    vmax=10
).format("{:+.2f}%", na_rep="N/A").set_caption("Percentage Change vs Baseline")

# Display in Notebook
display(styled_results)
display(styled_pct)

Results Pivot Table (Main):

             DT       LR        NB       KNN        RF         P
iris        NaN      NaN       NaN       NaN       NaN       NaN
crop   0.913725  0.78078  0.723330  0.664710  0.977840  0.652155
adult  0.820305  0.84682  0.908505  0.866205  0.896255  0.983250

Baseline Pivot Table:

            DT        LR        NB       KNN       RF        P
iris       NaN       NaN       NaN       NaN      NaN      NaN
crop   0.91295  0.743335  0.698435  0.653135  0.97314  0.65254
adult  0.82990  0.840160  0.921110  0.855655  0.89448  0.98456

In [ ]:
# visualize results x axis is the explanation type, y axis is the similarity
import numpy as np
import matplotlib.pyplot as plt

# Resolve readable dataset/model names
dataset_dict, model_dict, exp_dict = load_experiment_dicts()
dataset_label = dataset_dict.get(which_dataset, f"Dataset {which_dataset}")
model_label = model_dict.get(which_model, f"Model {which_model}")

explanation_types = list(results.keys())
similarities = [np.mean(results[etype]['rtest_sims']) for etype in explanation_types]

# each bar should have different pastel color
colors = ['#AEC6CF', '#77DD77', '#FFB347', '#B39EB5', '#FF6961', '#FDFD96', '#CB99C9', '#CFCFC4', '#F49AC2', '#C23B22']

plt.figure(figsize=(9,5))
plt.bar(explanation_types, similarities, color=colors[:len(explanation_types)])

# put the value on top of each bar
for i, v in enumerate(similarities):
    plt.text(i, v + 0.001, f"{v:.3f}", ha='center', fontweight='bold')

# Add labels and title (include dataset and model)
plt.xlabel('Explanation Type')
plt.ylabel('Average Similarity')  # focus on 0.5 to 1.0 range
plt.ylim(0.5, 1.0)
plt.title(f'Average Similarity by Explanation Type\nDataset: {dataset_label} | Model: {model_label}', fontsize=12)

# Add small info string with other parameters below the chart
info_str = f"sets={how_many_sets} | sample_set_sizes={sample_set_sizes} | nfe={nfe} | ql={query_limit}"
ax = plt.gca()
ax.text(0.99, -0.12, info_str, ha='right', va='top', transform=ax.transAxes, fontsize=9,
        bbox=dict(facecolor='white', alpha=0.6, edgecolor='none'))

plt.tight_layout()
plt.show()

In [ ]:
#run attack with different models and datasets and different top_exp values
#keep the average similarity results for each combination and visualize them later
explanation_tool = 1 # 'Lime = 0', 'Shap = 1'
how_many_sets = 10 # This is the number of auxiliary datasets to experiment on. Lower the number for lowering the runtime.
sample_set_sizes = [5] # (list of n values from the paper) Size of auxiliary dataset (per class) in a list format
nfe = [3] # (list of k values from the paper) Number of features explored in a list format
query_limit = [500] # (list of Q values from the paper) Number of queries allowed for traversal
import numpy as np
for which_dataset in [2]:
    for which_model in range(4,6):
        for top_exp in [1,3,5,7]:
            results, other_args = run_attack_auto_v2(which_dataset, which_model, explanation_tool, how_many_sets, sample_set_sizes, nfe, query_limit, False, top_exp)
            print(f"Dataset: {which_dataset}, Model: {which_model}, Top Exp: {top_exp}")
            for etype in results.keys():
                #save the results to use later
                np.save(f"results/results_dataset{which_dataset}_model{which_model}_topexp{top_exp}_etype{etype}.npy", results[etype]['rtest_sims'])
                print(f"Explanation Type: {etype}")
                print("Average Similarity and Std Dev: ", np.mean(results[etype]['rtest_sims']), np.std(results[etype]['rtest_sims']))
        print()

In [ ]:
# read saved results and visualize. Group by dataset and model, x axis is top_exp, y axis is average similarity, different lines for different explanation types
import numpy as np
import matplotlib.pyplot as plt 
which_dataset = 2    
explanation_types = ["vanilla", "topk", "random", "zero"]

for which_model in range(6):
    top_exps = [1,3, 5, 7]
    for etype in explanation_types:
        avg_similarities = []
        for top_exp in top_exps: #results are saved in "results" folder with this naming convention                  
            try:
                sims = np.load(f"results/results_dataset{which_dataset}_model{which_model}_topexp{top_exp}_etype{etype}.npy")
            except FileNotFoundError:
                avg_similarities.append(0)
                continue
            avg_similarities.append(np.mean(sims))
        plt.plot(top_exps, avg_similarities, marker='o', label=etype)
    plt.xlabel('Top Explanations Used')
    plt.ylabel('Average Similarity')
    plt.title(f'Dataset: {which_dataset}, Model: {which_model}')
    plt.legend()
    plt.show()

In [ ]:
import glob
import os
import re
import numpy as np
import matplotlib.pyplot as plt

# Read results for dataset 1, grouped by model
# X-axis: top_exp values, Y-axis: average similarity, different lines for each explanation type

dataset_idx = 1
top_exps_to_read = [1, 3, 5, 7, 10]
explanation_types = ['vanilla', 'topk', 'random', 'zero', 'hybrid']

# Find all result files for dataset 1
pattern = f"results_dataset{dataset_idx}_model*_topexp*_etype*.npy"
files = glob.glob(pattern)
print(f"Found {len(files)} result files for dataset {dataset_idx}")

# Parse filenames to organize data
# data[model_idx][etype] = {top_exp: avg_similarity}
data = {}
available_etypes = set()
available_models = set()

rx = re.compile(r"results_dataset(\d+)_model(\d+)_topexp(\d+)_etype(.+)\.npy")
for fpath in files:
    fname = os.path.basename(fpath)
    m = rx.match(fname)
    if not m:
        continue
    _, model_s, topexp_s, etype = m.groups()
    model_idx = int(model_s)
    topexp = int(topexp_s)
    
    available_models.add(model_idx)
    available_etypes.add(etype)
    
    try:
        sims = np.load(fpath, allow_pickle=True)
        sims = np.asarray(sims).ravel()
        if len(sims) == 0:
            continue
        avg_sim = float(np.mean(sims))
        data.setdefault(model_idx, {}).setdefault(etype, {})[topexp] = avg_sim
    except Exception as e:
        print(f"Failed to load {fpath}: {e}")

if len(data) == 0:
    print("No data loaded.")
else:
    available_models_sorted = sorted(available_models)
    available_etypes_sorted = sorted(available_etypes)
    
    # Plot: one subplot per model
    n_models = len(available_models_sorted)
    n_cols = 2
    n_rows = (n_models + n_cols - 1) // n_cols
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(12, 4 * n_rows))
    axes = axes.ravel() if n_models > 1 else [axes]
    
    for idx, model_idx in enumerate(available_models_sorted):
        ax = axes[idx]
        for etype in available_etypes_sorted:
            sim_values = []
            topexp_values = []
            for te in top_exps_to_read:
                if te in data.get(model_idx, {}).get(etype, {}):
                    topexp_values.append(te)
                    sim_values.append(data[model_idx][etype][te])
            
            if len(sim_values) > 0:
                ax.plot(topexp_values, sim_values, marker='o', label=etype, linewidth=2)
        
        ax.set_xlabel('Top Explanations (top_exp)')
        ax.set_ylabel('Average Similarity')
        ax.set_title(f'Dataset {dataset_idx}, Model {model_idx}')
        ax.legend()
        ax.grid(True, alpha=0.3)
    
    # Hide unused subplots
    for idx in range(n_models, len(axes)):
        axes[idx].set_visible(False)
    
    plt.tight_layout()
    plt.show()
    
    print(f"\nAvailable explanation types: {sorted(available_etypes_sorted)}")
    print(f"Available models: {sorted(available_models_sorted)}")

In [ ]:
#Visualize the saved results
import numpy as np
import matplotlib.pyplot as plt
for which_dataset in range(6):
    for which_model in range(6):
        top_exp_values = [1, 3, 5, 7, 10]
        explanation_types = []
        avg_similarities = {top_exp: [] for top_exp in top_exp_values}
        for top_exp in top_exp_values:
            for etype in ['vanilla', 'shap', 'lime']:
                try:
                    sims = np.load(f"results_dataset{which_dataset}_model{which_model}_topexp{top_exp}_etype{etype}.npy")
                    explanation_types.append(etype)
                    avg_similarities[top_exp].append(np.mean(sims))
                except FileNotFoundError:
                    continue
        #plotting
        x = np.arange(len(explanation_types))
        width = 0.15
        fig, ax = plt.subplots()
        for i, top_exp in enumerate(top_exp_values):
            ax.bar(x + i*width, avg_similarities[top_exp], width, label=f'Top Exp {top_exp}')
        ax.set_xlabel('Explanation Type')
        ax.set_ylabel('Average Similarity')
        ax.set_title(f'Average Similarity by Explanation Type\nDataset: {which_dataset}, Model: {which_model}')
        ax.set_xticks(x + width * (len(top_exp_values) - 1) / 2)
        ax.set_xticklabels(explanation_types)
        ax.legend()
        plt.show()

In [ ]:
# ...existing code...
def _flatten_and_stats(mat3d):
    """Convert nested list (dims x rows x cols) to numpy and return mean/std."""
    arr = np.array(mat3d, dtype=float)
    if arr.size == 0:
        return float('nan'), float('nan')
    return float(np.nanmean(arr)), float(np.nanstd(arr))


def sweep_top_exp(wd=which_dataset, wm=which_model, et=explanation_tool, hms=how_many_sets, sss=sample_set_sizes, nfe=nfe, ql=query_limit, so=False, top_exp_list=[1,3,5,10]):
    """
    Run run_attack_auto_v2 for each value in top_exp_list and return summary metrics.
    Returns dict: {top_exp: {'acc_mean':..., 'acc_std':..., 'sim_mean':..., 'sim_std':..., 'raw': (accuracies, sims)}}
    """
    results = {}
    for te in top_exp_list:
        print(f"\nRunning attack with top_exp = {te}")
        accs, sims, smega, other = run_attack_auto_v2(which_dataset, which_model, explanation_tool, how_many_sets, sample_set_sizes, nfe, query_limit, False, top_exp=te)
        acc_mean, acc_std = _flatten_and_stats(accs)
        sim_mean, sim_std = _flatten_and_stats(sims)
        results[te] = {
            'acc_mean': acc_mean,
            'acc_std': acc_std,
            'sim_mean': sim_mean,
            'sim_std': sim_std,
            'raw': (accs, sims, smega, other)
        }
        print(f"top_exp={te} -> acc_mean={acc_mean:.4f}, acc_std={acc_std:.4f}, sim_mean={sim_mean:.4f}, sim_std={sim_std:.4f}")
    return results
# ...existing code...

In [ ]:
# from attack_utils import sweep_top_exp
top_values = [1]
res = sweep_top_exp(top_exp_list=top_values)

In [ ]:
# Inspect results
print("\nSummary of results:")
print("TopExp\tAccMean\tSimMean\tSimStd")
for te, stats in res.items():
    print(te, stats['acc_mean'], stats['sim_mean'], stats['sim_std'])

In [ ]:
# write the results to results.txt file for later analysis add a header line
with open("results.txt", "a") as f:
    f.write("TopExp\tAccMean\tSimMean\n")
    for te, stats in res.items():
        f.write(f"{te}\t{stats['acc_mean']}\t{stats['sim_mean']}\n")